package.json
Avoids ssh permission errors during `npm install`. Excited to try this out!
=> Use HTTPS github url instead of SSH

src/index.js, src/schemaGenerator.js, test/testSchemaGenerator.js
Breaks out a bunch of functions from generateSchema so they can be used on any GraphQL schema on their own.
=> Refactor generateSchema

src/schemaGenerator.js, test/testSchemaGenerator.js
Features:
* Define a root resolve function
* Attach loaders to schema
Still to be done:
* more tests to get 100% coverage
* update the apollo-demo to use the above features
=> Attach loaders

package.json, src/apolloServer.js, src/schemaGenerator.js, test/testApolloServer.js, test/testApolloServerHTTP.js, test/testSchemaGenerator.js, test/tests.js
Basically, I think apolloServer is now usable and passes all express-graphql tests and a bunch more for the added functionality.
=> Apollo http tests

src/schemaGenerator.js, test/testSchemaGenerator.js
This adds support for interfaces, union types and scalars via the addResolveFunctionsToSchema. That function should probably be renamed to something like addExecutionInfoToSchema, because it's no longer just resolve functions.
=> Interface support

package.json, src/mock.js, test/testMocking.js
This solves #34 partly by returning a random implementing type. The mock function hints at what type is returned by setting typename on the object. Unions must thus have a resolveType method that looks like this in order to work (this is something I recommend doing anyway, in order to avoid fuzzy type logic which could be hard to debug).
```js
resolveType(data, context, info){
return info.schema.getType(data.typename);
}
```
For interfaces it's a bit trickier, because they don't know what types implement them. It should however be possible to simply check all types in the schema to see if they implement the interface.
=> Mock unions

src/schemaGenerator.js, test/testSchemaGenerator.js
Does what it says. This is useful for taking tokens etc from the context during the construction of a connector.
=> pass context to connector constructor

package.json, src/mock.js
Pretty straight forward. Random generator can't be seeded, but you can override the defaults to get deterministic behavior. Maybe we'll put in something seedable later.
=> remove casual dependency

package.json
I also updated `graphql` to `0.6.0` since there are no breaking changes and all tests passed with it. However if you don't want to update yet I'll change it back to `0.5.0`.
Fixes #50.
=> Make `graphql` a peer dependency

src/mock.js
It should use nullable type but it wasn't the case for GraphQLList.
=> Use nullable type. Fixes #56

src/apolloServer.js, test/testApolloServer.js
These patches allow to specify both resolvers and mocks options in a call to apolloServer. It is motivated by the need to define a resolveType function for mocking union types.
Related issues:
#60 
https://github.com/apollostack/apollo-starter-kit/issues/9
=> Issue 60/resolvers and mocking

src/mock.js, test/testMocking.js
#34 
Randomly chooses a concrete type that implements the mocked interface and mocks that concrete type.
=> Mock interfaces

.travis.yml, package.json, src/schemaGenerator.js
Firstly thanks for this great library!
I noticed that alot of the dependencies in package.json could be moved to devDependencies since they are only referenced from test files. I also changed lodash to lodash.uniq since this is the only function used. This makes a fair bit of difference on the install size of the production version of node_modules 7MB down to 100 KB.
=> reduce package size

CHANGELOG.md, src/schemaGenerator.js, test/testSchemaGenerator.js
This PR is meant to allow use of the following IDL syntax:
https://github.com/graphql/graphql-js/blob/9ea8196c2af97551bab5cfd57201c29e3085ee4e/src/utilities/__tests__/extendSchema.js#L127
It seems to a feature that was meant to be used for client purposes only.
But, in my opinion, while using the IDL to describe type definitions, you lose to ability to do cyclic dependencies and by that, the ability to create suite packages that will enhance and be enhanced by your own application code base.
e.g: 
Consider the [accounts package](https://github.com/davidyaha/apollo-accounts-server/blob/master/server/imports/api/schema.js) as the sole owner of the User type, being so, in your own schema files, you would like to use that same User type to describe relations to other types. 
Lets say Post
``` …
```
=> Added `extend` support to schemaGenerator

CHANGELOG.md, package.json
=> unpin babel-core

src/mock.js, test/testMocking.js
=> mock unions and interfaces

CHANGELOG.md, src/schemaGenerator.js, test/testSchemaGenerator.js
Asserts that _all_ fields have a valid resolve function.  This effectively disables default resolver behavior.
---
For example, we have a strict set of ACL decorators for our resolvers, and we want developers to be explicit about the access control for each new field they add to our schema
---
TODO:
=> Add `requireResolversForAllFields` resolver validation option

CHANGELOG.md, src/mock.js, test/testMocking.js
Here is a test that show that that last commit in #96 broke `preserveResolvers` for root resolvers.
Turns out, that test was already there, but no mock was in `mockMap` so nothing could take precedence.
@helfer I'll work on a fix.
=> Fix preserveResolvers for root resolvers

CHANGELOG.md, index.d.ts, package.json
=> Added embedded Typescript definitions.

CHANGELOG.md, src/mock.js, test/testMocking.js
I've noted a bug with @sebastienbarre 's new logic to merge resolvers & mocks ([#115](https://github.com/apollostack/graphql-tools/pull/115))
Basiclly, if there is a connector or a logger (or any other wrapper, hidden as a resolve function),
the original resolve function value will be undefined (as it's not provided)
and then an undefined will be returned, instead of the proper mocked value.
TODO:
=> Bugfix for resolving & mocking, when resolve is wrapped

CHANGELOG.md, index.d.ts
TODO:
…pt compiler errors (#132)
=> Add missing type annotations to avoid typescript compiler errors when 'noImplicitAny' is enabled

CHANGELOG.md, src/schemaGenerator.js, test/testSchemaGenerator.js
As talked in #131, resolve function missing validator is now showing a warning instead of an error
=> Change resolve function missing error to warning

CHANGELOG.md, package.json
as discuessed in apollostack/meteor-starter-kit#30
@helfer, do we need to update CHANGLOG for that? i wouldn't..
TODO:
=> changed graphql-typings dependency from peer to standard

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, package.json
Hi,
I've added a new command, npm run release which runs standard version for automatic semver + changelog.
TODO:
=> Standard version supprt

package.json
as autopublish feature exports a symbol from graphql-subscriptions package,
it should be either move to dependencies or copied to peerDependencies.
TODO:
=> chore(package): copy graphql-subscriptions to peerDepenecies

src/schemaGenerator.ts
Resolve `Promise` in schema level resolver if one is returned, conforming to behaviour of all other resolvers.
This should cause no change in current functionality, due to the use of `Promise.resolve`.
=> Resolve Promise for `addSchemaLevelResolver`

src/schemaGenerator.ts, src/test/testSchemaGenerator.ts
=> fix for custom scalar client-side usage

CHANGELOG.md, src/schemaGenerator.ts, src/test/testResolution.ts, src/test/tests.ts
Basically, we isolate here the "run once" between possible operations instead of having them for all of the operations. Sometimes, a race condition could indeed mess with the root value of a subscription. We ensure this does not happen here.
This should fix #218
=> addSchemaLevelResolveFunction resolves once per operation type

CHANGELOG.md, package.json, src/Interfaces.ts, src/autopublish.ts, src/mock.ts, src/schemaGenerator.ts, src/test/testMocking.ts, src/test/testSchemaGenerator.ts, tsconfig.json
=> move from typed-graphql to @types/graphql

src/schemaGenerator.ts, src/test/testSchemaGenerator.ts
hey @stubailo - i spend some hours traveling through my code and searching for an issue we found in our project after we started to export our typeDefs inside of objects that get combined with a function. The problem seems to be with the way the tools are checking how to include a 
Our objects are structured like this: 
```
import TypeB from './TypeB';
const TypeA = {
typeDefs: `
type TypeA {
name: String!
field: TypeB
}
`,
resolvers: {
TypeA: {
name: () => null,
field: () => null,
},
},
};
export default combineSchemaDependencies(TypeA, TypeB);
```
`typeDefs` can be a function returning an array or a string like you expect for the typeDefinitions passed into `makeExecutableSchema`.  As soon as i export my objects via my function there are no typeDefinitions in the result. The reason for …
=> use function reference instead of string for concatenateTypeDefs

CHANGELOG.md, package.json
To be merged before the next minor or major version bump so we don't have to worry about supporting features from ancient versions of graphql-js
=> Restrict version range of graphql-js peerDependency

src/schemaGenerator.ts
The property was "resolved" twice.
In case the property is provided by a getter or proxied the two calls are probably less performant then using the already referenced property.
TODO:
Concerning the todos:
Tests: I guess this is covered by the existing tests? If not, the function is private, how would we cope with that?
Do you need a changelog entry for this?
=> Prevents resolving a property twice in defaultResolverFn

CHANGELOG.md, src/Interfaces.ts, src/schemaGenerator.ts, src/test/testSchemaGenerator.ts
TODO:
The [webpack loader](https://github.com/apollographql/graphql-tag/blob/master/loader.js) and the [Meteor build plugin](https://github.com/Swydo/meteor-graphql) both return a schema AST when importing a `.graphql` file. It would be great to simply pass this to the `makeExecutableSchema` function without first having to print it.
This PR makes sure that no needless print and parsing is done when an AST is passed. If an Array is passed it will print every AST it finds so that it can be combined with passed schema strings.
See https://github.com/apollographql/graphql-tools/issues/273#issuecomment-289583038
_Example:_
```js
import schema from './data/schema.graphql'; // No need to print with 'graphql/language/printer'
import resolverMap from './data/resolvers';
import { …
```
=> Support schema AST as type definition

src/mock.ts, src/test/testMocking.ts
it didn't work for me by following
>http://dev.apollodata.com/tools/graphql-tools/mocking.html#Mocking-interfaces  
so I fixed the problem
=> bugifx:mock interface type

src/mock.ts, src/schemaGenerator.ts, src/test/testMocking.ts
A Date was falsely taken to be an object with keys causing issues when
resolvers returned Date instances.
=> Fixes issue #351

CHANGELOG.md, package.json, src/schemaGenerator.ts
There is no need to use full `lodash` library so it is replaced with `lodash.uniq` as it is the only function used from `lodash`.
Tests are passing, but `tslint` is failing for me (it was failing before the changes too). Since I'm not using ts, I have no idea how to fix this.
```console
// tslint 5.5.0
ERROR: src/mock.ts[145, 29]: Shadowed name: 'mockType'
ERROR: src/schemaGenerator.ts[203, 13]: Shadowed name: 'attachConnectorsToContext'
```
Fixes https://github.com/apollographql/graphql-tools/issues/343
=> Replace lodash with lodash.uniq

src/schemaGenerator.ts
Use of defaultFieldResolver of graphql-js package instead own one.
Should fix #368 as soon as this PR is merged: https://github.com/graphql/graphql-js/pull/980
=> Use defaultFieldResolver from graphql-js package instead of own one

src/Interfaces.ts
This fixes issue #372. It seems like the 'subscribe' property was simply missing from the interface definition.
I've tested this by `yarn link`ing the change against another project where I was running into the issue and verified I no longer hit the issue with this diff. 
`npm run test` and `npm run lint` both pass locally.
=> Add 'subscribe' property to IResolverOptions

src/stitching/mergeSchemas.ts, src/test/testGraftSchemas.ts, src/test/tests.ts
The intention here is to allow an existing schema to remain unchanged / unprefixed, yet still accept a merge ("graft") from a new remote schema.  This is accomplished by _not_ passing in a "prefix" to `mergeSchemas` for the schema that should remain unchanged.  This PR only allows for a single unprefixed "ROOT SCHEMA", but we should consider a new pattern for identifying / referring to schemas that is not coupled to prefixing.
TODO:
=> Add support for grafting / unprefixed root schema

src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts
If the local resolvers contain a `GraphQLScalarType`, the check for `field.fragment` will cause an error with `cannot read property fragment of undefined`, since it's iterating over the object `GraphQLScalarType` properties. Not sure if there'd be other types where this could be an issue.
Another interesting observation when writing the test case, if I added:
```
scalar TestScalar
type TestingScalar {
value: TestScalar
}
```
without the root query, and add that to the list of merged schemas it's silently ignored by the try/catch [`here`](https://github.com/apollographql/graphql-tools/blob/a76cfae4fa17bb8d723fc2f70ad821a9cccd1e2f/src/stitching/mergeSchemas.ts#L106-L108) since the schema doesn't have a `Query` and therefore isn't valid on its own. Since it didn't have any extensions, it …
=> [schema-stitching]: Skip iterating fields on GraphQLScalarType

src/stitching/mergeSchemas.ts
I was running into an issue where `__typename` was being stripped out in `filterSelectionSet ` on delegated requests. Also I believe this should automatically add `__typename` on all interface/requests to execute. Still needs tests, but the existing suite is passing.
Prior to this change I was getting `Did not fetch typename for object, unable to resolve interface.` when it was definitely there in the request/parsed documentAST passed through to the `mergeInfo.resolve`
=> [schema-stitching]: __typename fixes

.npmignore, CHANGELOG.md, package.json, src/Interfaces.ts, src/index.ts, src/isEmptyObject.ts, src/schemaGenerator.ts, src/stitching/TypeRegistry.ts, src/stitching/index.ts, src/stitching/introspectSchema.ts, src/stitching/makeRemoteExecutableSchema.ts, src/stitching/mergeSchemas.ts, src/stitching/resolveFromParentTypename.ts, src/test/testMergeSchemas.ts, src/test/testingSchemas.ts, src/test/tests.ts, tsconfig.json
This is a WIP take on schema-stiching and schema merging. This will be published to a pre-release tag. See `src/test/testingSchemas.js` for examples..
<h3 id="makeRemoteExecutableSchema" title="makeRemoteExecutableSchema">
makeRemoteExecutableSchema({ schema: GraphQLSchema, fetcher: Fetcher }): GraphQLSchema
</h3>
Given a GraphQL schema (can be a non-executable client schema made by `buildClientSchema`) and a [Fetcher](#Fetcher), produce a GraphQL Schema that routes all requests to the fetcher.
<h3 id="introspectSchema" title="introspectSchema">
introspectSchema(
fetcher: Fetcher,
context?: {[key: string]: any}
): Promise&lt;GraphQLSchema&gt;</h3>
Use fetcher to build a client schema using introspection query. For easy of use of `makeRemoteExecutableSchema`. Provides a *client* schema, so …
=> [Do not merge] 2.0 with schema stitching

CHANGELOG.md, package.json, src/stitching/introspectSchema.ts, src/stitching/makeRemoteExecutableSchema.ts, src/test/testingSchemas.ts
This PR adjusts the fetcher portion of graphql-tools to accept a link or a fetcher. The idea is we would deprecate (potentially) using a fetcher in favor of a link stack since it makes it easier to do more complex actions and long term would make things like stitched `defer`, `live`, and more possible.
Docs link: https://github.com/apollographql/tools-docs/pull/135
=> added native support for using apollo-link as the network layer

src/mock.ts, src/stitching/introspectSchema.ts, src/stitching/makeRemoteExecutableSchema.ts, src/test/testMocking.ts, src/test/testResolution.ts, src/test/testSchemaGenerator.ts, src/test/testingSchemas.ts
Due to the fact that context differs between how apollo-links work and how context is used within graphql resolvers. This introduces a new API called `LinkContextCreator` which takes the context from the resolver and returns a context object for the apollo-links.
=> add in linkContext creator api

CHANGELOG.md, src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts
=> Fix alias problems by unaliasing queries we are sending to sub schemas

CHANGELOG.md, src/stitching/aliasAwareResolver.ts, src/stitching/makeRemoteExecutableSchema.ts, src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts, src/test/testingSchemas.ts
Pass through queries with aliases, but make fields be aware of their
aliases.
TODO:
=> Handle aliases in all fields in merged and remote schemas

CHANGELOG.md, src/stitching/typeFromAST.ts, src/test/testMergeSchemas.ts
As mentioned in #437, `mergeSchemas()` doesn't add the type descriptions from the typeDefs it merges into the resulting schema. This PR updates `typeFromAST()` to add the description.
One potential future enhancement is to also add parsing of the deprecation reason.
(The keeping of the Query type's description that I requested in #437 is not done here, this is just a fix for new type/field/arg descriptions.)
/cc @freiksenet
=> Parse type/field/arg descriptions in typeFromAST

src/stitching/introspectSchema.ts
https://github.com/apollographql/graphql-tools/issues/455
---
Do not throw when `introspectSchema` receives a response with an empty `errors` array.
=> Do not throw on empty errors array in introspectSchema

CHANGELOG.md, src/stitching/mergeSchemas.ts
Per the documentation and runtime behavior. See #461 
TODO:
=> `resolvers` parameter should be optional for `mergeSchemas`

src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts
I was having some issues using union types. I create a test to simulate my conditions.
```javascript
it('unions with alias', async () => {
const mergedResult = await graphql(
mergedSchema,
`
query {
customerById(id: "c1") {
... on Person {
name
}
v1: vehicle {
... on Bike {
bikeType
}
}
v2: vehicle {
... on Bike {
bikeType
}
}
}
}
`,
);
expect(mergedResult).to.deep.equal({
data: {
customerById: {
name: 'Exampler Customer',
v1: { bikeType: 'MOUNTAIN' },
v2: { bikeType: 'MOUNTAIN' },
},
},
});
});
```
This test doesn't pass but is a valid query.
I looked at the code and I found in **/src/stitching/mergeSchemas.ts** that the method `filterSelectionSet`  is doing this when it find a set of fields of a type:
L612
```javascript
if (
parentType instanceof GraphQLInterfaceType ||
parentType …
```
=> Fix alias of union types

CHANGELOG.md, src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts, src/test/testingSchemas.ts
These make sense in local schemas, as they have access to a complete raw
data object, however the proxied schema only gets the data that was
requested in the client’s GraphQL query which may well not include the
properties that the guard checks for.
cc @freiksenet 
----
=> [mergeSchemas] Remove `isTypeOf` from proxied schemas.

CHANGELOG.md, src/stitching/TypeRegistry.ts, src/stitching/defaultMergedResolver.ts, src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts, src/test/testingSchemas.ts
#420 - FourTwenty :)
Added support for subscription type (subscriptions will work with local schema only).
TODO:
=> Basic subscriptions support added to mergeSchemas and TypeRegistry.

README.md
I've noticed that all links to the docs are broken, so I've fixed it.
=> Fix links to doc in README

CHANGELOG.md, README.md, src/Interfaces.ts, src/schemaGenerator.ts, src/test/testSchemaGenerator.ts
**Description**: This PR allows implementing custom directives that can be used for translation, authentication and error tracking.
**API**:
```typescript
const directiveResolvers = {
// directive resolvers implement
},
const schema = makeExecutableSchema({
// ...
directiveResolvers,
});
```
**Example**:
- Using `@upper` directive to upper string from resolver:
```graphql
directive @upper on FIELD
type RootQuery {
hello: String @upper
}
schema {
query: RootQuery
}
```
Implement of `@upper` directive.
```typescript
const directiveResolvers = {
upper(
next: NextResolver,
src: any,
args: { [argName: string]: any },
context: any,
) {
return next().then((str) => {
if (typeof(str) === 'string') {
return str.toUpperCase();
}
return str;
});
},
}
```
- Using `@auth` directive check roles before …
=> Bring attachDirectiveResolvers to graphql-tools

docs/source/resolvers.md
As suggested by @stubailo on #307
=> Added "Companion tools" section to the docs.

.travis.yml, package.json, src/declarations.d.ts, src/schemaGenerator.ts, src/stitching/defaultMergedResolver.ts, src/stitching/errors.ts, src/stitching/mergeSchemas.ts, src/stitching/typeFromAST.ts, src/test/testMergeSchemas.ts
`graphql` 0.12 has some major breaking changes that make some features work differently.
Breaking changes to address:
After this PR, we should do a major release if it's no longer compatible with 0.11.
TODO:
=> Update to work with graphql 0.12

docs/source/remote-schemas.md
Looks like the docs keep moving around 😛  might be a good idea to come up with a way to gather all links across documentation repos that might break with certain restructurings
=> Fix link to Apollo Link docs

.vscode/settings.json, CHANGELOG.md, package.json, src/stitching/linkToFetcher.ts, src/stitching/makeRemoteExecutableSchema.ts, src/test/testMakeRemoteExecutableSchema.ts, src/test/testingSchemas.ts, src/test/tests.ts
=> Add subscriptions support to `makeRemoteExectuableSchema`

package.json
This PR aims to fix #472. It reverts the change made in #445 that apollo-link was made as a development dependency instead of a direct dependency. As a result, it causes a complain in typescript. According to the [guideline](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies), it should be listed as a direct dependency.
TODO:
=> fix: correct the dependency issue in typescript caused by #445

README.md, docs/source/generate-schema.md, docs/source/resolvers.md, docs/source/scalars.md, src/test/testMergeSchemas.ts, src/test/testSchemaGenerator.ts
This PR resolves #544. 
I'm new here, hence there could be lot of improvements. Kindly let me know through your review comments and I would be happy to fix and learn.
Thanks
Vimal
=> #544 - Update docs and tests to reflect new strings-as-descriptions pattern in new GraphQL SDL

CHANGELOG.md, src/stitching/schemaRecreation.ts
`mergeSchemas` does not set `astNode` properties, when recreating types.
But `CacheControlExtension.willResolveField` uses the `astNode` property in order to get the `cacheControl` directives.
TODO:
=> Include astNode in schema recreation

CHANGELOG.md, src/Interfaces.ts, src/test/testMergeSchemas.ts, src/test/testSchemaGenerator.ts
Pretty self-explanatory, tests included.
=> Allow IEnumResolver values to be number type

CHANGELOG.md, src/stitching/delegateToSchema.ts, src/test/testMergeSchemas.ts, src/test/testingSchemas.ts
@freiksenet: I had to pin graphql-tools to 2.7.1 because since the changes in https://github.com/apollographql/graphql-tools/pull/470, I have an issue with inline fragments on types that implement multiple interfaces.
TODO:
=> Fix fragment filtering edge case when a type implements multiple interfaces

package.json
The same module, `graphql-subscriptions` is specified in both `dependencies` and `devDependencies`.
On some versions of npm (we've seen it in 4.6.1) this can cause `npm prune --production` to erroneously remove the `graphql-subscriptions` module, causing a crash on startup when a server uses `makeExecutableSchema`.
Specifying `graphql-subscriptions` as a direct dependency of the project consuming `graphql-tools` is usable as a workaround.
=> Remove graphql-subscriptions from devDependencies

CHANGELOG.md, package.json, src/stitching/delegateToSchema.ts, src/test/testMergeSchemas.ts
=> Fix resolvers to accept and move forward args with zero or false values

CHANGELOG.md, src/stitching/schemaRecreation.ts
In a [previous commit](https://github.com/apollographql/graphql-tools/commit/fd9f6260faa779b2bfc12f1f707cdf2b778d306b) we added the `astNode` property in the `reacreateCompositeType` function. That resulted in cache control working with schema stitching but only for GraphQL Types. By recreating the `astNode` prop also in `fieldToFieldConfig` cache control also works for fields. This is required for caching fields and hence queries.
See also #505.
TODO:
=> Also recreate astNode for fields

CHANGELOG.md, package.json, src/stitching/makeRemoteExecutableSchema.ts, src/stitching/observableToAsyncIterable.ts, src/test/testMakeRemoteExecutableSchema.ts
The underlying subscription in a remote schema was not terminated properly, causing memory leaks. In
addition, multiple subscriptions caused duplicate payloads. Both are fixed by removing the PubSub
dependency and directly transforming the Observer returned by the ApolloLink to an async iterable.
This allows the async iterable to propagate to the underlying observable to cancel the subscription
once the subscription is not needed anymore.
Fixing https://github.com/graphcool/graphql-yoga/issues/101
=> fix(subscriptions): The subscription resolvers were firing too often

CHANGELOG.md, src/stitching/delegateToSchema.ts, src/test/testMergeSchemas.ts
This PR provided a fix for issue #602 where duplicate variables were being generated when delegating to a schema with multiple fragments referencing a linked field. 
Added minor change to remove duplicates from the `newVariableDefinitions` created in `delegateToSchema.ts`. All exiting tests pass, and the new tests create do demonstrate the issue now pass as well. 
TODO:
=> Deduping of new variable definitions when delegating to schemas

CHANGELOG.md, src/Interfaces.ts, src/stitching/mergeSchemas.ts, src/stitching/schemaRecreation.ts, src/test/testMergeSchemas.ts
Thank you to @orta and @renatobenks for help on this.
TODO:
=> Recreate enums and scalars in mergeSchema

docs/source/mocking.md
Same as https://github.com/apollographql/tools-docs/pull/141 which apparently never landed in but is still an issue 🐱 
> Currently the typeResolvers aren't used at all in the example, while they should be passed to makeExecutableSchema as seen in https://github.com/apollographql/graphql-tools/blob/5c5418cec88f1d5520eccc1d2e6dfaa511547e4d/src/schemaGenerator.ts#L99
=> fix: pass typeResolvers in mocking.md

CHANGELOG.md, src/stitching/errors.ts
Fix `error.path` could be `undefined` for schema stitching
TODO:
=> fix(stitching): error.path could be undefined

CHANGELOG.md, src/stitching/errors.ts
This is needed in order to handle custom properties on the GraphQLError object, like `code` or
`requestId`.
The problem is surfacing here: https://github.com/graphql-binding/graphql-binding/issues/45
=> fix(schema-stitching): Pass through error when coming from apollo-link-http

CHANGELOG.md, package.json
Fixes #625
Iterall is used in runtime code (e.g. https://github.com/apollographql/graphql-tools/blob/2868fe26266623dcb4a906c6450ccedbd10d62dc/src/stitching/observableToAsyncIterable.ts) but isn't a dependency. That means unless you happen to have it installed for some other reason, graphql-tools is unusable right now.
=> Make iterall a runtime dependency

docs/source/generate-schema.md
As it can be seen [in the code](https://github.com/apollographql/graphql-tools/blob/master/src/schemaGenerator.ts#L116), the `resolvers` option has a default value so it's not required argument.
=> [docs] makeExecutableSchema does not require resolvers

package.json
This brings in [`zen-observable-ts`](http://npmjs.org/package/zen-observable-ts), a TypeScript wrapper around the [`zen-observable`](http://npmjs.org/package/zen-observable) npm package, implemented by @evans: https://github.com/apollographql/apollo-link/pull/515
=> Update apollo-link to latest version.

CHANGELOG.md, src/stitching/errors.ts, src/test/testErrors.ts, src/test/tests.ts
This is to complete and address the PR previously opened here: https://github.com/apollographql/graphql-tools/pull/485
This is to address the issue logged here: https://github.com/apollographql/graphql-tools/issues/480
Currently, if schema stitching is used, any local errors will be swallowed and "recreated", thereby losing the original stack trace and making it very hard to debug. Along the same lines as what @alexFaunt proposed, we will now attach the original errors to the error object.
TODO:
=> Maintain original errors where possible

docs/source/schema-directives.md
Fixed a simple mistake in the docs on directives
```
attachDirectiveResolvers(
schema,
directiveResolvers,
});
```
Should be 
```
attachDirectiveResolvers(
schema,
directiveResolvers,
);
```
=> Remove extra bracket from docs

designs/connectors.md
Fix a typo in connectors documentation. I believe the author meant that a MySQL connector should be called from a model rather than from resolvers.
=> Fix typo in connectors.md

src/stitching/errors.ts, src/test/testErrors.ts
Added falsy check for the `error.path` value in `getErrorsFromParent`. If the path is undefined, the function will return the error with `kind: OWN` for the given field.
=> Handle undefined path in `getErrorsFromParent`

CHANGELOG.md, src/Interfaces.ts, src/index.ts, src/schemaGenerator.ts
- This is a small change
- No new logic
This PR adds generic typings to several interfaces related to resolvers, adds an optional `TContext` type parameter to `makeExecutableSchema`, and exports the interfaces file (so that the generic-ified types can be used to give a type signature to objects manually, especially for uses of `TSource`).
=> Improved generic typings for makeExecutableSchema

src/stitching/introspectSchema.ts, src/stitching/linkToFetcher.ts, src/stitching/makeRemoteExecutableSchema.ts, src/test/testingSchemas.ts
This PR removes an unnecessary print/parse pair that is used for making remote schema fetches 😄 
Let me know if you want me to do anything different. 
TODO:
=> Remove unnecessary print and subsequent parse

CHANGELOG.md, src/test/testDirectives.ts
=> fix timezone bug in test for @date directive

docs/source/generate-schema.md
* Use object shorthand for `id` in example
* Remove unnecessary parens in examples
* Add newlines in examples for better readability
* Update `makeExecutableSchema` API description
=> Update Generating a Schema docs

CHANGELOG.md, src/schemaGenerator.ts, src/test/testMergeSchemas.ts
TODO:
Allows `mergeSchemas` to recognize `extend interface` as a valid definition to pass to graphql's `extendSchema` as logged in #699.
=> Allow the use of extend interface when merging schemas

docs/package.json, renovate.json
As determined in https://github.com/renovateapp/config-help/issues/23#issuecomment-377202632,
it seems that it's not possible to have this sort of inherited
configuration.  It's possible that when I first introduced this behavior
that this behavior was on its way out (and the breaking change in Renovate
v11 on its way in).
Luckily, Renovate's shared configuration option still allows this to be
relatively painless and our `apollo-docs` shared configuration[0] does most
of the heavy lifting here.
[0] https://github.com/apollographql/renovate-config-apollo-docs
[1] https://github.com/meteor/hexo-theme-meteor
Closes #711.
=> Move Docs Renovate configuration into top-level `renovate.json`.

renovate.json
If we want to get this enabled on the rest of the `graphql-tools` dependencies, we'll just want to revert this commit, but we should be prepared for something that looks like this (which was what happened in https://github.com/apollographql/graphql-tools/pull/713 when I failed to consider that the changes in #712 would try to Renovate the whole repository:
=> Only run Renovate on `docs/package.json`.

src/test/testDirectives.ts
When running this test using `Australian Eastern Standard Time (AEST), @ 17:05` test would end up failing with the following error: 
`AssertionError: expected { today: 'March 16, 2018' } to deeply equal { today: 'March 15, 2018' }`
=> BUG - Fix failing tests when on a different timezone

CHANGELOG.md, docs/source/generate-schema.md, docs/source/resolvers.md, src/Interfaces.ts, src/schemaGenerator.ts, src/test/testSchemaGenerator.ts
This adds `inheritResolversFromInterfaces` to `addResolveFunctionsToSchema` and `makeExecutableSchema`
Later on we'll want to support interfaces implementing other interfaces
https://github.com/facebook/graphql/issues/295
TODO:
=> Add inheritResolversFromInterfaces option

docs/source/generate-schema.md
This statement is [quite old](https://github.com/apollographql/graphql-tools/commit/0614197255a4fb23d28acc9d3122cac80bc5f7e8) and, at least in my usage, is incorrect. I had to explicitly set these options to `true` before they had any effect.
/label docs
=> Correct outdated statement in generate-schema.md

src/stitching/mergeSchemas.ts
When using mergeSchema, we get this warning.
`The addResolveFunctionsToSchema function takes named options now; see IAddResolveFunctionsToSchemaOptions.`
=> Suppress warning when callling `mergeSchemas`

CHANGELOG.md, docs/source/remote-schemas.md, src/stitching/index.ts, src/stitching/makeRemoteExecutableSchema.ts
Allowing users to pass in this function will let users create custom fetching logic, including batching multiple queries into a single request. 
TODO:
=> Add ability to supply custom createRemoteResolver to mRES

src/test/testTransforms.ts, src/transforms/RenameTypes.ts
Related to #755 
The problem is the function `renameTypes`, Object.keys() with assignment of the key on the array, it's not a proper way for construct an array, leading to iteration problem later.
```javascript
var items = [{id: "1"},{id: "2"}];
var newItems = Object.create(Object.getPrototypeOf(items));
Object.keys(items).forEach((key) => {
newItems[key] = items[key];
});
console.log(newItems);
console.log('Length', newItems.length); 
// Result
Array { '0': { id: '1' }, '1': { id: '2' } }
Length 0
```
Maybe it's better to have two condition in `renameTypes`, one for object and one for array, i'm open to suggestion.
If the PR satisfied you, i'm would be really happy if we can merge it quickly, i'm really excited to used this new transform api 🙂
=> Fix transform with RenameTypes on list return, if type are renamed

CHANGELOG.md, src/transforms/FilterToSchema.ts
=> Fix duplicate fragment bug for v3

docs/source/generate-schema.md
The latest graphql-tools already has a merge function. Lodash merge is not needed now.
=> Remove lodash merge from docs

CHANGELOG.md, src/stitching/mergeSchemas.ts
Fixes a visitType error printing the name of the variable `typeName` rather than its value due to a template string being incorrectly formatted.
=> fix template string issue for visitType error

src/Interfaces.ts, src/stitching/delegateToSchema.ts
TODO:
Hey @stubailo @abernix, this adds a `skipValidation` flag to `delegateToSchema`, which prevents `validate` from being run which can be costly. Especially when delegating internally within a request, we typically don't need to validate again. 
I will add a test for this option, but I wanted to hear your thoughts first.
=> Add option to skip validation in delegateToSchema

docs/source/resolvers.md
This updates all blog URLs in the documentation to use blog.apollographql.com
as the domain, rather than dev-blog.apollodata.com.
=> docs: Update blog URLs to reference blog.apollographql.com.

docs/source/schema-stitching.md
In addition to the field's name, the transform function is also given the type of operation as the first argument.
None of the below TODO items seem application to documentation updates, so just leaving them there.
TODO:
=> Fix example usage of RenameRootFields transform

CHANGELOG.md, package.json
If you're using TypeScript, this ties the type definition for apollo-link to be specifically the version at 1.2.1 and if you have a less vague option in app-code then the two can not match (which is awesome, and totally the point) 
I assume that the tie to an exact version was likely a oversight, so this lets resolver potentially not just be one version.
=> Update apollo-link to be a greater than, rather than a specific version

docs/source/scalars.md
Hi, just a fix in the doc. 
The parameter in query is `borderColor` and not `favoriteColor`. (or did I miss something? :/)
Thanks for you work!
Matt'
=> Fix wrong parameter in enum example.

src/generate/addResolveFunctionsToSchema.ts, src/test/testSchemaGenerator.ts
Essentially, I expected enums to behave in the same way as other fields when providing `allowResolverNotInSchema`. Plausible use cases for this would be the same as for any other extra resolver: planned but not yet actual implementation, a spread that includes extra fields, directives and other mechanisms for manipulating the schema after it is built, and I'm sure other reasons I haven't thought of.
It's possible this is an intentional difference having to do with enum fields themselves and being more protective of the name lookups, but I think this change makes the behavior more predictable.
Test cases document the new functionality.
=> Extended allowResolverNotInSchema to apply to enums as it does to other types

CHANGELOG.md, docs/source/schema-transforms.md, src/test/testTransforms.ts, src/transforms/WrapQuery.ts
=> Fixes issue #901: WrapQuery - add support for query wrapper to return selection set node.

src/schemaGenerator.ts
This small change was suggested by @evans on https://github.com/apollographql/apollo-server/issues/1075#issuecomment-393230841
Hopefully, this should help removing confusion for less experimented GraphQL users.
Do you think we should update [the error message](https://github.com/apollographql/graphql-tools/blob/master/src/schemaGenerator.ts#L532) as well?
=> Rename `resolveType` to `__resolveType` in missing interface type resolver warning

CHANGELOG.md, src/Interfaces.ts
I believe that the `IResolvers` type is incorrect as  according to the resolvers documentation it should provide support for the example under [Unions and interfaces](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Unions-and-interfaces).
```ts
const resolverMap = {
Vehicle: {
__resolveType: (obj, context, info) => "Object",
},
};
```
In addition, whilst not mentioned in the documentation, I believe the below should also be allowed, so I added the possibility of `IResolverObject` having itself as a property:
```ts
const resolverMap = {
Query: {
Vehicle: {
resolve: () => true,
__resolveType: (obj, context, info) => "Object",
},
},
};
```
I also added the source & context generics whilst doing this.
=> Fix IResolvers type

CHANGELOG.md, src/schemaVisitor.ts
Returning null from a visitor will remove the type from the schema; however, the visitor methods were all typed without allowing `null`.
=> Add null to return type of directive visitors

CHANGELOG.md, src/stitching/schemaRecreation.ts, src/test/testMergeSchemas.ts
`mergeSchemas` doesn't transpose enum description, this PR in a first time adds a failing test
=> mergeSchema keeps ENUM description and deprecation

src/test/testMergeSchemas.ts
TODO:
Hi.
We ran into some behaviour changes after updating to v3 of `graphql-tools`, where our custom resolvers were not being provided with the data that their fragments requested.
It seems that this is due to the loop within `ReplaceFieldWithFragment`'s constructor, which overwrites `this.mapping[typeName]` on each iteration, seemingly by trying to index into an array with the type name (which I presume never succeeds?) or with an empty object.
This clears out any existing fragments, leaving just the information for the "last" field for any type.
=> Test that multiple fields can be added to a single type when stitching

src/test/testFragmentsAreNotDuplicated.ts, src/test/tests.ts
If a fragment is splatted multiple times into the same query body, it breaks after being run through `transformSchema`. The request works in base GraphQL and in v2 of this library, but not since attempting to upgrade to v3. If no schema transformation is used, the request processes correctly.
E.g. this query throws the error `There can be only one fragment named "PostOwner"`. 
```
query getPostById($id: ID!) {
post(id: $id) {
...Post
owner {
...PostOwner
email
}
}
}
fragment Post on Post {
id
title
owner {
...PostOwner
}
}
fragment PostOwner on User {
id
}
```
`PostOwner` is defined in the `Post` fragment, but we also want to override the `owner` field to fetch more data (the `email` as well as the `id`). Removing the `...PostOwner` in the main query works around this issue.
The reason …
=> Fragments in transformed schemas throw duplication errors

CHANGELOG.md, docs/source/schema-stitching.md, src/stitching/mergeSchemas.ts, src/test/testAlternateMergeSchemas.ts
This simply adds support for `inheritResolversFromInterfaces` via `mergeSchemas` (a simple passthrough thanks to the wonderful work done in pull request #720).
I didn't open an issue first since it was a pretty small change and I was looking for a quick way to achieve my goal, but I did link issue #616 below since this is just extending the concept to an additional util.
Let me know if this isn't in line with the original intent of that issue and/or the vision of the project, but I think it will prove to be a useful option.
TODO:
=> Add inheritResolversFromInterfaces option - mergeSchemas

CHANGELOG.md, src/test/testTransforms.ts, src/transforms/ReplaceFieldWithFragment.ts
TODO:
This is the implementation of #894 issue.
=> Multiple fragments support

CHANGELOG.md, src/Interfaces.ts, src/stitching/delegateToSchema.ts, src/stitching/mergeSchemas.ts, src/test/testDelegateToSchema.ts, src/test/testingSchemas.ts, src/test/tests.ts
See issue #876 
TODO:
/label bug
/label has-reproduction
/label schema-stitching
=> Fixes issue #876, mirror delegateToSchema behavior for standalone

CHANGELOG.md, docs/source/mocking.md, package.json, src/Interfaces.ts, src/mock.ts, src/test/testMocking.ts
Adds `casual` for mocking, and fixes the `TODO` for adding a seed random array length. 
I wanted to get initial feedback before updating docs. Should I add `seed` to `mockServer` as well? 
**TODO**:
cc: @benjamn
=> Use casual for mocking

src/stitching/mergeSchemas.ts, src/stitching/typeFromAST.ts
Just working on simplifying some code.
TODO:
=> Small non-breaking refactors

docs/source/remote-schemas.md
Looks like the docs incorrectly referenced the Authorization as "Authentication".  This updates the docs.
=> Change from Authentication to Authorization header

CHANGELOG.md, src/stitching/mergeSchemas.ts
> "Error: Could not find subschema with field `{operation}.{fieldName}`"
Hi there 👋, I just came across this error message while trying to debug some remote schema stitching issue. I guess a changelog entry and extra test coverage is not needed for this one or what do you think?
=> Fix template strings usage in guessSchemaByRootField error message

CHANGELOG.md, docs/source/remote-schemas.md
As mentioned in https://github.com/apollographql/graphql-tools/issues/891, the docs for a custom fetcher are off since a couple of months.
After https://github.com/apollographql/graphql-tools/commit/c91e5779feb3b09de2dc1efb1c5c6a82993b534c landed, the types were changed to accept a `DocumentNode` instead of a `string`.
TODO:
=> Adjust Fetcher interface in docs

CHANGELOG.md, src/Interfaces.ts
Related to https://github.com/apollographql/graphql-tools/issues/704
This change allows me to specify a type for the `args` object of a resolver. Without this change I cannot specify types for the `args` object of a resolver. As an example
```typescript
const resolvers = {
Query: {
hello: (_parent: object, args: { id: string }) => `Hello ${args.id}!`,
},
};
```
☝️ Does not compile.
```
[ts]
Argument of type '{ typeDefs: DocumentNode; resolvers: { Query: { hello: (_parent: object, args: { id: string; }) => string; }; }; }' is not assignable to parameter of type 'Config'.
Types of property 'resolvers' are incompatible.
Type '{ Query: { hello: (_parent: object, args: { id: string; }) => string; }; }' is not assignable to type 'IResolvers<any, any>'.
Property 'Query' is incompatible with …
```
=> Update field resolver interface to allow typed args

CHANGELOG.md, src/stitching/delegateToSchema.ts
Object spreading causes nothing to be returned when using subscriptions, removing object spreading allows subscriptions to successfully pass their resolutions.
=> Remove Object Spreading for Transformed Subscription Results

CHANGELOG.md, src/stitching/errors.ts, src/test/testErrors.ts
I was working with Apollo Server 2.0 and I couldn't get my `AuthenticationError` code of `'UNAUTHENTICATED'` to get passed back to the user. https://www.apollographql.com/docs/apollo-server/v2/features/errors.html#Codes
I pin-pointed to here in `graphql-tools` and it looks like it was originally setup to use `result`, but not `extensions`?
Anyway, I copied the test for `result` and added the logic to make it work for `extensions`.
TODO:
=> Pass and Check for Error Extensions

.travis.yml, .vscode/settings.json, CHANGELOG.md, package.json, src/generate/addResolveFunctionsToSchema.ts, src/makeExecutableSchema.ts, src/mock.ts, src/schemaVisitor.ts, src/stitching/delegateToSchema.ts, src/stitching/errors.ts, src/stitching/mergeSchemas.ts, src/stitching/schemaRecreation.ts, src/stitching/typeFromAST.ts, src/test/testDirectives.ts, src/test/testErrors.ts, src/test/testMergeSchemas.ts, src/test/testSchemaGenerator.ts, src/test/testTransforms.ts, src/test/testingSchemas.ts, src/transforms/ConvertEnumValues.ts, src/transforms/transformSchema.ts, tsconfig.json
This PR updates the `graphql-tools` `peerDependencies` to allow `graphql` 14.x, and enforces `graphql` 14.x in its `devDependencies`. All changes have been made in a way that is backwards compatible with `graphql` 0.13.x, but anyone looking to upgrade to `graphql` 14.x should keep in mind that [`graphql` 14.x introduced several breaking changes](https://github.com/graphql/graphql-js/releases/tag/v14.0.0). Because of this we're likely going to major version bump `graphql-tools` for the next release.
Most of the changes in this PR are pretty straightforward, with one main exception. The current version of `graphql-tools` is relying on `graphql` 0.13 functionality to achieve [internal enum value support](https://www.apollographql.com/docs/graphql-tools/scalars.html#internal-values). …
=> Update to `graphql-js` 14.x

CHANGELOG.md, src/generate/addResolveFunctionsToSchema.ts, src/test/testSchemaGenerator.ts
Fixes enum internal value mapping regression shown in #962, I believe this is also the issue with https://github.com/apollographql/apollo-server/issues/1721, includes tests.
Basically it should be:
```js
enumValueMap[type.name] = enumValueMap[type.name] || {};
enumValueMap[type.name][fieldName] = resolverValue[fieldName];
```
not
```js
enumValueMap[type.name] = {
[fieldName]: resolverValue[fieldName],
};
```
Unrelated, it'd be nice to get a `.prettierrc` and/or prettier setup as a precommit hook so it runs with the project's preferred settings.
TODO:
=> Fix #962, Enum internal value mapping

CHANGELOG.md, src/stitching/delegateToSchema.ts, src/test/testMergeSchemas.ts, src/test/testSchemaGenerator.ts, src/transforms/ConvertEnumResponse.ts, src/transforms/ConvertEnumValues.ts
Fixes the inverse of https://github.com/apollographql/graphql-tools/pull/973, values on input should be mapped to their internal values. This was broken because of the changes [noted here](https://github.com/apollographql/graphql-tools/blob/6c0f4294d8449dc26bbe832feb5c4ce4df35cec0/src/transforms/ConvertEnumValues.ts#L57-L79). I took what this was trying to achieve and moved it into a separate transform specific to merged schema delegation. Tests included.
TODO:
=> Fix regression in enum input -> internal value conversion

CHANGELOG.md, package.json
Updated the package.json `repository` field to reflect the current location of the repo (github.com/apollographql/graphql-tools). Making the fix because some of my tooling doesn't follow GitHub's redirects from `apollostack` -> `apollographql` :)
TODO:
=> Update package.json `repository` field

docs/source/schema-delegation.md
No `user` subfield were queried in the example, so the query was invalid.
=> Fix invalid query in schema delegation example

CHANGELOG.md, docs/source/schema-stitching.md, src/stitching/mergeSchemas.ts, src/test/testMergeSchemas.ts
Many APIs across graphql-tools and apollo libraries support passing
a parsed graphql ast or a graphql string. For example, makeExecutableSchema.
This PR updates the mergeSchemas API to support passing a parsed graphql ast.
=> Add support for passing parsed schema ast to mergeSchemas

CHANGELOG.md, src/generate/extractExtensionDefinitions.ts, src/test/testExtensionExtraction.ts
TODO:
Similarly to  #948, this makes `extractExtensionDefinitions` understand the new `union` and `enum` type extensions
Please note that this PR does not make the `enum` and `union` schema extensions "just work" with
`makeExecutableSchema` and others, because these -- same as the `input` type extension added in #948 -- actually need graphql-js v14. But at least these definitions are not skipped and we get a good descriptive message what's wrong:
```
Error: The UnionTypeExtension kind is not yet supported by extendSchema().
```
=> Extract the new enum and union type extensions supported by graphql-js

CHANGELOG.md, src/stitching/schemaRecreation.ts, src/test/testSchemaGenerator.ts
Fixes a regression where custom scalars were incorrectly replaced while recreating schema with `visitSchema`. `visitSchema` is used internally to replace the enums when the internal enum value mapping is used. However, because of a missing check for `keepResolvers`, all user-defined scalars are actually being replaced with a passthrough scalar:
```ts
return new GraphQLScalarType({
name: type.name,
description: type.description,
astNode: type.astNode,
serialize(value: any) {
return value;
},
parseValue(value: any) {
return value;
},
parseLiteral(ast: ValueNode) {
return parseLiteral(ast);
},
});
```
This means any user-defined formatting is broken/removed. Test included.
TODO:
=> Fix regression where custom scalars are incorrectly replaced

CHANGELOG.md, src/test/testTransforms.ts, src/transforms/WrapQuery.ts
Before the fix provided, the new testcase would get stuck in an infinite loop. The use of `unshift` was not correct.
Fixes #1007
=> Avoid infinite loop when using WrapQuery on second level fields

CHANGELOG.md, docs/source/mocking.md
TODO:
For reference, the mockServer function signature: https://github.com/apollographql/graphql-tools/blob/b85137ba81c9bdc5667bced9cad9b1d226ea83fc/src/mock.ts#L34-L38
I recently set up graphql mocking for the test environment in one of our apps, and it took me way longer than I care to admit to figure out that the single doc describing how to use `mockServer` was incorrect (should have looked at the source code a lot earlier in retrospect). This change fixes the example and adds a little more info to help prevent people from going down the wrong path.
All that being said, in the future I think I would prefer to see the `mockServer` function take an object of named parameters like many of the other related functions (notably `makeExecutableSchema` and `addMockFunctionsToSchema` which are …
=> Fix mockServer example

CHANGELOG.md, src/stitching/typeFromAST.ts, src/test/testMergeSchemas.ts
We were not including the deprecation reason inside of the type construction of merge schema. This PR fixes and tests the issue. Ran into this while working on the gateway github schema checks. 🎉 🐶 🥘 
TODO:
=> Include deprecations from string SDL in mergeSchemas

CHANGELOG.md, src/stitching/schemaRecreation.ts, src/test/testMergeSchemas.ts, src/test/testSchemaGenerator.ts
the `buildSchema` and `parse` from the `graphql` package, as well as 'src/stitching/typeFromAST.ts` both create `GraphQLNamedTypes` for built in scalar fields when creating `GraphQLSchema`s.
This causes an issue when we try to merge the schemas, because mergeSchemas tries to find definitions for those named types when merging the schemas.
Simple reproduction:
```graphql
import { mergeSchemas } from 'graphql-tools';
const BookSchema = `
type Book {
name: String
}
`;
mergeSchemas({ schemas: [BookSchema] });
```
TODO:
=> Handle cases where Scalars appear as NamedTypes when recreating schemas

docs/source/index.md
This branch de-duplicates the `example` heading id on the docs index page
=> Update githunt heading id

docs/package.json
This branch removes the `--prefix-paths` option from `gatsby develop` called by our NPM start script in the docs.
=> Don't --prefix-paths in development

src/stitching/makeRemoteExecutableSchema.ts, src/test/testMakeRemoteExecutableSchema.ts
=> Allow user-provided buildSchema options

CHANGELOG.md, src/stitching/introspectSchema.ts
`introspectionQuery` is being removed in v15 of graphql-js.
=> Use getIntrospectionQuery instead of deprecated introspectionQuery constant

CHANGELOG.md, src/generate/buildSchemaFromTypeDefinitions.ts, src/generate/filterExtensionDefinitions.ts, src/stitching/makeRemoteExecutableSchema.ts, src/stitching/observableToAsyncIterable.ts
Some minimal compatibility changes (see commits for additional clarity) to
prepare for `graphql@15`, which is currently in release candidate stages.
I should note that this PR doesn't attempt to get close to the more
comprehensive set of changes which @yaacovCR's
https://github.com/apollographql/graphql-tools/pull/1206 brings.
Instead, I'm aiming to provide the minimum compatibility with the least number of breaking changes
in order to continue to support Apollo Server v2, which completely re-exports
the current `graphql-tools@4` version.
Future versions of Apollo Server will lessen their reliance on this
`graphql-tools` package and will also deprecate older versions of `graphql`
which are still supported by it today (including 0.13.x versions).  In the
meantime, I hope this will allow …
=> compat: minimal changes to support graphql@15 within Apollo Server

src/utils/SchemaDirectiveVisitor.ts
=> Generics for Arguments and Context in SchemaDirectiveVisitor

src/delegate/results/handleObject.ts, src/utils/SchemaDirectiveVisitor.ts, src/utils/collectFields.ts, src/utils/getArgumentValues.ts, src/utils/inspect.ts, src/utils/keyMap.ts
It may cause issues on bundlers.
=> Avoid using internal api of graphql-js

src/generate/extendResolversFromInterfaces.ts, src/polyfills/toConfig.ts, src/stitch/typeFromAST.ts, src/utils/clone.ts, src/utils/heal.ts, src/utils/map.ts, src/utils/stub.ts
- use v15 interface types for interfaces, as v15 types allow interfaces to have interfaces without casting to objects
- this change also streamlines types for stub type creation
=> refactor(types): use graphql v15 types

src/delegate/createRequest.ts, src/generate/addResolversToSchema.ts, src/stitch/index.ts, src/stitch/mergeInfo.ts, src/test/alternateMergeSchemas.test.ts, src/test/transforms.test.ts, src/utils/index.ts, src/wrap/transforms/AddArgumentsAsVariables.ts, src/wrap/transforms/HoistField.ts, src/wrap/transforms/ReplaceFieldWithFragment.ts, src/wrap/transforms/WrapFields.ts
graphql-tools-fork exported almost all utilities. graphql-tools should have a smaller (and more stable) api surface.
=> fix(exports): trim exports

src/Interfaces.ts, src/wrap/index.ts, src/wrap/makeRemoteExecutableSchema.ts, src/wrap/resolvers.ts, src/wrap/wrapSchema.ts
= add support for custom subscription resolver generation to makeRemoteExecutableSchema
= adds support for customizing resolver generation to schema config objects and thereby to wrapSchema/transformSchema, mergeSchemas
= closes #1302
=> feat(proxying): support custom resolver generation

src/Interfaces.ts, src/wrap/index.ts, src/wrap/makeRemoteExecutableSchema.ts, src/wrap/resolvers.ts
finishes work in #1349 for #1302
= streamlines the CreateProxyingResolverFn signature as no further arguments expected, pass along all info to users for possible customization
= adds fix for nested root query object to makeRemoteExecutableSchema
= actually export defaultCreateProxyingResolver
= reorders properties of SubschemaConfig, removes some unused properties
=> refactor(createProxyingResolver): finish new functionality

docs/source/schema-directives.md
Several of SchemaDirectiveVisitor's methods have arguments that don't appear to be in any documentation ([source](https://github.com/apollographql/graphql-tools/blob/c8d6e55cb6a23af412d3bc650bd79d5cf94c4317/src/schemaVisitor.ts#L90)). The same issue also applies to the signatures given in VS Code's Intellisense, but I'm not familiar enough to find the appropriate place to fix that.
Cheers.
=> [docs] Add undocumented method arguments

docs/source/mocking.md
I am afraid this example code could mislead because the `makeExecutableSchema` function doesn't have a parameter named `typeResolvers` according to [the API](https://www.apollographql.com/docs/graphql-tools/generate-schema/#makeexecutableschemaoptions).
I think this variable should be renamed to `resolvers` so that the code works as intended.
=> Rename `typeResolvers` to `resolvers`

docs/source/schema-delegation.md
_If the sound of the first letter is like Y then we use a, like a user, because u in user is like y. Otherwise, we use an, like an apple, an orange... ... For example, the word "user" is pronounced "yoozer" (the initial "y" sound acts as a consonant) so it must be preceded by an "a," not an "an."_ - https://www.quora.com/Is-it-an-user-or-a-user
https://www.quickanddirtytips.com/education/grammar/a-versus-an
=> "a userId" vs. "an userId"

src/Interfaces.ts, src/delegate/delegateToSchema.ts, src/wrap/makeRemoteExecutableSchema.ts
= refactor makeRemoteExecutableSchema default resolvers to use delegateToSchema
= return promise where required in createSubscriber
= remove unused internal Delegator type
=> fix(makeRemoteExecutableSchema): stop sending entire document

src/stitch/introspectSchema.ts
Using instanceOf causes problems is a project includes multiple versions of ApolloLink.
=> fix(introspectSchema): avoid instanceOf check

src/Interfaces.ts, src/delegate/results/handleObject.ts, src/stitch/mergeInfo.ts, src/test/fixtures/schemas.ts, src/utils/collectFields.ts, src/utils/fields.ts, src/wrap/transforms/RenameRootTypes.ts, src/wrap/transforms/RenameTypes.ts, src/wrap/transforms/TransformQuery.ts, src/wrap/transforms/WrapQuery.ts
= do not rely on external, non-exported graphql-js types
= provide backwards compatible ExecutionResult type that retains typecast from graphql-js <v15
= add extensions property from Result type to graphql-tools ExecutionResult type
= use ExecutionResult type instead of Result
= retain Result type for backwards-compatibility
=> fix(types): standardize types

src/Interfaces.ts, src/wrap/transforms/ExpandAbstractTypes.ts, src/wrap/transforms/ExtendSchema.ts, src/wrap/transforms/FilterRootFields.ts, src/wrap/transforms/MapFields.ts, src/wrap/transforms/RenameTypes.ts, src/wrap/transforms/TransformCompositeFields.ts, src/wrap/transforms/TransformRootFields.ts
= public types should be exported for ease of use
= private types do not require aliases
=> refactor(types): export transform argument types

.gitignore, .travis.yml, package.json, src/test/testSchemaGenerator.ts, src/test/testingSchemas.ts
=> Support GraphQL v15

package.json, src/delegate/results/handleNull.ts, src/delegate/results/handleObject.ts, src/stitch/errors.ts, src/stitch/proxiedResult.ts, src/test/alternateMergeSchemas.test.ts, src/test/errors.test.ts, src/test/fixtures/schemas.ts, src/test/mergeSchemas.test.ts, src/test/transforms.test.ts, src/wrap/transforms/TransformQuery.ts
= combineErrors now returns the originalError if one is present.
= relocating an error is not necessary prior to throwing, and may cause the original error to be lost.
= The CombinedError class now inherits from GraphQLError rather than directly from error to utilize its methods of properly allow extending the base Error class.
Hopefully fixes: #1367.
=> fix(errors): do not wrap errors unnecessarily

src/utils/transformInputValue.ts
Simple JS maps as objects with null prototype are a graphql-js/graphql-tools implementation detail and should not be exposed to users.
Hopefully fixes #1374.
=> fix(delegation): do not expose maps

.travis.yml, docs/source/schema-delegation.md, docs/source/schema-stitching.md, package.json, src/Interfaces.ts, src/esUtils/toObjMap.ts, src/mock/index.ts, src/stitch/introspectSchema.ts, src/stitch/mergeInfo.ts, src/test/delegateToSchema.test.ts, src/test/directives.test.ts, src/test/fixtures/schemas.ts, src/test/mocking.test.ts, src/test/schemaGenerator.test.ts, src/utils/SchemaDirectiveVisitor.ts, src/utils/SchemaVisitor.ts, src/utils/fragments.ts, src/wrap/transforms/AddArgumentsAsVariables.ts, src/wrap/transforms/RenameRootTypes.ts
= Use Record instead of { [key: string]: <whatever> } when possible.
= Use any for SchemaDirectiveVisitor generic default, a simpler attempt at #1376
= Add typescript check, as rollup seems to fail only on semantic/syntax errors, not type errors
=> fix(types): use Records when appropriate

src/generate/SchemaError.ts
I am running graphql under the chakracore JS runtime that does not implement
Error.captureStackTrace.
Note that the facebook graphql library also checks for the presence of Error.captureStackTrace:
https://github.com/graphql/graphql-js/blob/f0ae3f4c0ba469c8f2147f8d12c9e670313b865c/src/error/GraphQLError.js#L201
Please consider wrapping this call in a check to prevent runtime errors in this error handling code.
TODO:
=> Wrap captureStackTrace in check

src/Interfaces.ts, src/delegate/checkResultAndHandleErrors.ts, src/delegate/delegateToSchema.ts, src/delegate/results/handleList.ts, src/delegate/results/handleObject.ts, src/stitch/defaultMergedResolver.ts, src/stitch/mergeFields.ts, src/stitch/mergeInfo.ts, src/stitch/proxiedResult.ts, src/test/dataloader.test.ts, src/test/errors.test.ts, src/wrap/transforms/CheckResultAndHandleErrors.ts
use declaration merging to add optional properties to GraphQLResolveInfo rather than rely on new interface.
Retain IGraphQLToolsResolveInfo interface for backwards compatibility.
=> refactor(types): use declaration merging

src/Interfaces.ts, src/delegate/delegateToSchema.ts, src/stitch/linkToFetcher.ts
info argument may have additional functionality added to it via extensions that custom fetchers or links defined on subschemas may wish to use, such as dynamic cacheControl hints, see #1380
=> feat(delegate): pass info to fetcher/link

src/stitch/typeFromAST.ts, src/test/alternateMergeSchemas.test.ts
mergeSchemas dummy types should handle entire SDL surface prior to better prepare for rewiring with actual types
closes #1399
=> fix(mergeSchemas): handle entire SDL surface

src/polyfills/toConfig.ts, src/stitch/mergeSchemas.ts, src/test/utils.test.ts, src/utils/fields.ts, src/utils/filterSchema.ts, src/wrap/transforms/RenameTypes.ts, src/wrap/transforms/TransformCompositeFields.ts
It should also narrow return type when argument passed is a union of possible types.
=> fix(toConfig): should properly map types to individual configs

packages/load/tests/loaders/documents/documents-from-glob.spec.ts
yarn test returns successfully even on windows, but jest plugin within vscode errors with posix path separator.
=> Fix tests on windows

packages/schema/src/attachDirectiveResolvers.ts, packages/schema/src/makeExecutableSchema.ts, packages/schema/src/types.ts, packages/stitch/src/stitchSchemas.ts, packages/utils/src/Interfaces.ts, packages/utils/src/get-directives.ts, packages/utils/src/mapSchema.ts, packages/utils/tests/schemaTransforms.test.ts, website/docs/directive-resolvers.md, website/docs/generate-schema.md, website/docs/legacy-schema-directives.md, website/docs/schema-delegation.md, website/docs/schema-directives.md, website/docs/schema-wrapping.md, website/sidebars.js
new implementation of directive-based schema transformation
closes #1234
=> Schema transforms

packages/utils/src/fields.ts, packages/wrap/src/transforms/WrapFields.ts, packages/wrap/tests/gatsbyTransforms.test.ts
it was selecting, not helping!
it turns out that removing all object fields leads to automatic type pruning -- this could be optionally disabled, but easier for users to just add a selectObjectFields helper and a modifyObjectFields helper that can remove and add fields in a single step
=> fix removeObjectFields helper

packages/delegate/src/createRequest.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/types.ts, packages/delegate/tests/createRequest.test.ts, packages/delegate/tests/delegateToSchema.test..ts, packages/stitch/tests/fragments.test.ts
delegateRequest should work without passing info argument to delegateRequest.
details about the request to be delegated (operation, fieldName, returnType) should be calculated from the request (if not provided).
=> Fix bare request delegation

packages/delegate/src/createRequest.ts, packages/delegate/src/results/handleObject.ts, packages/delegate/src/results/handleResult.ts, packages/delegate/tests/createRequest.test.ts
handle object fields
handle some errors
=> further improve bare delegation

packages/delegate/src/proxiedResult.ts, packages/delegate/src/results/handleList.ts, packages/delegate/src/results/handleNull.ts, packages/delegate/src/results/handleResult.ts
this function after prior refactoring was recursively passing along arugments without actually ever using them
=> simplify handleNull

packages/loaders/url/tests/url-loader.spec.ts, packages/utils/src/print-schema-with-directives.ts
fixSchemaAst fixes the schema ast by adding a getter for the property which lazily calls buildSchema(printSchemaWithDirectives(schema) to rebuild the schema.
printSchemaWithDirectives, however, now checks to see if schema.astNode is defined, and so will end up calling itself. This can be avoided by making sure that the astNode is not defined as a getter.
fixSchemaAst could alternatively be changed to return a new schema ratehr than modifying the original schema.
=> avoid infinite loop

packages/utils/src/SchemaDirectiveVisitor.ts, packages/utils/src/get-directives.ts
in --some-- codebase locations!
closes #1486
=> guard against undefined directives

packages/utils/src/mapSchema.ts, packages/utils/src/reannotateObject.ts, packages/utils/src/rewire.ts, packages/utils/tests/mapSchema.test.ts
within the graphql ecosystem, many users still annotate schemas, types, and
possibly directives with custom properties instead of using the
newer extensions property.
mapSchema should copy all custom properties when creating graphql
objects as possible.
=> support regenerating schema, type and directive object annotations

website/docs/merge-typedefs.md
Just missing a equal sign in the example. Just committed a small fix to the docs.
=> merge-typedefs doc example is missing a equal sign

packages/utils/src/print-schema-with-directives.ts
Related https://github.com/Urigo/graphql-mesh/issues/424#issuecomment-632738140
=> Fix issue in printSchemaWithDirectives

packages/load-files/src/index.ts, packages/load-files/tests/file-scanner.spec.ts
`loadFiles` fails to load file with non-directory `minimatch` patterns. It's using async function `isDirectory` for pattern checking but not waiting for it to finish, hence the result of the ternary is always `exprIfTrue`.
This PR adds `await`.
=> fix: loadFiles path resolving issue

packages/wrap/src/transforms/ExtendSchema.ts
helpful to explain why result of MapFields transformSchema function is not saved
=> add comment to ExtendSchema

packages/wrap/src/transforms/MapFields.ts
MapFields (really should be MapFieldNodes, this should be changed in next major release) provides a quick way to modify field nodes for object types by specification of a map of type/field names as opposed to a function.
this backwards-compatible change allows MapFields to work for interfaces and root types.
=> allow MapFields to transform all field nodes

packages/loaders/apollo-engine/src/index.ts
Generally, users are not going to provide a custom endpoint for fetching from the Apollo Engine, so make it optional and add a sensible default value.
TODO:
=> Add default Apollo Engine endpoint

website/docs/schema-directives.md
Old `schemaDirectives` is mentioned in the docs while example already has `schemaTransforms`.
=> Replace schemaDirectives argument in docs

packages/delegate/src/delegateToSchema.ts, packages/wrap/src/generateProxyingResolvers.ts
If a subschema has the subscription resolvers like below;
```js
{
Subscription: {
foo: {
subscribe: () => someAsyncIteratorReturnsNumber, // not an object with fieldName like { foo: 2 }
resolve: payload => payload, // << this function gets an object { foo: 2 } if the schema is wrapped, so GraphQL Request fails because returned value here should be a string.
}
}
}
```
So this PR adds additional `resolve` field to proxy resolvers. It resolves `payload[fieldName]` by overwriting subschema's `resolve` method.
=> Fix: resolve correct data if schema is wrapped

CHANGELOG.md, packages/wrap/src/index.ts
As mentioned in #1568, this PR adds `createProxyingResolver` to the public API to quickly create a ResolverMap without having to create a schema.
(While I'm here, thank you a ton to @yaacovCR for all the hard work that must've gone into moving this library from v4 to v5.)
=> Feature: Add `generateProxyingResolvers` to public API for v6.0.0

CHANGELOG.md, packages/stitch/src/stitchSchemas.ts, packages/stitch/tests/stitchSchemas.test.ts
If an empty array is passed, the GraphQL parser fails, because the
source is empty. Switch the typeDef check to check for length as well,
since an empty array is truthy.
TODO:
=> Fix stitchSchemas for when empty array of typeDefs are passed

website/docs/loaders.md
1. UrlFileLoader => UrlLoader
https://www.graphql-tools.com/docs/schema-loading/ uses `UrlLoader`, the code is called UrlLoader
https://github.com/ardatan/graphql-tools/blob/bd17df5795fec065fca9b502a862dc4f20862829/packages/loaders/url/src/index.ts#L29-L42
This fixes the typos.
2. the url ref to remote-schemas is broken, I have updated it commit no 2.
=> docs(loaders): UrlFileLoader => UrlLoader + fix url ref to remote-schemas

website/docs/migration-from-import.md
Hello there,
After reading the [migration from import](https://www.graphql-tools.com/docs/migration-from-import/`) page of the documentation, I noticed the file loader import used in the example wasn't correct, so I took the liberty of changing:
`code-file-loader` => `graphql-file-loader` 
Since in the example, we want to load a graphql file.
Let me know if I missed anything
Thank you so much for your work 🙏🏼
=> Docs (migration-from-import): code-file-loader => graphql-file-loader

packages/delegate/src/Transformer.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/delegationBindings.ts, packages/delegate/src/index.ts, packages/delegate/src/types.ts, packages/utils/src/Interfaces.ts
= provide binding option to delegateToSchema
A Binding is a function that takes a delegationContext (just the relevant subset of options passed to delegateSchema) and produces the set of transforms used to actually delegate (i.e. that "binds" the fieldNodes from the sourceSchema to that of the targetSchema), this provides library users ability to completely customize delegation behavior, even on a per field level. These delegation transforms are the specified schema transforms, but also the additional delegation transforms that reduce friction between the source and target schemas, see below.
= export defaultBinding that enables:
(a) setting arguments after schema transformation = AddArgumentsAsVariables
(b) conversion of original result into object annotated with errors for easy return …
=> refactor application of transforms

packages/utils/src/Interfaces.ts, packages/wrap/src/transforms/FilterInputObjectFields.ts, packages/wrap/src/transforms/RenameInputObjectFields.ts, packages/wrap/src/transforms/TransformInputFields.ts, packages/wrap/src/transforms/TransformInputObjectFields.ts, packages/wrap/src/transforms/index.ts, packages/wrap/src/types.ts, packages/wrap/tests/transforms.test.ts
This PR represents an initial attempt at transforming input fields to address #1058 
It does enable filtering and renaming input fields, which can then be included as dedicated transforms.
But it doesn't enable (yet?) adding default values for filtered fields, because the specified input field node transformer only transforms existing field nodes, it does not provide a hook for adding new ones.
(It does let you return multiple input field nodes instead of one, which could be helpful, but only for expanding a known required field node into a required and optional, and this is not really helpful for the general case).
An option would be to allow an additional generic inputObjectTransformer function to be specified that could modify the entire object as desired vs creating a …
=> introduce input object field transformers: Filter/Rename/TransformInputObjectFields

packages/wrap/src/transforms/FilterInputObjectFields.ts, packages/wrap/src/transforms/RenameInputObjectFields.ts, packages/wrap/src/transforms/TransformInputObjectFields.ts, packages/wrap/src/types.ts
Addresses typing issues in #1605
=> temporarily make delegationContext optional until next major version

package.json, packages/delegate/src/proxiedResult.ts, yarn.lock
if sources.length > 0, errors will be in the form [[]], making it non empty, while the source result set is empty. Any code path that checks errors length for result errors will erroneously detect errors.
eg: in handleNull: https://github.com/ardatan/graphql-tools/blob/master/packages/delegate/src/results/handleNull.ts#L6
=> Fix mergeProxiedResults errors aggregation

package.json, packages/schema/src/addResolversToSchema.ts, packages/schema/tests/schemaGenerator.test.ts, yarn.lock
first attempt at fix for #1587
requires some thinking as to whether this is a breaking change.
requires some new tests?
=> addResolversToSchema should not lose directives

packages/delegate/src/mergeFields.ts, packages/stitch/tests/typeMerging.test.ts
Just creating a PR with an updated test to trigger issue
=> Merged types should allow query of `__typename` field without crashing query

packages/delegate/src/transforms/AddArgumentsAsVariables.ts, packages/wrap/src/transforms/ExtractField.ts, packages/wrap/src/transforms/RenameRootTypes.ts, packages/wrap/src/transforms/RenameTypes.ts, packages/wrap/src/transforms/TransformQuery.ts, packages/wrap/src/transforms/WrapQuery.ts
so as not to lose extensions, for example
motivation: https://github.com/gatsbyjs/gatsby/issues/23552#issuecomment-641928334
=> transforms should always pass along unmodified parts of originalRequest

packages/schema/src/makeExecutableSchema.ts, packages/schema/src/types.ts, packages/stitch/src/stitchSchemas.ts, packages/utils/src/heal.ts, packages/utils/src/index.ts, packages/utils/src/prune.ts, packages/utils/src/rewire.ts, packages/wrap/src/transforms/PruneSchema.ts, packages/wrap/src/transforms/index.ts
Some of these options won't work, as there is a minimal level of pruning built into v6 healSchema and mapSchemas. This default pruning should probably be removed in v7, as we cannot necessarily make assumptions as to who wants what pruned.
Motivation: #1624
=> introduce pruneSchema function, PruneSchema transform, and pruneSchema options for makeExecutableSchema and stitchSchemas

packages/stitch/src/typeCandidates.ts, packages/stitch/tests/alternateStitchSchemas.test.ts
_**NOTE** I've no idea if that fix is sufficient or if support of input object is otherwise supported_
Without the proposed fix in `typeCandidates.ts` the added test case triggers the following error from expected unreachable code:
```
FAIL  packages/stitch/tests/alternateStitchSchemas.test.ts (11.775 s)
● mergeTypes › can merge types
Type ObjectInput has unknown GraphQL type.
351 |   } else {
352 |     // not reachable.
> 353 |     throw new Error(`Type ${typeName} has unknown GraphQL type.`);
|           ^
354 |   }
355 | }
356 |
at merge (packages/stitch/src/typeCandidates.ts:353:11)
at packages/stitch/src/typeCandidates.ts:222:27
at Array.forEach (<anonymous>)
at Object.buildTypeMap (packages/stitch/src/typeCandidates.ts:212:31)
at Object.stitchSchemas …
```
=> fix(stitchSchemas): subschemas with object inputs and mergeTypes  as true causes crash

packages/stitch/package.json, packages/stitch/src/mergeCandidates.ts, packages/stitch/src/typeCandidates.ts
= merge astNodes, extensions, etc, when available.
= with conflicts, merge last type candidate, to allow overriding on
gateway
= add scalar merging
=> improve type merging

packages/stitch/tests/typeMerging.test.ts
Found a tricky one. I spent several hours trying to figure out exactly what going on, It looks like transparent querying of list / object bites us hard.
Long story short, the fallback [resolve of merge config](https://github.com/nicolas-cherel/graphql-tools/blame/5b7711c657e53338071387f86731e8f2a3e54b86/packages/stitch/src/stitchingInfo.ts#L104-L104) doesn't handle difference between list or non list of queried items. So it goes on quering with provided query field that will just query a single object, while `info.returnType` is a list of object.
So `handleResult()`, reading the `returnType` will call [`handleList()`](https://github.com/nicolas-cherel/graphql-tools/blame/5b7711c657e53338071387f86731e8f2a3e54b86/packages/delegate/src/results/handleResult.ts#L37-L37) while result is an …
=> fix(typeMerging): can't return a list of merged types

packages/stitch/src/stitchingInfo.ts, packages/stitch/tests/typeMerging.test.ts
This possibly should be added as an argument to the resolver for
performance reasons.
In general, the next version of type merging will require a lot of
refactoring to improve performance.
=> fix by getting underlying type prior to delegation

packages/delegate/package.json, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/results/handleNull.ts, packages/utils/package.json, packages/utils/src/errors.ts, packages/utils/src/validate-documents.ts, packages/utils/tests/validate-documents.spec.ts, packages/wrap/package.json, packages/wrap/src/introspect.ts, yarn.lock
Related https://github.com/dotansimha/graphql-code-generator/issues/4227
=> Use aggregate-error to keep the content of errors

packages/delegate/src/mergeFields.ts, packages/delegate/src/results/handleObject.ts, packages/stitch/tests/typeMerging.test.ts
=> fix combination of type merging and gateway type extensions

packages/stitch/src/stitchSchemas.ts, packages/stitch/src/typeCandidates.ts, packages/utils/src/rewire.ts
Fixes #1656.
Later directives with the same name should override earlier directives rather than causing an error.
Directives with the same names from a later subschema will override an earlier subschema. Directives from typedefs will override both.
Mixing of legacy schemas argument and newer subschemas, typeDefs, and types arguments should respect this same order.
We can consider adding onDirectiveConflict option to match onTypeConflict for customization.
=> fix(stitching): avoid duplicate directives

packages/delegate/src/proxiedResult.ts, packages/stitch/tests/typeMerging.test.ts
*_NOTE_*: once again, I've doubts to this being the right fix. maybe errors on query toplevel fields should throw errors instead of merely go through merging, the thing is, yet again, I'm not familiar enough with underlying principles to figure out the right call. But somehow, this fix solves the issue at the right place — on processing subschema results.
If the toplevel query of delegation has failed and reports an error on toplevel, with null as result,
`handleNull()` returns the errors has result, then `mergeProxiedResults()`, concats an error array consisting of `[undefined]`, the errors props not being set on exception (in a previous fix on mergeProxiedResults, it was assumed that sources where always execution results).
I suspect that the real problem is the `handleNull` with …
=> fix(proxiedResults): handle top level errors when using type merging

packages/merge/src/typedefs-mergers/directives.ts, packages/merge/tests/merge-typedefs.spec.ts
The GraphQL reference implementation treats directives  as optional,
so mergeDirectives needs to handle the `undefined` case, since some
libraries will set `directives` to be undefined instead of an empty list.
see https://github.com/graphql/graphql-js/blob/20a8f555e7eaa5c2fa2fd188abcef83ee8169e7f/src/language/ast.d.ts#L453
TODO:
=> fix(merge): add default value for `mergeDirectives`

packages/delegate/src/Subschema.ts, packages/delegate/src/createRequest.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/types.ts
alternative to #1651 
allows specification of operation name when delegating without a default. no need to allow a function as discussed there, as caller will always have access to the existing operation name under the info argument.
you can use the subschema createProxyingResolver option to enable setting the operation for delegation to a subschema when wrapping or stitching subschemas.
you can also just set the operation name in a transform (now that the second argument of a transformRequest function is the delegationContext)
you can also set the operation name within the executor function, now that info argument is passed there.
=> Name operations

packages/loaders/url/src/index.ts
Related https://github.com/Urigo/graphql-mesh/issues/633
=> Use DocumentNode instead of GraphQLResolveInfo to decide the HTTP method for useGETForQueries

packages/stitch/tests/alternateStitchSchemas.test.ts, packages/wrap/src/generateProxyingResolvers.ts, website/docs/remote-schemas.md
the blocker for this was that the default createProxyingResolverFn was changed to no longer hardcode the operation, but to rather infer it from the root type being stitched from.
This was in parallel to a similar change with the target fieldName which was helpful when making the RenameRootField transformer just a special case of the RenameObjectField transformer, but messes up the wrapping of mutations, because when the root fields in the wrapping subschema are the ones that actually do the proxying, and wrapping them with another type causes them to default to the query operation.
So, the default createProxyingResolverFn now hardcodes the operation, and all is well.
Addresses #1708
=> allow mutation type wrapping

packages/delegate/src/delegateToSchema.ts, packages/delegate/src/transforms/CheckResultAndHandleErrors.ts, packages/mock/src/types.ts, packages/schema/tests/resolution.test.ts, packages/schema/tests/schemaGenerator.test.ts, packages/stitch/tests/alternateStitchSchemas.test.ts, packages/stitch/tests/stitchSchemas.test.ts, packages/stitch/tests/typeMerging.example.test.ts, packages/utils/tests/directives.test.ts, packages/utils/tests/schemaTransforms.test.ts, packages/wrap/tests/fragmentsAreNotDuplicated.test.ts
to be from internal polyfill
this can probably be changed back to import from graphql after support for versions < 15.2 is dropped
See:
https://github.com/graphql/graphql-js/releases/tag/v15.2.0
https://github.com/graphql/graphql-js/pull/2644
=> standardize ExecutionResult

packages/utils/src/Interfaces.ts, packages/utils/src/index.ts, packages/utils/src/visitResult.ts, packages/utils/tests/visitResult.test.ts, packages/wrap/src/transforms/ExtendSchema.ts, packages/wrap/src/transforms/HoistField.ts, packages/wrap/src/transforms/MapFields.ts, packages/wrap/src/transforms/RenameTypes.ts, packages/wrap/src/transforms/TransformCompositeFields.ts, packages/wrap/src/transforms/TransformInterfaceFields.ts, packages/wrap/src/transforms/TransformObjectFields.ts, packages/wrap/src/transforms/TransformRootFields.ts, packages/wrap/src/transforms/WrapFields.ts, packages/wrap/src/transforms/WrapType.ts, packages/wrap/src/types.ts
When transforming a delegating schema (i.e. utilizing the transformSchema method within transforms passed to wrapSchema), one technique for result transformation is to defer the work until field resolution time, i.e. by wrapping the resolve method for the appropriate field within the delegating schema.
This approach saves a round of result tree traversal., but, unfortunately, causes several issues:
= return type inconsistencies that affect using these fields for stitching (see: #1725, https://github.com/yaacovCR/graphql-tools-fork/issues/35)
= type merging issues when fields are wrapped only in some subschemas
WrapType, WrapFields, HoistField, ExtendSchema transformers have been converted to utilize their transformResult methods to visit the result. 
This PR embraces that result visiting …
=> Introduce result visiting

website/docs/merge-resolvers.md, website/docs/merge-typedefs.md
After moving to graphql-tools v6, the extensions specified when using `loadFilesSync` now do not require the `.` e.g. `.graphql` --> `graphql`.
TODO:
=> Update loadFilesSync docs for specifying extensions

packages/delegate/src/delegationBindings.ts, packages/delegate/src/transforms/AddSelectionSets.ts, packages/delegate/src/transforms/VisitSelectionSets.ts, packages/delegate/src/transforms/index.ts, packages/stitch/tests/alternateStitchSchemas.test.ts
Visitors visiting the proxying ast cannot rely on the operation being valid according to the source schema in all cases.
But, the proxying document's root field nodes represent values with the expected return type, and so the document can be traversed according to the source schema from that point and below.
See #1725
=> fixes selectionSet hints with WrapFields transform

packages/stitch/tests/alternateStitchSchemas.test.ts, packages/utils/src/fields.ts, packages/utils/src/mapSchema.ts, packages/wrap/src/transforms/MapFields.ts, packages/wrap/src/transforms/RenameTypes.ts, packages/wrap/src/transforms/TransformCompositeFields.ts, packages/wrap/src/transforms/TransformInputObjectFields.ts
Each transform should also modify the underlying astnode and extensionASTNodes, if they exist.
This PR also changes mapSchema to automatically update a type's astNode list of field definitions to match the actual field definitions includes within the type's new config map after mapping.
There is likely space for making sure to update additional astNodes within types to match the enclosed graphql type system objects, for example, enum types with the enclosed enum values. That may be included in a separate PR at this time.
Addresses #1747
=> Modify ast nodes when transforming schemas

packages/delegate/src/delegationBindings.ts, packages/delegate/src/transforms/AddSelectionSets.ts, packages/delegate/src/types.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/types.ts
that take the specified gateway field as a parameter and produce a required selection set, allowing passing of arguments from the gateway field to the required target schema field.
See #1709
=> allow selectionSet hints for stitching to be functions

packages/utils/src/fields.ts, packages/utils/src/mapSchema.ts, packages/wrap/src/transforms/TransformCompositeFields.ts, packages/wrap/src/transforms/TransformInputObjectFields.ts
= TransformCompositeFields and TransformInputObjectFields can use mapSchema via MapperKind.COMPOSITE_FIELD and MapperKind.INPUT_OBJECT_FIELD.
= field utility functions can use rebuildAstNode and rebuildExtensionAstNodes from mapSchema
=> refactor to rely on mapSchema

packages/utils/src/index.ts, packages/utils/src/renameType.ts, packages/wrap/src/transforms/RenameRootTypes.ts, packages/wrap/src/transforms/RenameTypes.ts
from RenameTypes transform
= to remove duplicative functionality from RenameRootTypes
= also switch RenameRootTypes to use visitData just like RenameTypes
=> refactor out renameTypes function

packages/graphql-tag-pluck/src/index.ts, packages/load-files/src/index.ts, packages/load/src/documents.ts, packages/load/src/filter-document-kind.ts, packages/load/src/load-typedefs.ts, packages/load/src/schema.ts, packages/loaders/apollo-engine/src/index.ts, packages/loaders/code-file/src/exports.ts, packages/loaders/code-file/src/helpers.ts, packages/loaders/code-file/src/index.ts, packages/loaders/code-file/src/load-from-module.ts, packages/loaders/git/src/index.ts, packages/loaders/git/src/load-git.ts, packages/loaders/git/src/parse.ts, packages/loaders/github/src/index.ts, packages/loaders/graphql-file/src/index.ts, packages/loaders/json-file/src/index.ts, packages/loaders/module/src/index.ts, packages/loaders/prisma/src/index.ts, packages/loaders/url/src/index.ts, packages/merge/src/merge-resolvers.ts, packages/merge/src/merge-schemas.ts, packages/merge/src/typedefs-mergers/merge-typedefs.ts, packages/mock/src/mocking.ts, packages/mock/src/types.ts, packages/schema/src/makeExecutableSchema.ts, packages/schema/src/types.ts, packages/utils/src/Interfaces.ts, packages/utils/src/prune.ts
Partially addresses #1758. This is the initial batch of JSDoc comments to facilitate API documentation generation from source code. There's still a good chunk of code to go through, so subsequent PRs will need to follow. 
I updated parameter names in a few places for consistency and clarity. These are not breaking changes, but I'll add comments to point those out.
=> Annotate code base with JSDoc comments

packages/utils/src/Interfaces.ts, packages/wrap/src/transforms/WrapFields.ts, packages/wrap/src/transforms/WrapType.ts
=> fix public signatures for strict option

packages/utils/src/Interfaces.ts, packages/utils/src/fields.ts, packages/utils/src/mapSchema.ts, packages/wrap/src/transforms/MapLeafValues.ts, packages/wrap/src/transforms/TransformEnumValues.ts, packages/wrap/src/transforms/index.ts, packages/wrap/src/types.ts, packages/wrap/tests/transforms.test.ts
See #1634
This PR implements TransformEnumValues that allows conversion of individual enum values.
This PR does not yet rigorously support addition/deletion of values, just conversion.
Additional test cases are possibly required.
=> introduce TransformEnumValues

packages/loaders/git/package.json, packages/loaders/git/src/index.ts, packages/loaders/git/src/load-git.ts, packages/loaders/git/tests/loader.spec.ts, packages/loaders/git/tests/test-files/bad-extension.garphql, packages/loaders/git/tests/test-files/introspection.json, packages/loaders/git/tests/test-files/pluckable.ts, packages/loaders/git/tests/test-files/type-defs.graphql, packages/loaders/git/tests/test-files/type-defs.json
The existing GitLoader's `loadSync` function is broken because it uses `simple-git` and `simple-git` does not provide a way to execute git commands synchronously -- its API either uses Promises or callbacks. This PR refactors the loader to utilize `exec`/`execSync` instead and adds tests.
=> Refactor GitLoader

packages/stitch/tests/alternateStitchSchemas.test.ts, packages/wrap/src/transforms/TransformCompositeFields.ts
=> fix(transforms): preserve aliases

website/docs/documents-loading.md
Spent a few hours debugging why `loadDocuments` wasn't working as expected - there's a default of filtering NON_OPERATION_KINDS in the options that I missed :(
I had only read this page - telling the user "hey watch out, there's some defaults to be aware of!" and linking to them would be great.
Thanks! :)
Thanks!
TODO:
=> Add link to full API for loadDocuments

packages/loaders/graphql-file/src/index.ts, packages/loaders/graphql-file/tests/loader.spec.ts, packages/loaders/graphql-file/tests/test-files/executable.graphql, packages/loaders/graphql-file/tests/test-files/fragment.graphql, packages/loaders/graphql-file/tests/test-files/import-me.graphql, packages/loaders/graphql-file/tests/test-files/type-defs-with-import.graphql
Temporary fix for `GraphQLFileLoader` until we can revisit how `processImport` works
=> Fix GraphQLFileLoader #import syntax handling

packages/delegate/src/createRequest.ts
selectionSet option is used with bare execution, where fieldNodes is not present, without issue.
with type merging, info.fieldNodes and fieldNodes may be specified, but selectionSet should override, as there may be situation when both appear but selectionSet desired, unlikely for them both to appear but fieldNodes to be desired, as fieldNodes is auto generated, and selectionSet is more likely to be created manually.
TODO:
=> fix(createRequest): selectionSet overrides fieldNodes

packages/delegate/src/results/mergeFields.ts, packages/delegate/src/types.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/types.ts, packages/stitch/tests/alternateStitchSchemas.test.ts
Use case is a subschema in which the only defined fields are the key, so that merging is neither required nor really possible.
see #1839
=> feat(stitch): allow subschemas to not provide queries for merging

packages/batch-delegate/src/createBatchDelegateFn.ts
TODO:
I love the recent addition of the batch-delegate package! The only thing that prevents me from using it is the inability to edit the server's response before returning the results to the dataloader. I believe there is a general need for this feature (e.g. what if the array of entities is not in order, or what if the we want to group entities together by key for a one-to-many relation?), so I wrote a quick PR to make this available. Let me know what you think!
=> feat(batch-delegate): added mapping function to createBatchDelegateFn

packages/batch-delegate/src/batchDelegateToSchema.ts, packages/batch-delegate/src/createBatchDelegateFn.ts, packages/batch-delegate/src/getLoader.ts, packages/batch-delegate/src/index.ts, packages/batch-delegate/src/types.ts, packages/delegate/src/types.ts, packages/stitch/src/stitchingInfo.ts
= allow createBatchDelegateFn to take an options object that can prespecify any option if desired
= introduces batchDelegateToSchema in which all arguments including key and result mapping are deferred to runtime, in parallel to delegateToSchema
= updates schema stitching type merging to allow configuration of result mapping
=> refactor(batchDelegate): simplify batch delegation

packages/batch-delegate/src/batchDelegateToSchema.ts, packages/batch-delegate/tests/basic.example.test.ts
It's not uncommon for a model to posses an array of keys to be stitched from another service, for example:
```graphql
type Post {
networkIds: [ID!]!
}
```
In these cases, the array of keys are delegated through `DataLoader.loadMany` so that the results return an array of mapped models. This PR adds this behavior. While at it, I've added eager returns for skipping delegation entirely when a key or key set is empty.
TODO:
=> Make batch delegate send key arrays to loadMany

website/docs/merge-typedefs.md
Fixes #1864.
Remove the obsolete `{all: true}` example.
=> Update mergeTypeDefs docs

packages/utils/src/rewire.ts, packages/utils/tests/schemaTransforms.test.ts
that reference other types
see #1870
=> fix(mapSchema): mapping fields to new types

packages/mock/src/mocking.ts, packages/mock/tests/mocking.spec.ts
In my opinion it's a bug fix : mergeMocks function signature accept **any** type, so Promise type should be covered.
In our application, we use the mocks with Promise result.
That gives us the possibility to test the "pending" and "error" state of a query or a mutation more easily. (and also the optimistic UI part can also be covered during pending state)
Actually it's really working fine and it's way easier to use on Frontend side compare to other mock utilities (for example the "mock" request system of apollo is awful)
We discover that if we define a custom mock + use Promise the custom mock override the expected result.
It's because of this test:
```js
if (isObject(customMock)) {
return mergeObjects(genericMockFunction(), customMock);
}
```
Promise is an object, but you can merge it as …
=> feat(mergeMocks): support Promise

packages/loaders/url/src/index.ts, packages/loaders/url/tests/url-loader.spec.ts, packages/testing/utils.ts
Related https://github.com/Urigo/graphql-mesh/issues/737
=> fix(url-loader): pass variables correctly on HTTP GET

packages/load/src/load-typedefs/parse.ts, packages/loaders/graphql-file/src/index.ts, packages/schema/src/buildSchemaFromTypeDefinitions.ts, packages/utils/src/loaders.ts, packages/utils/src/parse-graphql-json.ts, packages/utils/src/parse-graphql-sdl.ts, packages/utils/tests/__snapshots__/parse-graphql-sdl.spec.ts.snap, packages/utils/tests/parse-graphql-sdl.spec.ts
The PR includes fixes for:
- Allow transforming old GraphQL comments into GraphQL descriptions (during `parse`), using the same `commentDescriptions` configuration flag (it's a workaround for https://github.com/graphql/graphql-js/issues/2241) 
- Use custom `parse` in all relevant pieces of code. 
- Ensure empty document isn't throwing errors during parsing.
=> Improved `parse` to support converting comments into descriptions

packages/stitch/src/mergeCandidates.ts, packages/stitch/tests/mergeInterfaces.test.ts
thanks go to @gmac for finding this bug and contributing test code
see: https://github.com/ardatan/graphql-tools/issues/1911#issuecomment-674875107
=> fix(typeMerging): fix interface merging

website/docs/stitch-type-merging.md
Adds stitching docs for cross-schema interface strategies. Promotes capabilities enabled by https://github.com/ardatan/graphql-tools/pull/1912 and https://github.com/ardatan/graphql-tools/pull/1917.
TODO:
=> enhance(website) stitching docs for cross-schema interfaces

packages/delegate/src/results/mergeFields.ts, packages/stitch/tests/fieldSelectionSets.test.ts
should work on their own when necessary
see: https://github.com/ardatan/graphql-tools/issues/1956
=> fix(typeMerging): field selection sets

packages/utils/src/get-fields-with-directives.ts, packages/utils/tests/get-fields-with-directives.spec.ts
[Closes](https://github.com/ardatan/graphql-tools/issues/1933)
Usage of `includeInputTypes` means no breaking changes
=> Support InputObjectTypeDefinition & InputObjectTypeExtension for getFieldsWithDirectives 

packages/delegate/package.json, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/getBatchingExecutor.ts, packages/delegate/src/memoize.ts, packages/delegate/src/mergeRequests.ts, packages/delegate/src/prefix.ts, packages/delegate/src/splitResult.ts, packages/delegate/src/types.ts, packages/delegate/tests/batchExecution.test.ts
WIP:
When `batch` is set to true for a given subschemaConfig, batches all delegated root fields into a combined request passed to the executor. Moreover, batches all requests to a given subschema into the minimum number of requests, collecting queries and mutations separately, preserving operation order. Distributes properly pathed errors to the originating requests.
Adapted from Gatsby query batcher by @vladar.
Caveats:
* Uses a Dataloader under the hood, which is created anew upon each request -- relies on a unique context argument per request to make this happen!
* Does not pass `info` argument to the batched executor call, disabling any executors that used extensions annotated onto info.
TODO:
- Add testing!
- Extensions support should be added by a custom option?
Related: …
=> enable batch execution

packages/stitch/src/mergeCandidates.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/src/types.ts, website/docs/stitch-type-merging.md
also includes refactoring of MergeTypeCandidate type to match docs.
=> fix(typeMerging): fix scalar type merging

packages/stitch/src/mergeCandidates.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/src/types.ts
add ability to customize how type descriptions and conflicting fields
are merged.
TODO:
=> enhance(typeMerging): add options

packages/delegate/src/delegateToSchema.ts, packages/delegate/src/getBatchingExecutor.ts, packages/delegate/src/types.ts, packages/delegate/tests/batchExecution.test.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/types.ts
allow query batching to work with different subschemas with same endpoint
see: https://github.com/ardatan/graphql-tools/issues/1959#issuecomment-685273899
=> enhance(stitching): improve query batching

packages/loaders/url/src/index.ts, packages/loaders/url/tests/url-loader.spec.ts
=> fix(url-loader): should preserve ws and http in the middle of a pointer

packages/delegate/src/Subschema.ts, packages/delegate/src/index.ts, packages/delegate/src/types.ts, packages/delegate/tests/batchExecution.test.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/types.ts
further simplified subschema config sets by simply using an array of SubschemaConfig objects
Named endpoints are no longer necessary, as common endpoints can simply be used by using identical (===) endpoint objects which will allow query batching across subschemas.
Technically, there is now no difference from including an array of SubschemaConfig objects within the `subschemas` property or simply spreading the arrray into the subschemas property, whatever is simpler for end-users.
=> enhance(stitch): simplify subschema sets

packages/loaders/git/src/load-git.ts
This is bug fix
My `graphql.schema.json` grown to 1.5KB, and my schema validation broke:
```
graphql-inspector diff git:origin/master:graphql.schema.json ./graphql.schema.json
```
The error I'm getting is:  `Error: Unable to load file from git: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded`
Fix is easy: increase buffer size to 1MB (default value was 1KB)
=> Increase maxBuffer to 1MB

packages/stitch/tests/mergeConflicts.test.ts
Adds tests for merge conflicts. These work well enough, although they're pretty opaque for an extremely common use case like picking the right docstring. It'd be nice if there was some way to provide a friendly facade for this type of setup along the lines of:
```js
combineDescriptions({ delimiter: '\n', ignorePrefix: 'ignore!' });
```
Obviously, we wouldn't want that to interfere with the ability to still take advantage of these merge handlers for other truly specialized use cases. Any ideas for how something like this could be cleanly packaged?
Either way, these tests hit merge handlers so provide worthwhile coverage!
TODO:
=> enhance(stitch) Test merge conflicts

packages/utils/src/prune.ts, packages/utils/tests/prune.test.ts
When pruning schema with recursive types, a `RangeError: Maximum call stack size exceeded` error would be thrown
=> Handle recursive input types when pruning schemas

README.md
> 3. Automatically stitch multiple schemas together into one larger API
Old link, shows 404: https://graphql-tools.com/docs/schema-stitching
Proposed correction: https://graphql-tools.com/docs/stitch-combining-schemas
Alternately, the copy could be changed slightly and the link could go to https://www.graphql-tools.com/docs/schema-delegation , which gives a more general-purpose overview of schema delegation options provided by `graphql-tools`.
(PS: speaking of https://www.graphql-tools.com/docs/schema-delegation , it links to https://www.graphql-tools.com/docs/stitch-api ("Schema stitching - merging multiple schemas into one"), but maybe https://www.graphql-tools.com/docs/stitch-combining-schemas would be better?
=> Fix bad stitching docs link in README

website/docs/merge-typedefs.md
https://www.graphql-tools.com/docs/merge-typedefs/
Current source code, from which types are generated doesn't mention `{ all: true }` as part of the config
=> Update `Type definitions (SDL) merging` docs

website/docs/stitch-type-merging.md
This performs another pass on computed fields documentation tailored to the final implementation that got merged in https://github.com/ardatan/graphql-tools/pull/1989. Also adds a few additional general notes:
- Computed field narrative now focuses exclusively on the core `@computed` behavior that assumes field dependencies are a hard requirement. The supposition of what _could_ happen if storefronts had a local cache of data is removed for now because it conflates what computed IS doing. This supposition of the local cache scenario would be more appropriate in a dedicated section that explores the `fields` feature–should that establish itself as a widespread use case.
- Mentions of "Federated" are switched to "Federation". Now that type merging is decided on the "computed" terminology, …
=> enhance(docs) Computed fields docs

packages/stitch/tests/alternateStitchSchemas.test.ts, packages/utils/src/Interfaces.ts, packages/utils/src/filterSchema.ts, packages/utils/tests/filterSchema.test.ts
This enhances the `utils/filterSchema` method to make it more general purpose and efficient. Right now the method is not quite granular enough to be useful for access control filtering. This updates the method as follows:
- Adds dedicated filters for object fields, interface fields, and input fields; while leaving one general purpose field filter option that will operate across all three.
- Adds argument filtering, which is extremely useful when performing access control on a schema for certain audiences.
- Makes all but the type filter optional. When a filter is omitted, the method skips churning through that set of work.
BREAKING – `filterSchema(fieldFilter)` option will now filter ALL fields across Object, Interface, and Input types. For the previous Object-only behavior, switch to the …
=> v7 enhance(utils) expand filterSchema

packages/merge/tests/merge-schemas.spec.ts, packages/utils/src/getResolversFromSchema.ts
Related #2031. getResolversFromSchema was cloning the entire scalar type, including the AST node, and addResolversToSchema was concatenating the directives from the original AST node and the cloned one. This fix changes getResolversFromSchema to omit the AST node from the cloned type. This seems reasonable, since none of the other types there have an AST node included.
=> Fix duplication of scalar directives in merge

packages/merge/src/typedefs-mergers/merge-nodes.ts, packages/merge/src/typedefs-mergers/scalar.ts, packages/merge/tests/merge-typedefs.spec.ts
Minor change to support [scalar extensions](https://spec.graphql.org/June2018/#sec-Scalar-Extensions) by merging scalar directives. Based on the logic from merging enums. Lint and tests pass.
=> Support scalar extensions by merging directives

website/docs/remote-schemas.md, website/docs/server-setup.md
👋,
this is a small PR showing how to leverage [`graphql-transport-ws`](https://github.com/enisdenjo/graphql-transport-ws) to add subscriptions support over WebSockets.
=> docs: Example of using graphql-transport-ws

.changeset/odd-moons-hunt.md, packages/utils/src/helpers.ts
Problem: `@graphql-codegen` silently ignore paths with `$`.
Solution: remove `$` from `invalidPathRegex`
TODO:
=> Remove $ from invalidPathRegex

.changeset/cool-ads-sin.md, .changeset/itchy-pillows-trade.md, packages/delegate/src/transforms/AddArgumentsAsVariables.ts
This fixes a type error in the `addVariablesToRootField` function.
The interface for the `FieldNode` type has the `arguments` field as an optional type, whereas the original code treats it like the array is always present:
```typescript
export interface FieldNode {
readonly kind: 'Field';
readonly loc?: Location;
readonly alias?: NameNode;
readonly name: NameNode;
readonly arguments?: ReadonlyArray<ArgumentNode>;
readonly directives?: ReadonlyArray<DirectiveNode>;
readonly selectionSet?: SelectionSetNode;
}
```
This resolves the original #820 issue, which is that delegating to remote schema fails.
The selection this is tripping up on has the following shape:
```js
{ kind: 'Field', name: { kind: 'Name', value: '__typename' }
```
=> Fix type error with `arguments` being undefined

.changeset/new-pears-compete.md, .changeset/thin-ways-wave.md, .github/workflows/canary.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/website.yml, package.json, packages/links/package.json, packages/links/src/AwaitVariablesLink.ts, packages/links/src/createServerHttpLink.ts, packages/links/src/linkToExecutor.ts, packages/links/src/linkToSubscriber.ts, packages/loaders/url/src/index.ts, packages/utils/src/observableToAsyncIterable.ts, packages/wrap/src/transforms/HoistField.ts, yarn.lock
After Apollo Client v3 got released, `apollo-link` and `apollo-link-http` have been deprecated. So `@graphql-tools/links` package now uses `@apollo/client/links` directly as a peer dependency to prevent `instanceof` and typing issues.
This PR also fixes typing mismatch between `observableToAsyncIterator` and `linkToSubscriber`.
See #2111 and https://github.com/ardatan/graphql-tools/issues/2105#issuecomment-715382726
=> Update `links` package to use `@apollo/client/links`

.changeset/honest-taxis-fix.md, packages/delegate/src/externalObjects.ts, packages/stitch/tests/typeMerging.test.ts
v7 introduced a regression in the merging of ExternalObjects that causes type merging to fail when undergoing multiple rounds of merging.
#2157
=> fix(stitch): mergeExternalObjects regressions

.changeset/wet-garlics-tickle.md, packages/utils/src/observableToAsyncIterable.ts
revert to old behavior of returning an AsyncIterableIterator
=> fix(utils): observableToAsyncIterable return type

.changeset/heavy-peas-begin.md, packages/links/package.json
`links` should behave like other packages when releasing and not publish new versions with minor updates of internal dependencies
=> chore(packaging): allow patches of local packages

website/docs/server-setup.md
The `graphql-transport-ws` library has been renamed recently, its called `graphql-ws` now. Just a small PR fixing the name and links 😄 .
=> Use graphql-ws name

packages/stitch/tests/isolateComputedFields.test.ts
I noticed earlier that `isolateComputedFields` tests were missing the `.test` extension that makes them run as part of the automated test suite. This adds the `.test` extension, and then fixes some new errors in the coverage:
- Removes the SDL test. I believe SDLs are translated into static config before ever hitting this operation now.
- Updates a check on `Storefront` type presence in filtered schema. It looks like `pruneSchema` isn't doing everything it did before here and I'm not sure what the new expectations are. @yaacovCR?
=> test(stitch) enable isolateComputedFields test

.changeset/poor-ears-sip.md, packages/loaders/prisma/src/index.ts
As exposed in #2208 , env vars in prisma.yml are not correctly resolved by `graphql-tools`.
This PR implements the workaround described in the above issue. We have been using this patch locally in our codebase without issues so far.
=> fix (Prisma): Don't initialize env vars with empty object

.changeset/honest-oranges-tie.md, package.json, packages/import/package.json, packages/import/src/index.ts, packages/load-files/package.json, packages/load-files/src/index.ts, packages/loaders/code-file/package.json, packages/loaders/code-file/src/index.ts, packages/loaders/graphql-file/package.json, packages/loaders/graphql-file/src/index.ts, packages/loaders/json-file/package.json, packages/loaders/json-file/src/index.ts, packages/loaders/prisma/package.json, packages/loaders/prisma/src/index.ts, packages/loaders/prisma/src/prisma-yml/Environment.test.ts, packages/loaders/prisma/src/prisma-yml/Environment.ts, packages/loaders/prisma/src/prisma-yml/PrismaDefinition.test.ts, packages/loaders/prisma/src/prisma-yml/PrismaDefinition.ts, packages/loaders/prisma/src/prisma-yml/test/getTmpDir.ts, packages/loaders/prisma/src/prisma-yml/yaml.ts, yarn.lock
Node 10 added support for promisified methods out of the box
and recursive flag for mkdir method. pathExists can be replaced with
fs.access methods which though throws error instead of returning
boolean.
TODO:
=> Replace fs-extra with native methods

.changeset/flat-monkeys-watch.md, .changeset/pink-eagles-cheer.md, packages/graphql-tools/package.json, packages/graphql-tools/src/index.ts, packages/optimize/src/optimizers/remove-empty-nodes.ts
- Added missing `Directive` handling for empty-nodes optimizer.
- Added export from root `graphql-tools` package.
=> Fixes for optimize package

packages/delegate/src/delegationBindings.ts, packages/stitch/tests/mergeInterfaces.test.ts
I came across a bug with merged interfaces while putting together a demo of them. It looks like a pretty simple fix unless I'm overlooking something.
We have two merged interfaces...
```graphql
interface Placement {
id: ID!
name: String!
}
interface Placement {
id: ID!
index: Int!
}
type Item implements Placement {
id: ID!
name: String!
index: Int!
}
type Query {
placement(id: ID!): Placement
}
```
Querying for the full interface works fine:
```graphql
query {
placement(id: 23) {
id
name
index
}
}
```
HOWEVER, it breaks when we query without `id`, which is the key used by the merge `selectionSet`.
```graphql
query {
placement(id: 23) {
name
index
}
}
```
This solution simply adjusts delegation transform order to put `ExtandAbstractTypes` in front of `AddSelectionSets`. That way abstracts …
=> fix(stitch) Add selectionSets to abstract types

.changeset/moody-worms-shave.md, .changeset/seven-dryers-vanish.md, packages/batch-delegate/src/getLoader.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/mergeFields.ts, packages/delegate/src/transforms/CheckResultAndHandleErrors.ts, packages/delegate/src/types.ts, packages/stitch/tests/mergeFailures.test.ts
At present there's a bug in error paths mapped from batched arrays... an error taken from a batched array always ends with its position in the underlying batch set, even though that position is not applicable within the stitched document path:
```json
{
"errors": [
{
"message": "nope",
"locations": [],
"path": [
"parent",
"thing",
0
]
}
],
"data": {
"parent": {
"thing": null
}
}
}
```
This checks the return type of the delegation query and omits the final path position from array values when they check out as integers.
cc @yaacovCR
=> fix(stitch) fix merged error paths from batched arrays

.changeset/olive-parrots-cross.md, packages/delegate/src/mergeFields.ts
Disallows key fields to be filtered from subschema.
Work-around would be to use filterSchema to filter as desired after creating the stitched schema.
=> fix(typeMerging): enable renaming of subschema key fields via transforms

.changeset/fuzzy-bugs-sparkle.md, packages/wrap/src/transforms/MapFields.ts, packages/wrap/src/transforms/TransformCompositeFields.ts
see:
https://github.com/ardatan/graphql-tools/issues/2282
https://github.com/graphql/graphql-js/pull/2861
https://github.com/graphql/graphql-spec/pull/776
=> fix(transforms): don't add __typename to subscriptions

.changeset/angry-coats-relax.md, packages/delegate/src/delegationBindings.ts, packages/delegate/src/types.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/types.ts, packages/stitch/tests/nestedRootTypes.test.ts
addresses #2347
also removed code that adds __typename to all merged types, it should only be necessary for root types when nesting, as all other merged types should have some selection set hint defined.
=> fix(stitch): add __typename for root fields

.changeset/sixty-walls-remember.md, packages/stitch/src/stitchSchemas.ts, packages/stitch/tests/stitchSchemas.test.ts
External data metadata is sometimes lost when utilizing type shadowing...
Sometimes users may want to delegate from a gateway to a subschema by utilizing "type shadowing," i.e. by creating types on the gateway that mirror/mimic types in the remote schema. Normally, we encourage users to use transforms to rename types and fields from a subschema as desired, rather than create new fields on the gateway. However, we did/should support users that prefer to manually create types on the gateway that match the subschema rather than using transforms.
Schema stitching used to support this method in v4, by always utilizing the defaultMergedResolver, but along the way between v4 and at least v6, we stopped using the defaultMergedResolver as the default resolver for all new fields defined on the …
=> fix(stitch): always use defaultMergedResolver by default on gateway

.changeset/unlucky-apes-raise.md, packages/utils/src/filterSchema.ts, packages/utils/tests/filterSchema.test.ts
Whoops. Forgot to extend argument filtering to root fields in the new v7 implementation of `filterSchema`. This adds argument filtering for root fields.
Why? Because filtering arguments is really handy while reducing an API down to only a select set of features made available to the public.
TODO:
=> enhance(utils) filter root field arguments with filterSchema

.changeset/dirty-bears-agree.md, .changeset/hungry-dragons-drop.md, packages/stitching-directives/src/stitchingDirectives.ts, packages/utils/src/fix-schema-ast.ts, packages/utils/src/get-directives.ts, packages/utils/src/print-schema-with-directives.ts, packages/utils/src/types.ts, packages/utils/tests/print-schema-with-directives.spec.ts
GraphQL directives defined without an astNode should be converted to as astNode/print.
GraphQL directives found in extensions should be converted to astNodes/print.
=> enhance(printSchemaWithDirectives): for code first schemas

.changeset/proud-cooks-begin.md, packages/stitch/src/selectionSetArgs.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/tests/typeMergingWithDirectives.test.ts, packages/stitch/tests/typeMergingWithExtensions.test.ts, packages/stitching-directives/src/stitchingDirectivesTransformer.ts, packages/stitching-directives/tests/stitchingDirectivesTransformer.test.ts, packages/utils/src/selectionSets.ts, website/docs/stitch-directives-sdl.md, website/docs/stitch-schema-extensions.md
When using simple keys, i.e. when using the keyField argument to `@merge`, the keyField can be added implicitly to the types's key. In most cases, therefore, `@key` should not be required at all.
=> enhance(stitching-directives): use keyField

.changeset/grumpy-suits-scream.md, packages/delegate/src/mergeFields.ts
@yaacovCR – was reading some delegation code and happened to notice what appears to be a mistake in the query planner logic. Seems like after a `filter`, this:
```js
if (nonUniqueSubschemas == null) { ...
```
Should be this:
```js
if (!nonUniqueSubschemas.length) { ...
```
Also flattened out an `includes` call to check the map directly, which _I think_ should still be compatible with all versions of Node that support `Map`.
=> fix(delegate) fix array check

.changeset/eleven-toys-arrive.md, packages/merge/src/typedefs-mergers/enum-values.ts, packages/merge/src/typedefs-mergers/enum.ts, packages/merge/src/typedefs-mergers/merge-typedefs.ts, packages/stitch/src/mergeCandidates.ts
Follows up the conversation and change made here: https://github.com/ardatan/graphql-tools/pull/2417/files#r554290366
At present in the `merge` package, enum values are merged in the opposite direction from an enum type; so merging enums A and B results in type characteristics of A being prioritized and value characteristics of B being prioritized. This was normalized in https://github.com/ardatan/graphql-tools/pull/2417, but not released for fear of the potential for breaking changes.
This rewrites the normalization to go through an opt-in setting. When `consistentEnumMerge` is enabled, the enum value merger will reverse its arguments for consistency with the type merger. I've specifically chosen to update the value merger function because it is the unit that is implemented backwards …
=> fix(merge/stitch) consistent enum value merge

.changeset/plenty-pots-impress.md, packages/webpack-loader/src/index.ts, packages/webpack-loader/tests/loader.test.ts
```diff
- {"kind" : "Document", definitions: []}
+ {"kind" : Kind.DOCUMENT, definitions: []}
```
It should save up some bundle size
=> Introduce replaceKinds option in webpack-loader

.changeset/rich-books-nail.md, packages/stitch/src/mergeCandidates.ts, packages/stitch/tests/mergeDefinitions.test.ts
In a slightly ridiculous oversight, I wrote tests for `canonical` stitching code and directives code, but never stitching + directives code together. Go figure, I missed a critical piece of linkage in referencing `transformedSubschema` rather than `subschema`.
This fixes subschema references so that directives now affect canonical outcomes properly.
=> fix(stitch) canonical via transformed subschema

.changeset/fast-lizards-try.md, packages/batch-delegate/tests/typeMerging.example.test.ts, packages/delegate/src/subschemaConfig.ts, packages/delegate/src/types.ts, packages/stitch/src/isolateComputedFields.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/subschemaConfigTransforms/computedDirectiveTransformer.ts, packages/stitch/tests/isolateComputedFields.test.ts, packages/stitch/tests/mergeComputedFields.test.ts, packages/stitching-directives/src/stitchingDirectivesTransformer.ts, packages/stitching-directives/tests/stitchingDirectivesTransformer.test.ts, website/docs/stitch-type-merging.md, website/sidebars.js
Cleans up the splitting of computed schemas to preserve subschema configuration as follows:
- Currently, the `fields` setting on the base schema is eliminated in the presence of computed fields. This assures that field settings of the base schema (such as `canonical`) are preserved, and that computed field settings are transferred to the computed schema.
- Currently, both subschemas resolve with a duplicate `computedFields` setting, which I believe is moot after this stage in schema building? It's still odd though, because the base schema no longer has computed fields. So, the `computedFields` setting is removed from the base schema.
- Also assures that the computed schema disables its types as `canonical` so that they don't conflict with the base definition.
- Aaaaand, fixes a bunch of …
=> [deploy_website] fix(stitch) cleanup computed field splitting

.changeset/heavy-peaches-search.md, .changeset/sweet-humans-draw.md, .changeset/young-chairs-float.md, packages/load/package.json, packages/load/src/load-typedefs/collect-sources.ts, packages/loaders/module/package.json, packages/loaders/module/src/index.ts, packages/merge/package.json, packages/merge/src/typedefs-mergers/merge-typedefs.ts, packages/utils/src/isDocumentNode.ts, packages/utils/src/print-schema-with-directives.ts, packages/utils/src/types.ts, packages/utils/tests/print-schema-with-directives.spec.ts
- Instead of printing every single generated astNode, collect all astNode to create a `DocumentNode` and print it
- Extract that code to another function that creates `DocumentNode` from `GraphQLSchema` -> `getDocumentNodeFromSchema`
- Replace `parse(printSchemaWithDirectives(` with new `getDocumentNodeFromSchema`
- Take `defaultValue` of an input value while creating astNode from the field of GraphQLInputObjectType; Related #2610
=> Small refactor and fixes in printSchemaWithDirectives and improvements in other packages

algolia/config.json, patches/@docusaurus+theme-search-algolia+2.0.0-alpha.fd17476c3.patch
- Adds Codegen to the list of websites to be indexed by docsearch
- Fixes bug with enterkey in search which led to routing within the same site
=> Fixed bugs with Docsearch

.changeset/lucky-bats-relax.md, packages/load-files/src/index.ts, packages/load-files/tests/file-scanner.spec.ts, packages/load-files/tests/test-assets/custom-extractor/factory-func.js, website/docs/schema-merging.md
**Custom extraction from exports**
By default, `loadFiles` checks export names `typeDefs`, `resolvers` and `schema`. But you can change the way it extracts the content from the exported values.
Let's say you have a factory function inside your resolvers like below;
```js
module.exports = customQueryTypeName = ({
[customQueryTypeName]: {
foo: () => 'FOO',
}
})
```
And you can define custom `extractExports` like below;
```js
const { loadFilesSync } = require('@graphql-tools/load-files');
const resolvers = loadFilesSync(join(__dirname, './resolvers/**/*.js'), {
extractExports: fileExport => {
if (typeof fileExport === 'function') {
return fileExport('query_root');
}
return fileExport;
}
})
```
=> feat(load-files): ability to provide a custom extractExports

.changeset/kind-houses-collect.md, packages/utils/src/prune.ts, packages/utils/src/types.ts, packages/utils/tests/prune.test.ts
`pruneSchema` accepts a secondary parameter, `PruneSchemaOptions`. This object contains properties like `skipEmptyCompositeTypePruning` and `skipEmptyUnionPruning` which allow you to skip specific use cases of pruning. We can also add another option `skipPruning` which is a function that accepts the `GraphQLNamedType` and returns true when we should not prune a specific type.
This would help solve issues around pruning [Apollo Federation](https://www.apollographql.com/docs/federation/) schemas but it is also a general purpose filter that anyone can use when pruning schemas.
Related #2723
```ts
test('does not prune types that match the filter', () => {
const schema = buildSchema(`
directive @bar on OBJECT
type CustomType @bar {
value: String
} …
```
=> Add generic pruning filter option

website/docs/stitch-schema-extensions.md
The DataLoader documentation explicitly mentions that 
> - The Array of values must be the same length as the Array of keys.
> - Each index in the Array of values must correspond to the same index in the Array of keys.
This implicit contract should be made explicit in this documentation as well. Otherwise it might be assumed that it would get the correct results based on the key.
=> enhance(docs) clarify batchDelegateToSchema results implicit contract

packages/stitching-directives/src/properties.ts, packages/stitching-directives/tests/stitchingDirectivesTransformer.test.ts
Add tests to make sure that key selectionSets work consistently between SDL directives and MergeTypeConfigs.
One test currently failing (lists within lists).
Related #2735
- OS: Mac OS 11.0.1
- `@graphql-tools/stitching-directives`: 1.3.1
- NodeJS: 14.15.1
=> args from keys cornercase tests

.changeset/gentle-foxes-look.md, packages/utils/src/stub.ts
Related #2804
```
graphql "__fake" must not begin with "__", which is reserved by GraphQL introspection.
```
c.f. https://github.com/graphql/graphql-spec/pull/244
=>  __ is reserved for introspection

website/docs/server-setup.md
As of [`graphql-ws@v4.3.0`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.3.0) the `execute` and `subscribe` server options are optional.
=> docs(server-setup): `graphql-ws` uses `graphql`'s execute and subscribe

.changeset/tidy-dancers-dance.md, packages/loaders/url/package.json, yarn.lock
I use semantic versioning and take extra care not to break anything in minor and patch bumps. `graphql-ws` bugs take the high priority lane and I release patches as soon as they get fixed.
I know you use the renovate bot to do the bumps for you; however, I still wouldnt use exact versioning to make sure the user always has the latest and the newest.
P.S. This is just a suggestion, feel free to close this PR in case you feel different about this.
=> chore(url-loader): Use compatible `graphq-ws` versioning

.changeset/young-swans-deliver.md, packages/utils/src/visitResult.ts, packages/utils/tests/visitResult.test.ts
visitResult fails if querying reserved fields. This PR currently does not have a solution for the problem, only a failing test is added to reproduce it.
Credit to @mjbcopland for creating the issue and writing the reproduction.
Related #2860 
https://codesandbox.io/s/happy-visvesvaraya-s9fk7
=> fix(visitResult): don't throw on encountering __typename in request (#2860) 

.changeset/sixty-tools-teach.md, packages/batch-delegate/tests/aliasing.test.ts, packages/batch-delegate/tests/withTransforms.test.ts, packages/wrap/src/transforms/TransformQuery.ts
`delegateToSchema` conditionally applies `defaultMergedResolver` based on whether the object is external. An object is determined to be external based on whether it has the symbol UNPATHED_ERRORS_SYMBOL.
Removing the symbol in `batchDelegateToSchema.valuesFromResult` by returning plain js objects breaks query aliasing.
This PR currently just contains a failing test to reproduce the bug
[#2829](https://github.com/ardatan/graphql-tools/issues/2829)
=> batch-delagate: create failing test for aliasing bug

.changeset/slimy-tools-decide.md, packages/import/src/index.ts, packages/import/tests/schema/fixtures/deep/a.graphql, packages/import/tests/schema/fixtures/deep/b.graphql, packages/import/tests/schema/import-schema.spec.ts
This adds a simple deeply nested graphql schema failing test. It proves that there is a bug with deep nested structures in the `import` package.
Related #1591
=> fix(import): handle nested imports correctly

.changeset/fuzzy-jobs-own.md, packages/batch-delegate/package.json, packages/batch-execute/package.json, packages/delegate/package.json, packages/schema/package.json, packages/wrap/package.json, yarn.lock
We seem use the caret for internal packages, pin for external dependencies (...except ts-lib)
This PR fixes a few outliers.
=> chore(deps): streamline pinning

packages/stitch/src/index.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/src/types.ts
Exports type definitions from the Stitch package to make them available for TypeScript introspection. Should address https://github.com/ardatan/graphql-tools/issues/2865.
In the process, the `StitchingInfo` and `MergedTypeInfo` types are removed from the `stitch` package in favor of using the primary definitions in the `delegate` package.
=> chore(stitch) export typescript package types + cleanup

.changeset/warm-buckets-applaud.md, packages/mock/src/MockStore.ts, packages/mock/tests/mocking-compatibility.spec.ts
I ran into a very mysterious error when working with `@graphql-tools/mock` and abstract types:
```
__typename does not exist on type ConcreteType
```
This seems to occur under some specific circumstances:
1. A selection is made against an interface
2. A selection is made against a non-null object field on the interface
3. The explicit mocks contain a `__typename` on the interface
4. The explicit mocks do not contain the aforementioned object field
I've tried to capture this in a new test case, which fails on master but is handled with this patch. I also have an external repro here:
https://github.com/72636c/graphql-tools-mock-typename
- OS: macOS 10.15.7
- `@graphql-tools/mock`: 8.1.2
- NodeJS: 14
=> fix(mock): avoid __typename does not exist error

.changeset/lucky-mayflies-shout.md, packages/utils/src/executor.ts
See https://github.com/ardatan/graphql-tools/pull/2749 and
https://github.com/ardatan/graphql-tools/commit/58fd4b285ae9eff9c2098c5d589a14cfa0f03718
for some history.
There's still one more problem however: an Executor is still a generic
function over any possible context type. <TContext = TBaseContext>
merely sets a default if the function is called without explicit type 
arguments, but implementation is still required to work with any other 
type that may be passed for `TContext`.
Since context exists to hold application-specific information, requiring
executors to be generic is not useful. An application's implementation 
of resolvers, executors, subscribers, etc. will only work with that 
application's context type and can't be generic.
An example of how the previous typing fails in my …
=> Make executors not generic over context types

.changeset/friendly-coins-beam.md, packages/load/tests/loaders/schema/schema-from-json.spec.ts, packages/utils/src/getResolversFromSchema.ts
Related https://github.com/ardatan/graphql-tools/issues/2955
Checks for a double underscore, rather than a single underscore.
I've tested this change locally against the Keystone project (where we discovered the bug) and verified that it fixes the issues we were seeing.
=> Fix bug handling single underscore type names

renovate.json, yarn.lock
I ran `npx yarn-deduplicate --strategy fewer` locally and also configured renovate to run it when updating dependencies. This avoids having a lot of different versions of the same package when possible.
=> dedupe yarn deps

packages/schema/src/addResolversToSchema.ts, packages/schema/tests/schemaGenerator.test.ts
If resolvers are implemented as methods in a class and invoke this, then this leads to an error as this in undefined when the resolver is invoked. For example, the following does not work as `this` inside `myResolver` is undefined.
```ts
resolvers = {
Query: new QueryResolver()
....
}
class QueryResolver() {
private someVariable: string = 'a'
myResolver(root, args, context) {
return this.someVariable
}
}
```
The reason for this bug is that the resolver method is invoked out of context without prior binding of `this` to the instance.
Related …
=> Properly bind resolver function to class instance

packages/merge/src/merge-resolvers.ts, packages/utils/src/mergeDeep.ts, packages/utils/tests/mergeDeep.test.ts
The `mergeDeep` function only merged enumerable properties of the objects, and ignored methods / properties from the prototype chain. This is fixed, and a few tests are added for this method as well.
Related #3038
Using the added unit tests
- OS: Win 10
- `@graphql-tools/...`: master branch
- NodeJS:
=> Merge prototypes of resolvers

.changeset/fifty-wombats-help.md, packages/mock/src/types.ts
Fixes an error I get when GraphQL JS passes a prototypeless object into the resolver
```
ReferenceError: maybeRef is not defined
at eval (eval at <anonymous> (/Users/mattalexander/Projects/edge-sites-schema/tests/regression.test.js:67:7), <anonymous>:1:38)
at forEach (/projectpath/tests/regression.test.js:67:7)
at Array.forEach (<anonymous>)
at Object.<anonymous> (/projectpath/tests/regression.test.js:65:17)
``` …
=> Safer use of `Object.prototype.hasOwnProperty`

.changeset/grumpy-months-nail.md, packages/resolvers-composition/src/resolvers-composition.ts, packages/resolvers-composition/tests/resolvers-composition.spec.ts
Bug fix - Checking if there are any endpoints before treating them as an array.
On a specific occasion there were no mutations so trying to do Object.keys(undefined) threw an exception. 
Related https://github.com/ardatan/graphql-tools/issues/3075
=> BugFix: Handle parsing endpoints when there are no mutations

packages/batch-delegate/src/getLoader.ts
I don't think this needs a changeset, as #3010 has not yet been released.
=> don't throw on errors that should not be relocated

.changeset/fresh-queens-watch.md, packages/batch-delegate/tests/withTransforms.test.ts, packages/batch-execute/src/createBatchingExecutor.ts, packages/batch-execute/src/getBatchingExecutor.ts, packages/batch-execute/src/mergeRequests.ts, packages/delegate/src/createRequest.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/index.ts, packages/delegate/src/transforms/AddArgumentsAsVariables.ts, packages/delegate/src/transforms/FilterToSchema.ts, packages/delegate/src/types.ts, packages/delegate/tests/batchExecution.test.ts, packages/links/src/linkToExecutor.ts, packages/loaders/url/src/index.ts, packages/stitch/tests/fixtures/schemas.ts, packages/utils/src/Interfaces.ts, packages/utils/src/executor.ts, packages/wrap/src/transforms/MapLeafValues.ts, packages/wrap/src/transforms/TransformInputObjectFields.ts, packages/wrap/tests/fixtures/schemas.ts, packages/wrap/tests/requests.test.ts, website/docs/remote-schemas.md, website/docs/stitch-combining-schemas.md, website/docs/stitch-type-merging.md
* also affixes rootValue to Request
* when delegating with delegateToSchema, rootValue can be set multiple ways:
* when using a custom executor, the custom executor can utilize a
rootValue in whichever custom way it specifies.
* when using the default executor (execute/subscribe from graphql-js):
-- rootValue can be passed to delegateToSchema via a named option
-- rootValue can be included within a subschemaConfig
-- otherwise, rootValue is inferred from the originating schema
- when using wrapSchema/stitchSchemas, a subschemaConfig can specify the
createProxyingResolver function which can pass whatever rootValue it
wants to delegateToSchema as above.
=> consolidate Request and ExecutionParams types

.changeset/quick-hotels-beam.md, packages/stitch/src/subschemaConfigTransforms/computedDirectiveTransformer.ts, packages/stitch/tests/mergeDefinitions.test.ts, packages/stitch/tests/typeMergingWithExtensions.test.ts, packages/stitching-directives/src/stitchingDirectivesTransformer.ts, packages/stitching-directives/src/stitchingDirectivesValidator.ts, packages/utils/src/get-directives.ts, packages/utils/tests/get-directives.spec.ts, packages/utils/tests/schemaTransforms.test.ts, packages/wrap/src/transforms/RemoveObjectFieldsWithDirective.ts, website/docs/schema-directives.md
BREAKING CHANGE: getDirectives now always return an array of DirectiveAnnotation objects
New function getDirective returns an array of args records for each use of the directive.
Note: this is true even when the directive is non-repeatable. This is because one use of this function is to throw an error if more than one directive annotation is used for a non repeatable directive!
See https://github.com/ardatan/graphql-tools/issues/2534
=> feat: support Gatsby-style directives in extensions

packages/delegate/src/delegationBindings.ts, packages/delegate/src/getFieldsNotInSubschema.ts, packages/delegate/src/transforms/AddSelectionSets.ts, packages/delegate/src/types.ts, packages/stitch/src/stitchingInfo.ts
-- run collectFields on selectionSet hints at build time
-- use a fieldNode cache at build time so that at run time we can collect unique fieldNodes simply by using a Set (rather than by printing nodes and using a Map)
=> refactor(stitchingInfo): shift more calculation to build time

.changeset/green-rocks-swim.md, packages/delegate/src/externalObjects.ts, packages/merge/src/extensions.ts, packages/merge/src/merge-resolvers.ts, packages/stitching-directives/src/stitchingDirectivesTransformer.ts, packages/utils/src/mergeDeep.ts, packages/utils/tests/mergeDeep.test.ts
Extracted from #3195
- Use Object.assign instead of mergeDeep in mergeExternalObject
- Remove isScalarType check in mergeDeep because it already merges prototypes 
- Add a flag to merge prototypes
=> mergeDeep improvements

.github/workflows/tests.yml, packages/load/tests/loaders/documents/documents-from-glob.spec.ts, packages/load/tests/loaders/schema/schema-from-typedefs.spec.ts, packages/loaders/code-file/src/index.ts, packages/loaders/graphql-file/src/index.ts
this enables running tests on windows with node 14 and graphql 15 only.
Also resolves path issues
=> fix loader glob issues and run tests on windows

.changeset/metal-files-worry.md, packages/wrap/src/transforms/TransformQuery.ts, packages/wrap/tests/transforms.test.ts
Fix for TransformQuery where path is longer than 1.
- Returns correctly the entire response while only modifying the relevant `path`
- Preserves other fields that are not part of the `path`
Related #3323
Tests for this fix are included. If fix isn't present the longer path fails with the error described in the issue. Other tests are left untouched so backwards compatibility is ensured.
- N/A
- N/A
=> Fix for supporting longer paths in TransformQuery

.changeset/spicy-lions-shop.md, packages/delegate/src/resolveExternalValue.ts, packages/stitch/tests/typeMerging.test.ts
Fixes nested type merge issue, when children multiple levels deep may be repeated on parents.  Fixes #3372 
Tested against a fairly complex pre-existing schema which exhibited the behavior prior to change
- OS: Windows 10
- `@graphql-tools/delegate`: 8.0.8
- NodeJS: v12.21.0
=> Fix nested type merges with repeated children ignore all but first occurrence

.changeset/shaggy-monkeys-smoke.md, packages/utils/src/build-operation-for-field.ts, packages/utils/tests/build-operation-node-for-field.spec.ts
Related #3380 #3381
I found the bug when trying to use this rule https://graphql-rules.com/rules/mutation-payload-query
#3381
- OS:
- `@graphql-tools/utils`: 6.2.3
=> fix(buildOperationNodeForField): mutation response return a field of type Query

packages/wrap/tests/transformWrapFields.test.ts, website/docs/schema-wrapping.mdx
Just came across `WrapFields` and was really amazed by how slick it is. This adds `wrap` package tests for it (both for coverage and to demonstrate its use, which I find extremely helpful with wrap transforms). Also adds a mention of it to the Schema Wrapping docs page for discoverability.
=> Wrap: add package tests for WrapFields

.changeset/six-radios-talk.md, packages/mock/src/MockStore.ts, packages/mock/tests/addMocksToSchema.spec.ts
This pull request adds tests the demonstrates the problem using _id fields in schema which is being mocked.
Related #3464
A test demonstrating an issue with _id fields in schema being mocked.
=> test: check if key field _id is resolved correctly

.changeset/brown-panthers-kneel.md, packages/merge/src/typedefs-mergers/merge-typedefs.ts, packages/merge/tests/merge-typedefs.spec.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/src/typeFromAST.ts, packages/utils/src/comments.ts
This pull request adds tests the demonstrates the problem merging typedefs with comments in them. 
**Note: This does not fix the issue** and should not be merged, this is just a reproduction.
Related #3244
Reproduction only
- OS: Linux
- `@graphql-tools/...`: master branch
- NodeJS: v14.17.5
=> fix(commentDescriptions): handle descriptions and comments correctly during merge

packages/wrap/tests/transformTransformCompositeFields.test.ts
Adds a preliminary test suite for `TransformCompositeFields`. I'm slowly filling in tests while exploring various transforms. Hopefully tests offer coverage and help document capabilities for others seeking reference within the documentation wasteland of the `wrap` package.
=> Wrap: tests for TransformCompositeFields

.changeset/forty-cooks-learn.md, packages/graphql-tag-pluck/src/index.ts
closes #3515 
tested the changes locally and everything works flawlessly with these changes
=> fix(graphql-tag-pluck): fix ESM usage

.changeset/tender-schools-bathe.md, packages/utils/src/visitResult.ts, packages/utils/tests/visitResult.test.ts
`visitData` method fails to visit objects containing read-only properties (getters). Updated the for loop to avoid processing the read-only properties.
Related #3554 
```js
describe('visiting data', () => {
it('should work when the parent contains properties with getters only', async () => {
const result = {
data: Buffer.from("Test"),
};
const visitedResult = visitData(result);
expect(visitedResult).toEqual(result);
});
});
```
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also …
=> Fixing visitData to prevent assingning read only properties

.changeset/three-colts-film.md, packages/mock/src/MockStore.ts, packages/mock/src/types.ts, packages/mock/tests/store.spec.ts
This change adds `has(typename: string, key: KeyT) => boolean` to MockStore to allow checking if data for a given key has previously been generated in the store.
Addresses #3479 
Tests have been provided in packages/mock/tests/store.spec.ts
- OS: MacOS 10.14.6
- NodeJS: 14.17.5
=> Add MockStore.has method

.changeset/great-owls-prove.md, packages/load/src/schema.ts, packages/load/tests/loaders/schema/integration.spec.ts, tsconfig.json
It breaks GraphQL Inspector 
```typescript
const schema = await load('...', {
loaders: [...],
schemas: [
buildSchema(`scalar DateTime`)
]
});
```
https://github.com/kamilkisiela/graphql-inspector/blob/03c49eaef0d6634e5222ee255990293a6ce355a5/packages/loaders/loaders/src/index.ts#L47-L55
=> loadSchema no longer accept options.schemas

.changeset/eight-experts-rush.md, packages/import/src/index.ts, packages/import/tests/schema/fixtures/multiple-levels-master-schema/level1.graphql, packages/import/tests/schema/fixtures/multiple-levels-master-schema/level2.graphql, packages/import/tests/schema/fixtures/multiple-levels-master-schema/level3.graphql, packages/import/tests/schema/fixtures/multiple-levels-master-schema/level4.graphql, packages/import/tests/schema/import-schema.spec.ts
If the schemata being processed contains only imports (and no definitions), we need to ensure the dependencies on those imports are fully resolved. The associated change will ensure all imported definitions fully resolve their dependencies and all relevant transitive dependencies. Without this alteration, imported definitions would only partially resolve required dependencies.
Related #3597
- OS: MacOS Big Sur 11.6
- `@graphql-tools/import`: 7.3.1
- NodeJS:
=> Fixing master schemata dependency resolution.

.changeset/healthy-penguins-learn.md, packages/import/src/index.ts, packages/import/tests/schema/fixtures/multiple-imports/schema.graphql
This PR breaks down the `processImport` function into more granular functions and exports them from the `@graphql-tools/import` package.
Related https://github.com/ardatan/graphql-tools/issues/3638
=> Refactor processImport from @graphql-tools/import

.changeset/lovely-guests-join.md, packages/import/src/index.ts, packages/import/tests/documents/import-documents.spec.ts, packages/import/tests/documents/import-test/default/d.gql, packages/import/tests/documents/import-test/default/with-nested-fragment.gql
related https://github.com/dotansimha/graphql-eslint/issues/654
It seems like a bug but `AnotherPostFields` is never imported even he is used in `PostFields` fragment that is used in `UserFields` fragment
=> fix(import): allow import nested fragments properly

website/docs/mocking.mdx
Fixing a small typo on mocking documentation - MockStore
Doc description refers to a `set` operation while the example shows a `get` operation.
Related #3853
=> Small typo on mocking docs

website/docs/mocking.mdx
Fix syntax error of the example provided for a byId fields.
Run the example
- n/a I have commented my code, particularly in hard-to-understand areas
- n/a I have added tests that prove my fix is effective or that my feature works
- n/a New and existing unit tests and linter rules pass locally with my changes
=> Fix example of handling byId fields in the docs

.changeset/poor-olives-report.md, packages/graphql-tag-pluck/src/utils.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts
Fixes graphql-tag-pluck returning results consisting of only whitespace. When it should just return an empty string
Related #3911
I've added two commits. The first one only adds a test which fails. The second fixes the tests. No existing tests fail
=> Fix graphql-tag-pluck returning results when it shouldn't

.changeset/seven-fireants-carry.md, packages/mock/src/addMocksToSchema.ts, packages/mock/src/index.ts, packages/mock/src/pagination.ts, packages/mock/src/utils.ts, packages/mock/tests/pagination.spec.ts, packages/utils/CHANGELOG.md, website/docs/mocking.mdx
This PR adds a helper to `@graphql-tools/mock` that makes mocking Relay-style pagination easier:
```ts
import { buildSchema } from 'graphql';
import { addMocksToSchema, relayStylePaginationMock } from '@graphql-tools/mock';
const typeDefs = /* GraphQL */`
type User {
id: Id!
name: String!
friends(first: Int!, after: String): FriendsConnection!
}
type PageInfo {
hasNextPage: Boolean!
endCursor: String!
}
type FriendConnection {
totalCount: Int!
edges: [FriendEdge!]!
pageInfo: PageInfo!
}
type FriendEdge {
node: User!
cursor: String!
}
type Query {
me: User!
}
`
const schema = …
```
=> [mock] Feature: add Relay style pagination mock helper

.changeset/gentle-poets-compete.md, packages/mock/src/addMocksToSchema.ts, packages/mock/tests/mocking-compatibility.spec.ts
Resolves an issue with custom scalar mocks being ignored in deep mocking when the `preserveResolvers` option is turned on. Please check the related issue for more information.
Related #4035 
Unit tests
=> Update to deep mocking with custom mocks when preserveResolvers option is turned on

.changeset/famous-owls-sit.md, packages/load/src/documents.ts
Fixes the following error that shows up when using `graphql@15`:
```
dist/load/src/documents.d.ts:12:43 - error TS2749: 'Kind' refers to a value, but is being used as a type here. Did you mean 'typeof Kind'?
12 export declare const NON_OPERATION_KINDS: Kind[];
```
Related https://github.com/ardatan/graphql-tools/issues/4050
1. In a local graphql-tools repository (without this change!), run `yarn build`
2. Run `yarn add graphql@15 -W` to override what's currently in the package.json devDependencies
3. Run `./node_modules/.bin/tsc --noEmit dist/load/src/documents.d.ts`
4. See the TypeScript error above
5. Apply the change from this PR
6. Run `yarn build` again
7. Run `./node_modules/.bin/tsc --noEmit dist/load/src/documents.d.ts` again
8. See …
=> fix(load): fix type for NON_OPERATION_KINDS

.changeset/shy-poems-tell.md, packages/import/src/index.ts, packages/load/src/load-typedefs.ts
Documenting merging issue with respect to `processImport`
Related https://github.com/ardatan/graphql-tools/issues/2980
=> Documenting duplicate typeDefs with processImport

website/docs/mocking.mdx
User reported a typo here: https://app.crisp.chat/website/af9adec5-ddfa-4db9-a4a3-25769daf2fc2/inbox/session_2247f5d0-4e6d-44d2-8af0-f1de034b3d74/
Related https://app.crisp.chat/website/af9adec5-ddfa-4db9-a4a3-25769daf2fc2/inbox/session_2247f5d0-4e6d-44d2-8af0-f1de034b3d74/
=> Fixing typo as suggested in crisp chat

.changeset/strange-carpets-bake.md, packages/delegate/package.json, packages/delegate/src/delegateToSchema.ts, packages/stitch/tests/alternateStitchSchemas.test.ts, packages/utils/src/prune.ts, yarn.lock
=> use graphql-executor

benchmark/federation/index.js, benchmark/federation/package.json, benchmark/federation/stitching.js, benchmark/federation/yarn.lock
compare benefit of executor to benefit of parse cache alone
=> add graphql-executor to benchmarks

.changeset/selfish-eggs-punch.md, packages/graphql-tag-pluck/package.json, yarn.lock
Only devDependencies should be pinned for libraries.
Related #4107
=> Don't pin babel deps to exact version

packages/schema/tests/merge-schemas.spec.ts
Saw an `it.only` was left in the `merge-schema` tests so some tests were being skipped. Created this small PR to remove it. All the previously skipped tests are passing on my local. 
Thanks for creating and maintaining `graphql-tools`!
=> fix: remove it.only from merge-schema tests

website/docs/schema-directives.mdx
(This is just a typo in your docs. I don't need to create an issue to help you fix this, that's silly.)
Typo location: `https://www.graphql-tools.com/docs/schema-directives`
The exported function from `@graphql-tools/utils`, as explained in the documentation, is **`getDirectives`**. In a few places the code blocks incorrectly use `getDirective`.
Changed all instances of `getDirective` → `getDirectives`
=> typo: docs/schema-directives - getDirective

.changeset/famous-humans-report.md, packages/merge/src/typedefs-mergers/interface.ts, packages/merge/tests/merge-typedefs.spec.ts
When I merge a schema definition like this:
```gql
interface Interface {
foo: String
}
extend interface Interface implements AdditionalInterface {
bar: String
}
interface AdditionalInterface {
bar: String
}
```
then I expect the `implements` to be preserved in the merged type (as is the case for type extensions), like this:
```gql
interface Interface implements AdditionalInterface {
foo: String
bar: String
}
interface AdditionalInterface {
bar: String
}
```
N/A
New unit test
=> Fix interface extension `implements` bug

website/docs/schema-directives.mdx
Corrects mistaken 'fix' merge in https://github.com/ardatan/graphql-tools/pull/4210, and gets the documentation and code blocks correct.
I was wrong, `@graphql-tools/utils` exports both `getDirective` AND `getDirectives`, and they can't be used in the same way, which was the original mistake in the documentation.
By their usage in the code blocks, passing in a single string with a directive name as the third argument to the function, this is meant to be `getDirective` (whose third argument is [`directiveName`](https://github.com/ardatan/graphql-tools/blob/b472f413e6fa40340f48bf750bcbff3a8fa51e95/packages/utils/src/get-directives.ts#L168)) vs. `getDirectives` (whose third argument is string array [`pathToDirectivesInExtensions`](https://github.com/ardatan/graphql-tools/blob/b472f413e6fa4034 …
=> docs/schema-directives - fixing confusion with getDirective vs. getDirectives

.changeset/thin-numbers-own.md, packages/mock/src/addMocksToSchema.ts, packages/mock/tests/addMocksToSchema.spec.ts
_I've opened an [issue](https://github.com/ardatan/graphql-tools/issues/4155) about this more than a month ago._
`addMocksToSchema` accepts an optional `store`. When a `store` is not provided, a default store will be used. 
In some cases, the `mockResolver` defined in `addMocksToSchema` will still use the default store, even when a `store` option is provided to `addMocksToSchema`.
This PR adds a test for this use case and fixes the bug.
Related #4155
This repository reproduces the issue: https://github.com/lipsumar/repro-graphql-tools-mock-store-issue
A unit test is provided and will fail if the proposed change in `addMocksToSchema` is removed.
- OS: Mac OS 11.6.2 (20G314)
- `@graphql-tools/mock`: latest (master / `8.5.2`) …
=> fix: use correct store in mockResolver

packages/wrap/src/transforms/TransformQuery.ts, packages/wrap/tests/transformTransformQuery.test.ts, packages/wrap/tests/transforms.test.ts
This PR:
* adds a failing test showing that the prior code would not call queryTransformer when there is no selection set
* re-adds the functionality of `TransformQuery#queryTransformer` being called even when the `selectionSet` is empty
Related https://github.com/ardatan/graphql-tools/issues/4311
Tough to say on this? It is a bug fix. Whether or not the change is breaking is fuzzy IMO. It's arguably a breaking change given that it makes the types _less_ strict, which may cause users with stricter types on their `queryTransformer` functions to see type errors.
=> Allow empty selectionSet when calling TransformQuery#queryTransformer

.changeset/pink-rivers-join.md, packages/graphql-tag-pluck/src/utils.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
I have tested the output of the function to make sure it's the same as the current one
- OS:
- NodeJS:
=> refactor: replace deprecated String.prototype.substr()

.changeset/dull-eyes-work.md, packages/schema/src/addResolversToSchema.ts
In previous versions, if `requireResolversToMatchSchema` was set to `ignore`, although no error would be thrown for an unexpected resolver type, type processing would still be aborted early. This fix changes the behavior to correctly continue resolver type processing with the next provided type.
In previous versions, if a resolver field began with double underscores, it would correctly be used for legacy behavior to directly set a type property, but field processing would be aborted early. This fix changes the behavior to correctly continue type processing with the next field.
https://github.com/ardatan/graphql-tools/pull/3096/#discussion_r838020747
=> fix(addResolversToSchema): continue processing all types and fields in edge cases

.changeset/grumpy-dragons-cry.md, packages/utils/src/print-schema-with-directives.ts, packages/utils/tests/print-schema-with-directives.spec.ts
Fix deprecated enum values not being parsed by File/UrlLoader.
Schema:
```gql
enum Color {
Red @deprecated(reason: "Blue is better")
Blue
}
```
Related #4350
I patched it in my own codebase, and it's been working great for months. Just trying to get …
=> Support deprecated directive on enum values

.changeset/slow-singers-pull.md, package.json, packages/delegate/src/Transformer.ts, packages/delegate/src/checkResultAndHandleErrors.ts, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/resolveExternalValue.ts, packages/links/src/linkToExecutor.ts, packages/loaders/git/src/parse.ts, packages/loaders/url/src/defaultAsyncFetch.ts, packages/loaders/url/src/index.ts, packages/loaders/url/tests/url-loader.spec.ts, packages/stitch/src/createMergedTypeResolver.ts, packages/stitch/src/stitchSchemas.ts, packages/stitch/src/stitchingInfo.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/tests/dataloader.test.ts, packages/utils/src/executor.ts, packages/wrap/src/generateProxyingResolvers.ts, packages/wrap/src/transforms/WrapFields.ts, packages/wrap/src/transforms/WrapType.ts, packages/wrap/src/wrapSchema.ts, yarn.lock
This PR was initially intended to be a reproduction of build errors caused by upgrading the TS version (to `typescript@4.7.0-beta`). This is now intended to be merged as-is, having resolved the build errors caused by upgrading to `typescript@4.7.0-beta` (followed by reverting the upgrade with no breakage).
The changes introduced in this PR bring this repo to `typescript@4.7` compatible while maintaining the existing typescript version for now. In doing so, a lot of the generic typings have been refined, so this seems like a win-win.
I've gone through and resolved the build errors (seemed to mostly all be of the class of error mentioned in https://github.com/microsoft/TypeScript/pull/48366). This seems ready to go if the maintainers agree with these changes.
Related #4381
Please delete …
=> `typescript@4.7` readiness (refine generic typings via `extends`)

.changeset/metal-bobcats-hunt.md, packages/utils/src/prune.ts, packages/utils/tests/prune.test.ts
`pruneSchema` will keep all implementations of an interface regardless of whether it is used or not. This replacement for `pruneSchema` will visit the schema based on root operations to determine used types within the schema, and prune unused types accordingly.
Related: https://github.com/ardatan/graphql-tools/issues/4365
To reproduce, prune the following schema:
```graphql
type Query {
operation: SomeType
}
interface SomeInterface {
field: String
}
type SomeType implements SomeInterface {
field: String
}
type ShouldPrune implements SomeInterface {
field: String
}
```
Please describe the tests that you ran to verify your …
=> prune function that only keeps types in execution path

.changeset/ten-spoons-promise.md, packages/delegate/src/checkResultAndHandleErrors.ts
as some implementations apparently may return null when no path is provided rather than not returning anything
=> consider relaxing error path check

.changeset/chilled-apricots-allow.md, packages/utils/src/prune.ts, packages/utils/tests/prune.test.ts
This fixes issue #4405 by correcting a check that improperly resulted in stripping all input types used or unused from the schema.
#4405 
Added an additional test to validate that used input types are not removed.
=> Fix pruneSchema removing used input object types

packages/jest-transform/src/index.ts
I tried to use this module today on a Jest 18 install and was met with this error:
> Invalid transformer module: <snip>/node_modules/@graphql-tools/dist/index.js specified in the "transform" object of Jest configuration must export a `process` or `processAsync` or `createTransformer` function.
Looking at the `babel-jest` module there is a comment [suggesting a default export is required](https://github.com/facebook/jest/blob/main/packages/babel-jest/src/index.ts#L276) and this seems to fix the above issue.
=> fix(jest-transform) Add default export

.changeset/angry-bobcats-double.md, .changeset/gold-timers-thank.md, .changeset/sweet-clouds-grab.md, package.json, packages/load/src/schema.ts, packages/loaders/url/src/index.ts, packages/loaders/url/tests/url-loader.spec.ts, packages/schema/src/merge-schemas.ts, packages/utils/src/getResolversFromSchema.ts, packages/wrap/tests/makeRemoteExecutableSchema.test.ts
`loadSchema`;
No longer call `mergeSchemas` if a single schema is loaded.
Previously all typeDefs and resolvers were extracted and the schema was rebuilt from scratch.
But this is not necessary if there is only one schema loaded with `loadSchema`
`mergeSchemas` was skipping `defaultFieldResolver` and `defaultMergedResolver` by default while extracting resolvers for each given schema to reduce the overhead. But this doesn't work properly if you mix wrapped schemas and local schemas. So new `includeDefaultMergedResolver` flag is introduced in `getResolversFromSchema` to put default "proxy" resolvers in the extracted resolver map for `mergeSchemas`.
This fixes an issue with alias issue, so nested aliased fields weren't resolved properly because of the missing `defaultMergedResolver` in the …
=> Introduce 'batch' flag, improve loadSchema and merge wrapped schemas properly

.changeset/beige-coats-kick.md, packages/utils/src/visitResult.ts, packages/utils/tests/visitResult.test.ts
Previously `visitResult` wasn't able to process introspection types because root query type's field map doesn't have introspection fields defined. So this PR handles this exception properly.
```ts
const introspectionRequest: ExecutionRequest = {
document: parse(getIntrospectionQuery()),
variables: {},
};
const result: any = {
data: introspectionFromSchema(schema),
};
expect(() =>
visitResult(result, introspectionRequest, schema, {
Query: {
__enter(val) {
return val;
},
},
})
).not.toThrow();
});
```
=> fix(visitResult): handle introspection fields correctly with an introspection query result

.changeset/sharp-paws-call.md, packages/loaders/url/src/index.ts
Closes https://github.com/ardatan/graphql-tools/issues/4550
Some environments like CF Workers don't support `credentials` in RequestInit object. But by default UrlLoader sends 'same-origin' and it wasn't possible to disable it. Now you can pass 'disable' to remove `credentials` property from RequestInit object completely.
=> New 'disable' flag for UrlLoaderOptions.credentials

.changeset/tidy-mangos-wash.md, packages/loaders/github/src/index.ts, packages/loaders/github/tests/schema-from-github.spec.ts
Github graphql API responds with HTTP status 401 when the token is
invalid.
Running the GitHub loader on a private repository with a missing or invalid GitHub token masks the real error as [object Object].
This happens because the GitHub GraphQL api returns 401 unauthorized if the token is not valid.
After some debugging the only http status code i could find that triggers this is 401.
With the returned payload being:
This PR fixes the problem for 401 by passing status to `handleResponse` and checking if that is 401 and reporting the correct message returned from Github. 
The response …
=> Fix Github loader responding with  401 with invalid credentials

.changeset/curly-tools-refuse.md, packages/loaders/url/src/event-stream/handleReadableStream.ts, packages/loaders/url/tests/url-loader-browser.spec.ts
Canceling a `fetch` request in a browser throws an "user aborted" error in the reader and its cancel method.
By using the `UrlLoader from @graphql-tools/url-loader` for GraphiQL's fetcher.
- Chrome and Safari: `latest`
- `@graphql-tools/url-loader`: `7.13.2`
=> fix(url-loader): ignore readable stream errors after completion

.changeset/dry-drinks-hammer.md, packages/delegate/src/Subschema.ts, packages/stitch/src/typeCandidates.ts, packages/stitch/tests/stitchSchemas.test.ts, packages/wrap/src/wrapSchema.ts
Fixes https://github.com/ardatan/graphql-tools/discussions/4631
After the refactor done in https://github.com/ardatan/graphql-tools/pull/4566, transforms are called twice.
This removes that call, too.
=> fix(stitching): ensure transformSchema called only once

.changeset/@graphql-tools_apollo-engine-loader-4665-dependencies.md, .changeset/@graphql-tools_github-loader-4665-dependencies.md, .changeset/@graphql-tools_jest-transform-4671-dependencies.md, .changeset/@graphql-tools_url-loader-4665-dependencies.md, .changeset/nasty-owls-compare.md, packages/utils/src/Interfaces.ts, packages/wrap/src/transforms/HoistField.ts
Update the typings so the the package is able to build with TypeScript v4.8 and the tests of the respective bump PR gets fixed.
Related #4674
Related #4672
- OS:
- NodeJS:
If this is a relatively large …
=> Type fixes for TypeScript 4.8

.changeset/violet-kiwis-doubt.md, packages/wrap/src/transforms/TransformInputObjectFields.ts, packages/wrap/tests/transformRenameInputObjectFields.test.ts
Related #4675
- OS: macOS 12.5.1
- `@graphql-tools/wrap`: 9.0.4
- NodeJS: v16.15.0
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> fix: Fixed Transforming wrapped input fields

.changeset/weak-news-cough.md, packages/loaders/url/src/index.ts
Related #4658
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
=> When using useGETForQueries make the URL as short as possible by stripping out all ignored characters

.changeset/short-melons-tell.md, .eslintrc.cjs, packages/utils/src/Path.ts, packages/utils/src/jsutils.ts
This is a build regression from #4778. I can file an issue if you really want me to.
Some pure-ESM processors (eg, `tsc` with `moduleResolution: 'nodenext') require extensions on all imports. #4778 added two import-less extensions. This PR fixes them and adds linting (from an already-installed plugin) to catch future errors. Test execution does not appear to require these extensions so we only check non-test files (there's another 17 errors to fix if you want to check tests too).
While this requirement isn't documented anywhere I found quickly, I have to assume it's intentional (since …
=> Add missing import extension, check with lint

.changeset/light-cups-kneel.md, packages/executor/package.json
When using Yarn 3, the usage of `@graphql-tools/executor` results in an error because it is requiring tslib but it isn't labeling it as a dependency.
`Error: @graphql-tools/executor tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.` 
It's marked as a dependency in pretty much every other package in the repo. It looks like the tslib requirement is being put in place by the typescript compilation process because it's not referenced in the source code of the package, but it is in the exported code visible here at …
=> Requires tslib

.changeset/stupid-wolves-fail.md, packages/wrap/src/transforms/TransformCompositeFields.ts, packages/wrap/tests/transformTransformCompositeFields.test.ts
This PR fixes the field `__typename` being added more than once when using `TransformCompositeFields` transform, which also other transforms use under the hood. More information in the issue below.
Related #4820 
A Unit test has been added with this PR.
- OS: macOS 12.5.1
- @graphql-tools/wrap: 9.2.9
- NodeJS: v16.15.0
The unit test is using `spyOn` and `toHaveNthReturnedWith` which might not be appropriate, if there is a better way to test this problem, please advice.
=> fix(wrap): Fixed __typename being added more than once in TransformCompositeFields

.changeset/@graphql-tools_graphql-tag-pluck-4863-dependencies.md, .changeset/gorgeous-foxes-hug.md, packages/graphql-tag-pluck/package.json, packages/graphql-tag-pluck/src/config.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts, yarn.lock
Related https://github.com/dotansimha/graphql-code-generator/issues/8630
=> feat(graphql-tag-pluck): support for import assertions

.changeset/giant-avocados-destroy.md, packages/delegate/src/prepareGatewayDocument.ts, packages/stitch/tests/typeMerging.test.ts
Fixes https://github.com/ardatan/graphql-tools/issues/4902
=> fix(type-merging): handle union types correctly

.changeset/fluffy-masks-develop.md, packages/utils/src/visitResult.ts, packages/utils/tests/visitResult.test.ts
This fixes an issue with introspection queries that affects other guild projects when using `@envelop/response-cache`
Related #5015 
I've added a test case for the visitResult function that fails currently and passes after the changes
- OS: Linux (codespaces container)
- `@graphql-tools/utils`: 9.1.4
- NodeJS: 14.x
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Fix error when visiting __type fields

.changeset/weak-tomatoes-act.md, packages/graphql-tag-pluck/src/visitor.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts
As described in the related issue, this introduces the ability for the graphql-tag-pluck package to match graphql queries that have declared with the typescript `as const` assertion. The reason you would do this is to force typescript to narrow the type to a string literal instead of just `string` which fixes a performance issue when using `@graphql-codegen/client-preset`
Related #4873 
- OS: mac os ventura
- …
=> Support matching template literals which are declared 'as const'

.changeset/curly-dolls-deny.md, packages/batch-delegate/src/getLoader.ts, packages/batch-delegate/src/types.ts, packages/batch-delegate/tests/basic.example.test.ts
`lazyOptionsFn` now accepts `keys` as an argument.
This way user can create a custom `options` based on the `keys`.
Beforehand It was not possible to pass arguments to an nested field.
Now it can be done with a custom `selectionSet` based on the `keys`.
Related #5102
Added a test with `lazyOptionsFn` returning custom `selectionSet` based on `keys`.
- OS: Windows 11
- NodeJS: 16.4.0
=> Add batch delegate lazy options from keys

.changeset/bright-glasses-watch.md, packages/delegate/src/symbols.ts
When multiple copies of `@graphql-tools/delegate` are available in a workspace (eg: because `stitch` and `wrap` depend on different versions), creating symbols with `Symbol()` can lead to bugs when one version of `delegate` sets an object property using its version of the symbol which the other `delegate` instance will not be able to access. Using `Symbol.for()` fixes this: as long as both versions of delegate use the same string description, they will refer to the same symbol.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and …
=> Create symbols with Symbol.for()

.changeset/@graphql-tools_github-loader-5151-dependencies.md, .changeset/smart-cameras-unite.md, .changeset/tender-eels-beam.md, packages/loaders/github/package.json, packages/loaders/github/src/index.ts, packages/loaders/github/tests/schema-from-github.spec.ts, packages/loaders/url/src/index.ts, packages/loaders/url/tests/url-loader.spec.ts, yarn.lock
related https://github.com/dotansimha/graphql-code-generator/issues/9273
=> fix(github/url): add missing user-agent for github and do not accept invalid protocols for UrlLoader

.changeset/dry-boats-smash.md, packages/batch-execute/src/splitResult.ts, packages/batch-execute/tests/batchExecute.test.ts
When an error that contains no path is returned in a batched operation the extensions are lost. 
I have changed it to just return the original error but we could wrap it like so.
```js
resultErrors.push(createGraphQLError(error.message, { ...error, originalError: error.originalError}));
```
Related # ([4732](https://github.com/ardatan/graphql-tools/issues/4732))
I ran into this issue and found the only way I could replicate it is on non pathed batch queries. 
Unit tested
=> Stitched schema loses error 'extensions' when batched

.changeset/nice-bulldogs-raise.md, packages/stitch/package.json
`@graphql-tools/stitch`: fix an issue with an undeclared dependency on `@graphql-tools/executor`
Package managers (pnpm, yarn pnp) strictly isolates the deps, without this `@graphql-tools/executor` seems to not be  resolvable. 
Related: https://github.com/ardatan/graphql-tools/issues/5234
Should fix:
Haven't tested it, but I guess it should work
=> fix(stitch): missing dep on @graphql-tools/executor

.changeset/short-spies-help.md, packages/graphql-tag-pluck/src/index.ts, packages/loaders/git/src/index.ts, packages/loaders/git/tests/__snapshots__/loader.spec.ts.snap, packages/loaders/git/tests/loader.spec.ts, packages/loaders/git/tests/test-files/a/b/file.graphql
See #5243 for issue details.
The issue occurs because `git ls-tree -r --name-only ref` in a subdirectory returns paths relative to cwd. `git show ref:file`, however, does not respect that relative path. Instead, it requires either a path relative to the root git directory or a `./`, neither of which `git ls-tree` provides.
This is simply fixed by adding back a leading `./` if the original path contained one.
Also fixed an error that `loadSync` not worked at all with globs.
n/a
- Tests pass
- I applied the patch on an own project and it works …
=> fix(git-loader): respect leading './' for globs

.changeset/cyan-ears-knock.md, packages/merge/src/typedefs-mergers/directives.ts, packages/merge/src/typedefs-mergers/enum-values.ts, packages/merge/src/typedefs-mergers/enum.ts, packages/merge/src/typedefs-mergers/fields.ts, packages/merge/src/typedefs-mergers/input-type.ts, packages/merge/src/typedefs-mergers/interface.ts, packages/merge/src/typedefs-mergers/merge-nodes.ts, packages/merge/src/typedefs-mergers/merge-typedefs.ts, packages/merge/src/typedefs-mergers/scalar.ts, packages/merge/src/typedefs-mergers/schema-def.ts, packages/merge/src/typedefs-mergers/type.ts, packages/merge/src/typedefs-mergers/union.ts, packages/merge/tests/merge-typedefs.spec.ts
According to [GraphQL Spec](https://spec.graphql.org/October2021/#example-67869) directives might be marked as repeatable, that means a GraphQL node might have more than one the same directive with different set of arguments. Currently `@graphql-tools/merge` package while merging doesn't respect `repeatable` directives and as a result overrides multiple same directives on one node and keeps only the last one. Which doesn't happen if directives declared in a node that isn't overridden. By this PR I merge directives definitions first and then use `isRepeatable` flag to merge directives …
=> fix(merge): Don't merge/override arguments for repeatable directives

.changeset/seven-boats-push.md, packages/utils/src/mergeIncrementalResult.ts, packages/utils/tests/mergeIncrementalResult.spec.ts
The function implementing merging of incremental results was not merging extensions, discarding it.
needed by https://github.com/n1ru4l/envelop/pull/1896
=> merge extensions in incremental result merging

.changeset/early-donkeys-join.md, packages/executors/graphql-ws/src/index.ts, packages/executors/legacy-ws/src/index.ts, packages/loaders/url/src/index.ts
Continuation task of https://github.com/Urigo/graphql-mesh/pull/4724
Uses the `connectionParams` from the operation extensions to extend the WebSocket connection parameters.
Are there any security implications with doing this?
=> Read and use the `connectionParams` from operation extensions

.changeset/stupid-pans-breathe.md, packages/utils/src/get-directives.ts
Exports the `DirectableGraphQLObject` type since it may be useful to library consumers. 
Related #5443
It has not given the size of the change.
=> Export DirectableGraphQLObject type

.changeset/fast-seahorses-visit.md, packages/graphql-tag-pluck/package.json, yarn.lock
Fixes yarn error:
```YN0002: │ @graphql-tools/graphql-tag-pluck@npm:8.0.1 [21b77] doesn't provide @babel/core (p8630f), requested by @babel/plugin-syntax-import-assertions```
Related https://github.com/ardatan/graphql-tools/issues/5066
=> Add @babel/core dependency to graphql-tag-pluck

.changeset/bright-moons-suffer.md, packages/batch-execute/src/prefix.ts, packages/batch-execute/src/splitResult.ts, packages/batch-execute/tests/batchExecute.test.ts
Key parsing logic for the `GraphQLError` `path` array is modified to search for the first item that satisfies the the batch key format. This allows external GraphQL API's to prefix error paths while still rewriting the error correctly for the consumer of `@graphql-tools/batch-execute`.
Related #5520 #5481 
I've provided a unit test to confirm the validity of the implemenation.
- OS: MacOS
- `@graphql-tools/...`: `batch-execute`
- NodeJS: v18.14.2
=> Loop through entire error path to find key match

.changeset/tender-lions-arrive.md, packages/executors/graphql-ws/src/index.ts
- simply changed the order how the configuration is given into the `graphql-ws`client and prevent the overwriting of the parameters
This should fix https://github.com/Urigo/graphql-mesh/issues/5774  and https://github.com/ardatan/graphql-tools/issues/5665
Related # (5774)
In the .meshrc of `graphql-mesh` with the `graphql`-handler I set
```
...
subscriptionsProtocol: WS
connectionParams:
user: "{context.headers['x-user']}"
...
```
where `"{context.headers['x-user']}"` now gets resolved.
- OS: macOS: 13.6
- `@graphql-tools/executor-graphql-ws`: 1.1.0
- NodeJS: 18.8.0
=> fix(graphql-ws-executor): changed initialization of graphql-ws client

packages/executors/http/src/index.ts, packages/executors/http/tests/buildHTTPExecutor.test.ts
This fix removes the headers from the extensions avoiding them being leaked in query parameters.
This happens if using the GraphiQL bundled in Yoga, this should fix the issue for Yoga if updated.
Related # ([5753](https://github.com/ardatan/graphql-tools/issues/5753))
I have written a unit test and confirmed the original ones work.
- OS:
- NodeJS: all
=> fix: remove headers from extensions

.changeset/twenty-walls-sleep.md, packages/utils/src/validate-documents.ts, packages/utils/tests/validate-documents.spec.ts
Make `validateGqlDocuments()` validation results more deterministic for cases when documents may include multiple anonymous definition nodes, where previously [validateGraphQLDocuments()](https://github.com/ardatan/graphql-tools/blob/000e93b47e437baa0a3d076ec09ff89a18a4b364/packages/utils/src/validate-documents.ts#L26) util would merge definitions in a way that created a risk for a race condition to take place depending on how fast the anonymous nodes get processed (definitions are keyed off `Date.now().toString()`), and blocked off certain validation rules.
This change essentially merges all definitions into one document as-is, with the exception of `FRAGMENT_DEFINITION` nodes, which get deduplicated based off their name. In turn this enables certain GraphQL rules, such as …
=> fix(utils): prevent race conditions when validating documents

.changeset/twenty-cats-drop.md, packages/mock/src/MockStore.ts, packages/mock/src/addMocksToSchema.ts, packages/mock/tests/store.spec.ts
Fix https://github.com/ardatan/graphql-tools/discussions/4497. This allows for finer-grained mocking with mocked data depending on field arguments.
```typescript
const store = createMockStore({
schema,
mocks: {
User: () => {
return {
name: ({ format }: { format: string }) =>
format === 'fullName' ? 'Alexandre the Great' : 'Alex',
};
},
},
});
store.get('User', '123', 'name', { format: 'fullName' }))
// Alexandre the Great
store.get('User', '123', 'name', { format: 'shortName ' }))
// Alex
```
=> Pass fieldArgs to value function

.changeset/perfect-files-bake.md, packages/federation/src/subgraph.ts, packages/federation/test/__snapshots__/subgraph.test.ts.snap, packages/federation/test/subgraph.test.ts
The federation package fails to create a valid schema in the case where no key directives are specified. This PR fixes this adding an empty `_Entity` union in this case.
=> fix: buildSubgraphSchema when there are no entity keys

.changeset/brown-guests-nail.md, packages/federation/src/subgraph.ts, packages/federation/test/__snapshots__/subgraph.test.ts.snap, packages/federation/test/subgraph.test.ts
Closes https://github.com/ardatan/graphql-tools/pull/5884
=> fix(federation/buildSubgraphSchema): do not create an invalid _Entity union if there is no entity defined

website/src/pages/docs/graphql-tag-pluck.mdx
Supported extensions stated in the document may be outdated.
I have updated the docs to follow the current implementation. 
https://github.com/ardatan/graphql-tools/blob/2c6c1d688741ef024b407e45f4040a667f7969e0/packages/graphql-tag-pluck/src/index.ts#L131-L146
=> Update doc to catch up with supported extensions for graphql-tag-pluck

.prettierignore
Adjust the prettierignore file to ignore changesets, but not the `README.md` and the `config.json`.
=> Prettier ignore changesets

.changeset/short-paws-provide.md, packages/graphql-tag-pluck/src/config.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts
A related issue #5869 has been open for several weeks.
This would be a simpler short-term solution to allow for the new syntax.
Adds the `explicitResourceManagement` parser plugin for babel. This allows using the stage 3 `using` keyword for resource management.
expected)
This has been tested by adding a test case to the `graphql-tg-pluck` package using the new syntax.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and …
=> Add explicitResourceManagement to the list of parser plugins in graphql-tag-pluck

.changeset/twelve-buckets-bow.md, packages/wrap/src/transforms/TransformCompositeFields.ts, packages/wrap/tests/transformTransformCompositeFields.test.ts
The `TransformCompositeFields` allows to transform fields, which automatically adds `__typename` to the selection set.
Problem is that to avoid duplicating the selection of this field, we check if it's already selected. This check is flawed because it doesn't take in account the possible alias, which leads to `__typename` not being selected if already present in the query with an alias.
This causes incompatibility with the response-cache plugin which rely on selecting `__typename`, but with a `__responseCacheType` alias.
Related https://github.com/ardatan/graphql-mesh/issues/6272
A better fix would have been to do exactly what response-cache plugin is doing, always adding typename but with a uniq identifiable alias. This would simplify code and allow for result clean up. But since the …
=> fix __typename not selected if already selected with alias

.changeset/warm-ducks-smash.md, packages/utils/src/filterSchema.ts, packages/utils/tests/filterSchema.test.ts
We are using `filterSchema()` on a schema that does not use the default `Query` type. We noticed that the `argumentsFilter()` does not work as expected and is provided with an inaccurate `typeName` argument.
I personally think that `rootFieldFilter()` should also pass the actual field name but I can see that is a breaking change. 
Related https://github.com/ardatan/graphql-tools/issues/5930
Added a unit test
- OS: Sonoma
- `@graphql-tools/utils`: 10.1.0
- NodeJS: v18.18.0 …
=> fix(filterSchema): provide actual type name for root field

.changeset/spotty-ways-give.md, packages/executor/src/execution/__tests__/subscribe-test.ts, packages/executor/src/execution/execute.ts
This reverts the changes for the executor introduced in https://github.com/ardatan/graphql-tools/pull/5187
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you considered, etc...
=> fix: revert subscription event source stream handling

packages/merge/src/typedefs-mergers/merge-nodes.ts, packages/merge/tests/merge-nodes.spec.ts
I was trying to make a toString directive and makeExecutableSchema was failing. 
It wasn't working because it creates an object (mergedResultMap in function mergeGraphQLNodes) and objects have an inherited toString method. So it was finding that toString exists in the map because it was the inherited object function, not a directive. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#direct_vs._inherited_properties)
So I thought maybe when merging the directive it could check if it exists and if it's an inherited property and not a …
=> allow toString directive  (check isNode on merge if inherited from prototype)

.changeset/pink-fishes-punch.md, packages/executor/src/execution/__tests__/abort-signal.test.ts, packages/executor/src/execution/__tests__/defer-test.ts, packages/executor/src/execution/__tests__/stream-test.ts, packages/executor/src/execution/execute.ts
This change properly handles the cancelation of defer/stream results returned from `normalizedExecutor`.
=> fix: incremental delivery cancelation unhandled rejection

.changeset/spotty-kiwis-crash.md, packages/utils/src/helpers.ts, packages/utils/tests/helpers.test.ts
A string may sometimes look like a path but is not (like an SDL of a simple GraphQL schema). To make sure we don't yield false-positives in such cases, we disallow new lines in paths (even though most Unix systems support new lines in file names).
An example of a false-positive:
```graphql
schema @transport(subgraph: "API", kind: "rest", location: "http://0.0.0.0:4001", headers: "{\"Content-Type\":\"application/json\"}") {
query: Query
mutation: Mutation
subscription: Subscription
}
```
=> Disallow new lines in paths when checking with `isValidPath`

.changeset/tricky-mice-crash.md, packages/batch-delegate/src/getLoader.ts, packages/federation/test/fixtures/gateway/discount/discount.graphql, packages/federation/test/fixtures/gateway/discount/index.ts, packages/federation/test/fixtures/gateway/products/index.ts, packages/federation/test/fixtures/gateway/products/products.graphql, packages/federation/test/fixtures/gateway/supergraph.graphql, packages/federation/test/fixtures/gateway/supergraph.yaml, packages/federation/test/gateway.test.ts, packages/federation/test/optimizations.test.ts
Fixes https://github.com/ardatan/graphql-mesh/issues/6671
=> fix(batch-delegate): respect the parent type name

.changeset/honest-trains-rule.md, packages/federation/src/utils.ts, packages/federation/test/fixtures/federation-compatibility/fed1-external-extends/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/fed1-external-extends/tests.json, packages/federation/test/fixtures/federation-compatibility/requires-interface/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/requires-interface/tests.json, packages/federation/test/fixtures/federation-compatibility/requires-with-fragments/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/requires-with-fragments/tests.json, packages/federation/test/fixtures/federation-compatibility/union-intersection/tests.json
- Handle Federation's `@inaccessible` directive on types
And this adds more tests for Federation
=> Handle @inaccessible on types & more Federation tests

.changeset/fresh-kangaroos-exist.md, .changeset/many-ads-run.md, packages/delegate/src/OverlappingAliasesTransform.ts, packages/delegate/src/Transformer.ts, packages/federation/src/supergraph.ts, packages/federation/test/federation-compatibility.test.ts, packages/stitch/src/mergeCandidates.ts, packages/stitch/src/mergeValidations.ts, packages/stitch/src/types.ts, packages/stitch/tests/mergeValidations.test.ts
Read the changeset for the description.
This PR fixes the validation issues within `no-entity` Federation example
=> fix: handle overlapping fields correctly across subschemas

.changeset/weak-bears-move.md, packages/merge/src/typedefs-mergers/merge-nodes.ts
Forgot to add a changeset when working on pull request ! 5973 which has already been merged and allows for a toString directive which couldn't before because toString is a property on all objects
Related #5967
=> add changeset for previous PR 5973

packages/stitching-directives/tests/reproductions.test.ts
=> Add reproduction for #4956

.changeset/healthy-news-enjoy.md, packages/delegate/src/delegateToSchema.ts, packages/delegate/src/prepareGatewayDocument.ts, packages/delegate/src/resolveExternalValue.ts, packages/federation/src/supergraph.ts, packages/stitch/tests/node.test.ts
When there is a Node subschema, and others to resolve the rest of the entities by using a union resolver as in Federation like below, it was failing. This version fixes that issue.
```graphql
query {
node(id: "1") {
id # Fetches from Node
... on User {
name # Fetches from User
}
}
}
```
```graphql
type Query {
node(id: ID!): Node
}
interface Node {
id: ID!
}
type User implements Node {
id: ID!
}
type Post implements Node {
id: ID!
}
```
```graphql
scalar _Any
type Query {
_entities(representations: [_Any!]!): [_Entity]!
}
union _Entity = User
interface Node {
id: ID!
}
type User implements Node {
id: ID!
name: String!
}
```
```graphql
scalar _Any
union _Entity = Post
type Query {
_entities(representations: [_Any!]!): [_Entity]!
}
interface Node {
id: ID!
}
type Post implements Node {
id: …
```
=> fix: Node subschema pattern

.changeset/lovely-games-reflect.md, packages/federation/src/supergraph.ts, packages/federation/test/fixtures/federation-compatibility/override-type-interface/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/override-type-interface/tests.json
Support overrides on interfaces
See [packages/federation/test/fixtures/federation-compatibility/override-type-interface/supergraph.graphql](https://github.com/ardatan/graphql-tools/blob/739264d5f7f2f4254d4d41f965d664ae04c37e45/packages/federation/test/fixtures/federation-compatibility/override-type-interface/supergraph.graphql) for more details
Closes https://github.com/ardatan/graphql-tools/issues/6074
=> fix(federation): override type federation

.changeset/sour-pianos-smile.md, packages/federation/src/supergraph.ts, packages/federation/test/federation-compatibility.test.ts, packages/federation/test/fixtures/federation-compatibility/interface-object-with-requires/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/interface-object-with-requires/tests.json, packages/federation/test/fixtures/federation-compatibility/non-resolvable-interface-object/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/non-resolvable-interface-object/tests.json, packages/federation/test/fixtures/federation-compatibility/simple-interface-object/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/simple-interface-object/tests.json, packages/stitch/src/subschemaConfigTransforms/isolateComputedFieldsTransformer.ts
Closes https://github.com/ardatan/graphql-tools/issues/6073
=> feat(federation): interface objects

.changeset/olive-shirts-buy.md, packages/delegate/src/extractUnavailableFields.ts, packages/delegate/src/index.ts, packages/delegate/src/prepareGatewayDocument.ts, packages/delegate/tests/extractUnavailableFields.test.ts, packages/delegate/tests/prepareGatewayDocument.test.ts, packages/stitch/src/createDelegationPlanBuilder.ts, packages/stitch/src/getFieldsNotInSubschema.ts, packages/stitch/tests/mergeFailures.test.ts
If a field is not going to be used for type merging in the following calls, do not add it to the final query to the subgraph.
See the changeset for the example
=> Ignore unmerged fields

.changeset/orange-balloons-grin.md, packages/delegate/src/defaultMergedResolver.ts, packages/delegate/src/index.ts, packages/delegate/src/leftOver.ts, packages/delegate/src/mergeFields.ts, packages/federation/test/fixtures/federation-compatibility/complex-entity-call/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/complex-entity-call/tests.json, packages/stitch/src/createDelegationPlanBuilder.ts, packages/stitch/src/createMergedTypeResolver.ts
If there are some fields depending on a nested type resolution, wait until it gets resolved then resolve the rest.
See packages/federation/test/fixtures/complex-entity-call example for more details.
You can see `ProductList` needs some fields from `Product` to resolve `first`
Closes https://github.com/ardatan/graphql-tools/pull/6076
=> fix(federation/stitch/delegate): handle complex nested keys

.changeset/old-lobsters-fold.md, packages/graphql-tag-pluck/src/index.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts, packages/load/tests/loaders/schema/schema-from-export.spec.ts
- Adds support for `graphql-tag-pluck` to pluck raw GraphQL from a custom Vue block.
- Adds an option `gqlVueBlock` (defaults to undefined) to specify the name of the custom block. The feature has no impact if this option is not set.
- The parsing of Vue blocks is already being done by the Vue parser, so this requires no additional dependencies or algorithms.
- Includes a new test and small documentation update.
- Very minimal refactoring was done to keep DRY.
Related #4320 
https://imgur.com/a/383F8uM
- OS: Ubuntu
- NodeJS: v16.15.0
- `@graphql-codegen/cli`: v2.6.2
- `@graphql-codegen/introspection`: v2.1.1
- `@graphql-codegen/typescript`: v2.4.7
- `@graphql-codegen/typescript-operations`: v2.3.4
- `@graphql-codegen/typescript-urql-graphcache`: v2.2.8
- …
=> Add option to pluck from custom Vue block

.changeset/rare-grapes-drive.md, packages/federation/test/fixtures/federation-compatibility/requires-requires/supergraph.graphql, packages/federation/test/fixtures/federation-compatibility/requires-requires/tests.json, packages/stitch/src/getFieldsNotInSubschema.ts
Handle nested dependencies in the computed fields
```ts
{
merge: {
Product: {
selectionSet: '{ id }',
fields: {
isExpensive: {
selectionSet: '{ price }',
computed: true,
},
canAfford: {
selectionSet: '{ isExpensive }',
computed: true,
},
}
}
}
}
```
=> fix(stitch): handle nested dependencies in computed fields

.changeset/four-items-live.md, packages/mock/src/addMocksToSchema.ts, packages/mock/tests/addMocksToSchema.spec.ts
This PR adds `updateResolversInPlace: true` to the call to `addResolversToSchema` in `addMocksToSchema`, to prevent large schemas from being cloned twice.
Related https://github.com/ardatan/graphql-tools/issues/6198
N/A
- Added a test that ensures that a new schema is always created by calls to `addMocksToSchema`, whether or not the `resolvers` argument is passed.
- OS: MacOS
- `@graphql-tools/mock`: 9.0.2
- NodeJS: v20.10.0 …
=> perf: only clone schema once in `addMocksToSchema`

.changeset/tough-flowers-listen.md, packages/documents/src/sort-executable-document.ts, packages/documents/tests/print-executable-graphql-document.spec.ts
printExecutableGraphQLDocument sorts mutations by name whereas from the GraphQL spec the order of mutation matters, they do not run in parallel like queries, but in series. See: [graphql.org/learn/queries/#multiple-fields-in-mutations](https://graphql.org/learn/queries/#multiple-fields-in-mutations).
This PR makes sure that mutations are not sorted and thus if you have a mutation where order matters they will run as 
you expect them to. 
Related #6195 
I was in doubt if it is a breaking change, but I think that anyone using the package …
=> fix(documents): do not order mutations

.changeset/hot-planes-smoke.md, .changeset/lovely-jokes-pull.md, packages/executors/envelop/src/index.ts, packages/executors/yoga/src/index.ts, packages/federation/src/supergraph.ts, packages/federation/test/federation-compatibility.test.ts, packages/federation/test/gateway.test.ts, packages/federation/test/optimizations.test.ts, packages/federation/test/queries.test.ts
BREAKING CHANGES:
- `getSubschemasFromSupergraphSdl` has been removed in favor of the new `getStitchingOptionsFromSupergraphSdl`, and it returns the options for `stitchSchemas` instead of the map of subschemas
- `onExecutor` has been removed in favor of `onSubschemaConfig`
- To change the default HTTP executor options, use `httpExecutorOpts` instead of `onExecutor`
=> Refactor Federation package

packages/federation/test/subscription.test.ts, packages/loaders/url/tests/test-utils.ts
This PR adds tests to test subscriptions in `@graphql-tools/federation`.
It adds two subgraphs that has different fields of `Post`, and one of the subgraphs have a subscription field, and the nested field `post` is filled by another subgraph. So it tests if type merging works as expected within subscriptions.
=> Add tests for subscriptions in Federation

.changeset/chilled-kids-flow.md, packages/executor/src/execution/__tests__/abstract-test.ts, packages/executor/src/execution/__tests__/resolveType.test.ts, packages/executor/src/execution/execute.ts
Fixes https://github.com/ardatan/graphql-tools/issues/6279
Since the executor is version agnostic, it should respect the schemas created with older versions.
So if a type resolver returns a type instead of type name which is required since `graphql@16`, the executor should handle it correctly.
See the following example:
```ts
// Assume that the following code is executed with `graphql@15`
import { execute } from '@graphql-tools/executor';
const BarType = new GraphQLObjectType({
name: 'Bar',
fields: {
bar: {
type: GraphQLString,
resolve: () => 'bar'
}
}
});
const BazType = new GraphQLObjectType({
name: 'Baz',
fields: {
baz: {
type: GraphQLString,
resolve: () => 'baz'
}
}
});
const BarBazType = new GraphQLUnionType({
name: 'BarBaz',
types: [BarType, BazType],
// This is the resolver that …
```
=> fix(executor): handle resolveType correctly for v15

.changeset/thirty-tigers-jump.md, packages/executor/src/execution/__tests__/variables-test.ts, packages/executor/src/execution/values.ts
(backport https://github.com/graphql/graphql-js/pull/3837; https://github.com/graphql/graphql-js/commit/076972e9c1944c9fe43a42046ed9d8be08d974dc)
=> fix: custom scalar original error propagation

packages/executor/src/execution/__tests__/oneOf-test.ts
Backport of https://github.com/graphql/graphql-js/commit/29144f73452f17ef669c6902f610f28afe61dbd1
=> chore: add test cases for oneOf support

packages/executor/src/execution/__tests__/executor-test.ts
Backports the test case from https://github.com/graphql/graphql-js/commit/)4a82557ae6d3b3c6cd72bcd528254296ecf7e9e8
The actual fix is already here.
=> test: backport test from graphql-js

.changeset/eleven-plums-tell.md, .changeset/nine-mayflies-retire.md, packages/delegate/src/prepareGatewayDocument.ts, packages/federation/src/supergraph.ts, packages/federation/test/__snapshots__/defer.test.ts.snap, packages/federation/test/defer.test.ts, packages/stitch/src/getFieldsNotInSubschema.ts, packages/utils/src/visitResult.ts
This PR adds tests for Federation with `@defer`.
=> Federation: Add tests with `@defer`

.changeset/lucky-bats-grab.md, packages/delegate/src/leftOver.ts, packages/executor/src/execution/__tests__/abort-signal.test.ts, packages/stitch/tests/isolateComputedFieldsTransformer.test.ts
Use native `Promise.withResolvers` when possible
=> enhance(delegate): use the native `Promise.withResolvers` when possible

.changeset/dry-rice-design.md, packages/executors/http/src/index.ts, packages/executors/http/tests/buildHTTPExecutor.test.ts
To allow errors to bubble up from upstream to client, errors contained into a valid execution result should be wrapped into an actual GraphQLError instance
=> [executors/http] wrap upstream graphql errors in a GraphQLError instance

.changeset/yellow-weeks-refuse.md, packages/executors/graphql-ws/src/index.ts, packages/executors/http/src/index.ts, packages/executors/http/tests/buildHTTPExecutor.test.ts, packages/federation/src/gateway.ts, packages/utils/src/executor.ts
Executor is no longer `Disposable` by default so you have to enable it with `disposable: true` option;
See [Explicit Resource Management](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management)
=> enhance(executor-http): add `disposable` option

.changeset/brave-jars-work.md, packages/executors/http/src/defaultPrintFn.ts
=> Strip ignored characters when printing a query in executor-http

.changeset/five-buttons-give.md, packages/executor/src/execution/execute.ts, packages/federation/src/supergraph.ts, packages/federation/test/error-handling.test.ts
Handle errors coming from subgraphs correctly when a root field is shared by different subgraphs
- If subgraph A returns an error for `Query.foo`, and subgraph B returns the data, ignore the error and keep it for null fields.
- If both subgraphs return errors, return them as `AggregateError` then return them to the gateway result.
=> fix(federation):  merge errors for shared root fields correctly

.changeset/early-birds-taste.md, packages/mock/src/MockStore.ts, packages/mock/tests/store.spec.ts
In MockStore, this change guards against an empty store in calls to filter/find to avoid calling Object.values() on undefined.
Related #6262 
- OS: macos
- `@graphql-tools/mock`: 9.0.3
- NodeJS: v22.2.0 …
=> Fix errors in find and filter with an empty store

.changeset/yellow-boats-walk.md, packages/federation/src/managed-federation.ts
The `schema` event is emitted each time we load a new schema with the already stitched schema. 
It can be useful to also have access to the raw supergraph SDL.
This is for example usefull for the integration with Apollo Server and its usage reporting feature.
=> expose the loaded supergraph sdl in the `schema` event

.changeset/wise-ravens-draw.md, packages/delegate/src/prepareGatewayDocument.ts, packages/delegate/tests/prepareGatewayDocument.test.ts
Fixes extra inline fragments for all abstract types in the upstream schema call
Also closes https://github.com/ardatan/graphql-mesh/issues/7235
If there are two subschemas like below, the final `Node` interface is implemented by both `Oven` and `Toaster` while they are not implemented in both schemas.
In this case the query `{ products { id ... on Node { id } } }` will need to be transformed to `{ products { id ... on Oven { id } ... on Node { id } } }` for the first subschema. But previously the query planner was automatically creating inline fragments for all possible types which was not optimal. Now it adds inline fragments only if this case is seen.
```graphql
type Query {
products: [Product]
}
union Product = Oven | Toaster
interface Node {
id: ID!
}
type Oven {
id: ID!
}
type …
```
=> fix(delegate): avoid extra inline fragments for all abstract types in the upstream call

.changeset/@graphql-tools_delegate-6420-dependencies.md, .changeset/good-parents-push.md, .changeset/nice-parrots-kick.md, packages/delegate/package.json, packages/delegate/src/createRequest.ts, packages/delegate/src/delegateToSchema.ts, packages/executor/src/execution/execute.ts, packages/federation/test/__snapshots__/defer-stream.test.ts.snap, packages/federation/test/defer-stream.test.ts, packages/stitch/tests/operationDirectives.test.ts, packages/utils/src/mapAsyncIterator.ts, packages/wrap/tests/requests.test.ts
Pass operation directives correctly to the subschema;
```graphql
query {
hello @someDir
}
```
Closes https://github.com/ardatan/graphql-tools/issues/6292
=> fix: forward operation directives to the subschema requests

packages/utils/src/debugTimer.ts
Removed optional chaining from `globalThis?.process.env['DEBUG'] || globalThis.DEBUG` to ensure it runs on Cloudflare Workers.
The current implementation with optional chaining is flawed as it fails when `globalThis` is undefined, resulting in an error when accessing `process.env`. Although this change does not fully resolve the issue, it aligns with the requirement for Cloudflare Workers compatibility.
Related https://github.com/cloudflare/workers-sdk/issues/6402
- OS: MacOS
- NodeJS: 20
The original error is within the Cloudflare Worker runtime, but this update ensures it will work in that environment.
=> fix: remove optional chaining in debug environment variable check

packages/utils/src/getDirectiveExtensions.ts, packages/utils/tests/getDirectiveExtensions.spec.ts
This change allow for invalid paths to be specified within the `getDirectiveExtensions` function.
Related #6435 
expected)
The function is tested in other tests, but a small set of tests specific to the function is now included with failing test that has been fixed:
```
PASS  packages/utils/tests/getDirectiveExtensions.spec.ts
```
- OS:
- NodeJS: …
=> fix(utils): Allow invalid path in getDirectiveExtensions

.changeset/four-deers-protect.md, packages/delegate/src/prepareGatewayDocument.ts, packages/delegate/tests/prepareGatewayDocument.test.ts, packages/federation/src/utils.ts, packages/federation/test/federation-compatibility.test.ts
Fix the bug happens when a merged field is a computed field requires another computed field requires a field from the initial subschema.
In the following test case, `totalOrdersPrices` needs `userOrders` which needs `lastName` from initial `Query.user`.
So the bug was skipping the dependencies of `userOrders` because it assumed `lastName` already there by mistake.
```ts
const schema1 = makeExecutableSchema({
typeDefs: /* GraphQL */ `
type User {
id: ID!
firstName: String!
lastName: String!
address: String
}
type Query {
user: User
}
`,
resolvers: {
Query: {
user: () => {
return {
id: 1,
firstName: 'Jake',
lastName: 'Dawkins',
address: 'everywhere',
};
},
},
},
});
const schema2 = makeExecutableSchema({
typeDefs: /* GraphQL */ `
type UserOrder {
id: ID!
}
type User {
id: ID! …
```
=> Nested Computed Fields Edge Case

.changeset/witty-lemons-drive.md, packages/federation/src/utils.ts, packages/federation/test/getKeyFnForFederation.test.ts
Filter errors as null in the projected key
If the key field has `Error`, do not send them to the subgraphs as objects but `null`.
=> fix(federation): filter errors as \`null\` while projecting the entity for the key

.changeset/stale-feet-rhyme.md, packages/delegate/src/defaultMergedResolver.ts, packages/delegate/src/mergeFields.ts, packages/delegate/src/resolveExternalValue.ts, packages/federation/src/supergraph.ts, packages/federation/src/utils.ts, packages/federation/test/federation-compatibility.test.ts
Handle merged selection sets in the computed fields;
When a selection set for a computed field needs to be merged, resolve that required selection set fully then resolve the computed field.
In the following case, the selection set for the `author` field in the `Post` type is merged with the selection set for the `authorId` field in the `Comment` type.
Query:
```graphql
{
feed {
author { id }
}
}
```
Subschema A;
```graphql
type Query {
feed: [Post!]!
}
type Post {
id: ID!
author: User! @computed(selectionSet: "{ comments { authorId } }")
}
type Comment {
id: ID!
authorId: ID!
}
type User {
id: ID!
name: String!
}
```
Subschema B;
```graphql
type Post {
id: ID!
comments: [Comment!]!
}
type Comment {
id: ID!
}
```
=> Fix nested computed fields

.changeset/cuddly-ants-change.md, packages/executors/graphql-ws/src/index.ts
This PR aims to allow users to configure HTTP headers for the WS connection request.
This is needed to allow headers propagation for subscriptions based on WebSockets in Hive Gateway
=> [executors/ws] Allow to configure headers

.changeset/thirty-parents-walk.md, packages/graphql-tag-pluck/package.json, packages/graphql-tag-pluck/src/config.ts, packages/graphql-tag-pluck/src/index.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts, packages/loaders/code-file/src/index.ts, yarn.lock
Add support for `.gts` and `.gjs` files in `graphq-tag-pluck` 
Related #6519 
Added unit tests.
=> feat: `graphql-tag-pluck` support for `.gts` & `.gjs` files [Issue #6519]

.changeset/wise-parrots-walk.md, packages/utils/src/getDirectiveExtensions.ts
> 🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**
> _Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
I did not create an issue in advance. The change was small and quick to make, so no worries if the PR is rejected.
After upgrading `@graphql-tools/utils@10.2.0` to `10.5.4`, I noticed this TypeScript error in custom schema directives:
```ts
import { getDirective, MapperKind, mapSchema } from "@graphql-tools/utils";
import type { GraphQLSchema } from "graphql";
export function applyFooBarSchemaTransformer(schema: GraphQLSchema) {
return mapSchema(schema, {
[MapperKind.OBJECT_FIELD]: (fieldConfig) => {
const [directive] =
getDirective(
schema,
fieldConfig,
// ↑↑↑↑
// Argument of type …
```
=> Make two types compatible with strict tsc config

.changeset/eleven-schools-build.md, .github/workflows/tests.yml, packages/delegate/src/extractUnavailableFields.ts, packages/federation/test/optimizations.test.ts, packages/loaders/url/tests/url-loader-browser.spec.ts, packages/stitch/src/createDelegationPlanBuilder.ts, packages/stitch/src/getFieldsNotInSubschema.ts, packages/stitch/src/subschemaConfigTransforms/isolateComputedFieldsTransformer.ts, packages/stitch/tests/isolateComputedFieldsTransformer.test.ts, packages/stitch/tests/mergeComputedFields.test.ts
When there are two services like below then the following query senty, the gateway tries to fetch `id` as an extra field because it considers `id` might be needed while this is not correct.
This patch avoids any extra calls, and forwards the query as is to the 2nd service.
```graphql
query {
viewer {
booksContainer(input: $input) {
edges {
cursor
node {
source {
upc
}
}
}
pageInfo {
endCursor
}
}
}
}
```
```graphql
type Book @key(fields: "id") @key(fields: "upc") {
id: ID!
upc: ID!
}
```
```graphql
type BookContainer { # the type that is used in a collection
id: ID!
source: Book!
}
type Book @key(fields: "upc") {
upc: ID!
}
type Query {
viewer: Viewer
}
type Viewer {
booksContainer: BooksContainerResult
}
type BooksContainerResult {
edges: [BooksContainerEdge!]!
pageInfo: PageInfo!
}
type …
```
=> fix(federation/stitch): avoid recursively type-merging in case of multiple keys

.changeset/changelog.md, packages/federation/src/supergraph.ts
If `currentUnavailableSelectionSet.selections` is empty array then "query planning" always fails in subsequent code.
Details can be found in issue [#6588](https://github.com/ardatan/graphql-tools/issues/6588).
Fixes [#6588](https://github.com/ardatan/graphql-tools/issues/6588)
Tested by downloading the currently fully functional supergraph from our Apollo Studio GraphQL registry (schema composition is validated by Apollo) which is transformed to stitched schema by `getStitchedSchemaFromSupergraphSdl()`method and served by GraphQL Yoga. No special configuration is used during transforming of supergraphSdl.
```ts
import { getStitchedSchemaFromSupergraphSdl } from '@graphql-tools/federation';
const schema = getStitchedSchemaFromSupergraphSdl({ …
```
=> fix(federation): continue if currentUnavailableSelectionSet.selections is empty array

.changeset/mean-goats-invent.md, packages/stitch/src/stitchSchemas.ts
Sets assumeValid to true when creating new GraphqlSchema in stitchSchemas.
Im not 100% sure if this is really safe to do so, but the perf implications are non negligible. So if we cannot just assume the schema to be valid at this stage then we can hopefully at least leave this for the user to decide somehow?
Internal releases.
- NodeJS:
=> perf: Assume internally created schemas as valid

.changeset/three-houses-cry.md, packages/utils/src/mergeDeep.ts, packages/utils/tests/mergeDeep.test.ts
Handle array of primitives correctly
The bug was following;
```ts
mergeDeep([
{ options: ['$a', '$b'] },
{ options: ['$c'] },
{ options: ['$d', '$e'] },
])
// results in { options: [{}, {}] }
```
=> fix(utils): handle array of primitives correctly

.changeset/hip-bikes-hunt.md, packages/executor/src/execution/__tests__/abort-signal.test.ts, packages/executor/src/execution/execute.ts, packages/executor/src/execution/promiseForObject.ts, packages/utils/src/index.ts, packages/utils/src/registerAbortSignalListener.ts, website/theme.config.tsx
PR to #6789 PR
- Single helper for AbortSignal event listener registration so it can be used by other packages, too.
- Replace `if(signal.aborted) throw` logic with `signal?.throwIfAborted`
- Check if there is only one listener registered to AbortSignal in tests
- Shared rejection promise for AbortSignal instead of creating it multiple times
=> Single place for AbortSignal listeners -> #6789

packages/graphql-tag-pluck/src/visitor.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts, website/src/pages/docs/graphql-tag-pluck.mdx
Currently globalGqlIdentifierNames are converted to lower case before being used for matching. This patch removes this conversion so they match in the file if the identifier in the code source is not all lower case. Previously if you had a mixed case globalGqlIdentifierName in the source code it would not match.
Eg: `const x = testGql(` could not be plucked using globalGqlIdentifierName as it is mixed case.
It also re-enables tests
Related # 5944 …
=> make globalGqlIdentifierName case sensitive

.changeset/hip-bikes-hunt.md, .changeset/selfish-worms-decide.md, packages/executor/src/execution/__tests__/abort-signal.test.ts, packages/executor/src/execution/execute.ts, packages/executor/src/execution/promiseForObject.ts, packages/utils/src/index.ts, packages/utils/src/registerAbortSignalListener.ts, website/theme.config.tsx
I noticed the "possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit." warning within our Hive GraphQL API service, which leads back to setting up too many event listeners here.
While the warning is not a real issue, we should avoid triggering it.
Extra from @ardatan ;
- Single helper for AbortSignal event listener registration so it can be used by other packages, too.
- Replace if(signal.aborted) throw logic with signal?.throwIfAborted
- Check if there is only one listener registered to AbortSignal in tests
- Shared rejection promise for AbortSignal instead of creating it multiple times
Existing tests pass, so the provided functionality stays the same.
=> fix: avoid "possible EventEmitter memory leak detected" warning

.changeset/@graphql-tools_apollo-engine-loader-6831-dependencies.md, .changeset/@graphql-tools_github-loader-6831-dependencies.md, .changeset/@graphql-tools_url-loader-6831-dependencies.md, packages/loaders/apollo-engine/package.json, packages/loaders/apollo-engine/src/index.ts, packages/loaders/github/package.json, packages/loaders/github/src/index.ts, packages/loaders/url/declarations.d.ts, packages/loaders/url/package.json, packages/loaders/url/src/defaultSyncFetch.ts, yarn.lock
The only reason to use our fork was to avoid `Buffer` usage for the browser code. Now it's not used anymore, and we can use the upstream `sync-fetch` package directly instead of `@ardatan/sync-fetch` fork.
=> Use upstream sync fetch instead of our fork

.changeset/funny-berries-grin.md, packages/executor/src/execution/execute.ts
Related https://github.com/dotansimha/graphql-yoga/pull/3672
=> feat(executor): `extensions.code`

.changeset/whole-hands-smell.md, packages/utils/src/build-operation-for-field.ts
Fix for [https://github.com/ardatan/graphql-tools/security/code-scanning/45](https://github.com/ardatan/graphql-tools/security/code-scanning/45)
To fix the problem, we need to ensure that all occurrences of the characters '!', '[', and ']' are replaced, not just the first occurrence. This can be achieved by using regular expressions with the global flag. Specifically, we will replace the `replace` method calls with regular expressions that include the global flag (`/g`).
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix for code scanning alert no. 45: Incomplete string escaping or encoding

packages/mock/src/MockStore.ts
Potential fix for [https://github.com/ardatan/graphql-tools/security/code-scanning/30](https://github.com/ardatan/graphql-tools/security/code-scanning/30)
To fix the prototype pollution issue, we need to ensure that `typeName` and `key` cannot be set to `__proto__`, `constructor`, or `prototype`. This can be achieved by adding a validation step before using these variables as keys in the `this.store` object. If either `typeName` or `key` matches any of these restricted values, we should throw an error or handle it appropriately.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix for code scanning alert no. 30: Prototype-polluting assignment

.changeset/dark-crabs-glow.md, packages/merge/src/merge-resolvers.ts
Potential fix for [https://github.com/ardatan/graphql-tools/security/code-scanning/29](https://github.com/ardatan/graphql-tools/security/code-scanning/29)
To fix the prototype pollution vulnerability, we need to ensure that the `typeName` and `fieldName` values cannot be special property names like `__proto__`, `constructor`, or `prototype`. We can achieve this by adding a validation step before using these values to delete properties from the `result` object.
The best way to fix this problem without changing existing functionality is to add a check to ensure that `typeName` and `fieldName` are not one of the special property names. If they are, we should skip the deletion operation.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix for code scanning alert no. 29: Prototype-polluting assignment

website/src/content/schema-directives.mdx
Clarify usage GraphQL Modules with Schema Directives with relevant example.
Only documentation updated, no code changes.
Updated documentation. Builded docs and checked that provided change is shown on localhost web site.
=> Add example to use schema directives with GraphQL modules

.changeset/huge-clocks-turn.md, packages/mock/src/addMocksToSchema.ts, packages/mock/tests/addMocksToSchema.spec.ts
Modifies the `typeResolver` to use the resolved __typename before using the mocked `$ref`'s type.
Resolves https://github.com/ardatan/graphql-tools/issues/7209
- OS: macos
- `@graphql-tools/...`: latest
- NodeJS: v22.13.1
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you considered, etc...
=> preserve resolvers should use the resolved typename

.changeset/three-impalas-love.md, packages/utils/src/Interfaces.ts
This PR aims to ease the development of GraphQL Gateways (like Hive Gateway) by adding an optional `subgraphName` property to the `ExecutionRequest` type. This property can be populated with the targeted subgraph name by the Gateway to make it easier to identify them.
Related to https://github.com/graphql-hive/gateway/issues/1311
This will allow to remove an annoying point in Hive Gateway Plugin development: The subgraph name can't be access directly from `onFetch` hook. It has to be retrieve from a global weak map with the execution request as a key. With this change, the subgraph name will be directly accessible and easy to find for new developers.
=> feat(utils): Add `subgraphName` to `ExecutionRequest` type

packages/graphql-tag-pluck/package.json, packages/graphql-tag-pluck/src/index.ts, packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts
TL;DR: this package has a dependency on `@vue/compiler-sfc` which updated two years ago in a non-backwards compatible way. Minor changes are required so that this package conforms to the changes in https://github.com/vuejs/core/pull/8083
Fixes #6945 (cc @felixxxxxs)
vue's composition API (most common syntax as of Vue 3) heavily leverages compiler macros. As part of the implementation of this feature, vue's SFC compiler requires two things:
1. The module `typescript` to be registered with `@vue/compiler-sfc` ([code pointer](https://github.com/vuejs/core/blob/eca0e1c/packages/compiler-sfc/src/script/resolveType.ts#L845))
2. Parsed files to include a file path for the purpose or resolving local imports ([code pointer](https://github.com/vuejs/core/blob/eca0e1c/packages/compiler-sfc/src/parse. …
=> support parsing vue single-file-components using composition API

.changeset/@graphql-tools_merge-7298-dependencies.md, .changeset/fine-beers-wear.md, packages/merge/package.json, packages/merge/src/links.ts, packages/merge/src/typedefs-mergers/merge-typedefs.ts
Removes the dependency "@theguild/federation-composition" from "@graphql-tools/merge" by creating a lightweight copy of the code used for extracting and resolving linked schema types' names.
Related https://github.com/ardatan/graphql-tools/issues/7290
Existing unit tests cover the link extraction/resolving behavior.
=> Replace dependency @theguild/federation-composition in graphqlt-tools/merge

.changeset/solid-loops-feel.md, packages/import/src/index.ts, packages/import/tests/schema/fixtures/path-aliases/absolute/a.graphql, packages/import/tests/schema/fixtures/path-aliases/absolute/b.graphql, packages/import/tests/schema/fixtures/path-aliases/node-subpath/a.graphql, packages/import/tests/schema/fixtures/path-aliases/node-subpath/b.graphql, packages/import/tests/schema/import-schema.spec.ts
This change fixes a minor bug from #7310 that affects users of path aliases - a feature that lets GraphQL users leverage [tsconfig.json#paths](https://www.typescriptlang.org/tsconfig/#paths) aliasing syntax for GraphQL imports.
The issue stems from the original implementation's execution order. Path alias resolution happens inside `resolveFilePath`, which only runs for non-absolute paths:
```ts
if (!isAbsolute(filePath) && !(filePath in predefinedImports)) {
filePath = resolveFilePath(cwd, filePath, pathAliases);
}
```
This means path aliases like `@/*` → `src/*` work correctly, but absolute path aliases like `/*` → `src/*` fail since they never reach the resolution logic.
The solution is straightforward: move path alias resolution before the absolute path check instead of after it. …
=> support absolute path aliases

.changeset/yummy-phones-punch.md, packages/import/src/index.ts
`@graphql-tools/import` is missing support for newer federation features.
=> import support for federation v2.10
