package.json
src/schemaGenerator.js
test/discourse-api/schema.js
test/testSchemaGenerator.js

At last I wrote some code today...

Add additional tests for likely schema mistakes

---

src/Logger.js
src/schemaGenerator.js
test/testLogger.js
test/testSchemaGenerator.js
test/tests.js

Adds logging to resolvers to avoid having to guess where the errors came from

Resolve error logging

---

.gitignore
.npmignore
package.json
resources/prepublish.sh

Avoid linking

---

package.json
resources/prepublish.sh
src/schemaGenerator.js
src/tracing.js
test/testTracer.js
test/tests.js

Does what the commit message says...

Add basic tracing to resolve functions

---

src/mock.js
test/testMocking.js

This fixes https://github.com/apollostack/graphql-tools/issues/17

Add enum support to mocking

---

package.json
src/schemaGenerator.js
test/circularSchemaA.js
test/circularSchemaB.js
test/testSchemaGenerator.js

Implements https://github.com/apollostack/graphql-tools/issues/20

Schema imports

---

package.json
src/apolloServer.js
src/index.js
src/schemaGenerator.js
test/testApolloServer.js
test/testSchemaGenerator.js
test/tests.js

Apollo http server

---

src/index.js

export attachConnectorsToContext in index.js

---

package.json
src/apolloServer.js
src/index.js
src/schemaGenerator.js
src/tracing.js
test/testApolloServer.js
test/testTracer.js

* use fork of express-graphql for server profiling
* implement Tracer
* automatically add tracing to resolve functions when tracer is provided

Implement first prototype of tracing

---

package.json
src/apolloServer.js
src/schemaGenerator.js
src/tracing.js
test/testTracer.js

Add an option to turn off reporting and add a bunch of tests to get all lines covered.

Tracer improvements

---

.travis.yml

updated node versions in travis.yml

---

.eslintignore
.eslintrc.json
package.json
test/circularSchemaA.js
test/circularSchemaB.js
test/discourse-api/discourse-context.js
test/discourse-api/schema.js
test/testMocking.js
test/testSchemaGenerator.js

eslint config

---

test/testDiscourseSchema.js
test/testLogger.js
test/testSchemaGenerator.js

rewrite tests to use makeExecutableSchema

---

test/testSchemaGenerator.js

add test for resolverValidationOptions to be object

---

src/index.js

export addSchemaLevelResolveFunction

---

CHANGELOG.md
package.json
src/index.js

Fix build dist

---

CHANGELOG.md
src/schemaGenerator.js
test/testSchemaGenerator.js

run schemaLevelResolveFunction once per tick

---

src/mock.js
test/testMocking.js

per #35, This PR adds the resolveType for unions and interfaces.

default ResolveType function in mockServer

---

src/schemaGenerator.js

improve runOnlyOnce function reliability

---

CHANGELOG.md
package.json

Version 0.6.4

---

CHANGELOG.md
src/schemaGenerator.js
test/testSchemaGenerator.js

make allowUndefinedInResolve true by default

---

src/schemaGenerator.js

Fix typeDefs error message

---

test/testMocking.js

Continuation of #121 
Added extra testcase to make sure resolver can return null to specify undefined behavior.
TODO:

Added additional test for null resolve test-case

---

src/mock.ts
src/schemaGenerator.ts
src/test/testMocking.ts
src/test/testSchemaGenerator.ts

TODO:
No need to for changelog i assume :)

Added more tests to reach 100% coverage

---

src/schemaGenerator.ts
src/test/testMocking.ts

Get coverage back to 100% after ES5 transformation

---

CHANGELOG.md
src/mock.ts
src/test/testMocking.ts

fix(mock): Fixed error handling on preserveResolvers (#149)

---

src/test/testAutopublish.ts

test(autopublish): fix race condition

---

package.json
src/autopublish.ts
src/index.ts
src/schemaGenerator.ts
src/test/testAutopublish.ts
src/test/testSchemaGenerator.ts
src/test/tests.ts

TODO:
1. implement function -> 10 minutes
2. write tests -> 2 hours 😑

WIP: trying out autopublish for mutation results

---

package.json

return dependencies back to original repo

---

.travis.yml
.vscode/settings.json
CHANGELOG.md
README.md
package.json
src/Interfaces.ts
src/autopublish.ts
src/schemaGenerator.ts
src/test/testSchemaGenerator.ts
tslint.json

Change defaults for next minor release

---

CHANGELOG.md

Update changelog for 0.8.2

---

CHANGELOG.md
package.json

Fixes https://github.com/apollostack/graphql-tools/issues/198
TODO:

Remove dependency on graphql-subscriptions

---

package.json
src/mock.ts

Moved from using node-uuid to uuid

---

package.json

Should solve the issues faced by #223

Updated TS version to 2.1.4

---

CHANGELOG.md
package.json
tsconfig.json

small fixes for next release

---

README.md

Readme: clarify where makeExecutableSchema comes from

---

CHANGELOG.md
src/Interfaces.ts
src/autopublish.ts

Use an interface instead of PubSub from graphql-subscriptions

---

package.json

So it doesn't break our build.

Pin version of chai to 3.4.35

---

CHANGELOG.md
src/mock.ts
src/test/testMocking.ts

bug fix. added type check for addMockFunctionsToSchema first arg

---

README.md

Point to Launchpad

---

README.md

Improve code sample

---

CHANGELOG.md

Added changelog for #373 PR

---

src/stitching/addTypenameForFragments.ts
src/stitching/mergeSchemas.ts
src/stitching/resolveFromParentTypename.ts
src/test/testMergeSchemas.ts
src/test/testingSchemas.ts

Add support for unions and interfaces

---

src/test/testMergeSchemas.ts

Test that reproduces the issue fixed by #401

[schema-stitching]: __typename test

---

src/mock.ts
src/test/testMocking.ts

I have created a test case that reproduces the bug outlined in issue #362.
I have been searching for a solution to this bug for quite a while but I cannot find it unfortunately. 
I was wondering if someone could help me locate and fix this bug:)

Instanceof check in resolveType bug

---

CHANGELOG.md
LICENSE
README.md
package.json

Wait to merge until the relevant docs PR is merged.
TODO:

Small cleanups

---

CHANGELOG.md
src/stitching/mergeSchemas.ts
src/test/testingSchemas.ts

Allow referring to query and mutation types from types

---

CHANGELOG.md
package.json

Make graphql typings dev dependency and flexible

---

CHANGELOG.md

Add v to changelog versions

---

CHANGELOG.md
package.json
src/stitching/mergeSchemas.ts
src/stitching/schemaRecreation.ts
src/stitching/typeFromAST.ts
src/test/testMergeSchemas.ts

Add ability to pass types in string extension definitions

---

src/schemaGenerator.ts

refactor(schemaGenerator): use one import

---

CHANGELOG.md
package.json
src/schemaGenerator.ts
src/stitching/introspectSchema.ts
src/stitching/linkToFetcher.ts
src/stitching/makeRemoteExecutableSchema.ts
src/test/testMergeSchemas.ts
src/test/testingSchemas.ts

Remove direct Apollo Link dependency

---

docs/source/resolvers.md

just fixing these as I see them :)

docs(graphql-tools): update broken links

---

src/stitching/mergeSchemas.ts
src/stitching/typeFromAST.ts
src/test/testMergeSchemas.ts

Resolve type on merged level

---

CHANGELOG.md
src/stitching/mergeSchemas.ts
src/stitching/typeFromAST.ts
src/test/testMergeSchemas.ts

Check that types are compatible when filtering fragments

---

docs/source/remote-schemas.md

Minor documentations fixies in remote-schemas.md
TODO:

Documentations fixies

---

CHANGELOG.md
src/stitching/schemaRecreation.ts
src/test/testMergeSchemas.ts
src/test/testingSchemas.ts

Pass the default value of input objects through

---

docs/source/scalars.md

Add docs for enums

---

CHANGELOG.md
src/Interfaces.ts
src/stitching/mergeSchemas.ts
src/test/testMergeSchemas.ts

Allow using plain usual objects for resolvers by removing mergeInfo closure

---

docs/source/mocking.md

Document array constructor parameter as inclusive

Document array constructor parameter as inclusive

---

src/stitching/delegateToSchema.ts
src/stitching/index.ts
src/stitching/mergeSchemas.ts

Currently part of unofficial, unsupported and undocumented API.
TODO:

Expose createDocument and delegateToSchema

---

CHANGELOG.md
src/stitching/makeRemoteExecutableSchema.ts

Added `typeDefs` param to `makeRemoteExectuableSchema`

---

docs/source/remote-schemas.md

Fixed code sample for authentication headers

---

docs/source/scalars.md

doc: fix links for custom scalar page

---

docs/source/scalars.md

GraphQL spec: http://facebook.github.io/graphql/October2016/#sec-ID
TODO:

doc: add ID as scalar type

---

src/stitching/mergeSchemas.ts
src/test/testMergeSchemas.ts

Guard against schemas without QueryType

---

CHANGELOG.md
designs/connectors.md
docs/source/resolvers.md
docs/source/schema-stitching.md

PR created using https://github.com/tbroadley/github-spellcheck-cli.

docs: fix typos

---

docs/source/mocking.md

doc: fix Generating schema URL on Mocking page

---

src/stitching/delegateToSchema.ts

Add document validation to `delegateToSchema`

---

package.json

https://github.com/SitePen/remap-istanbul/issues/160

Upgrade remap-istanbul

---

CHANGELOG.md
src/stitching/errors.ts

Don't use Symbol if you can't

---

package.json

Pinned apollo link

---

src/stitching/linkToFetcher.ts

TODO:
Not an issue, but is referenced in a TODO in the code

Remove old Apollo link code

---

docs/source/generate-schema.md

Resolvers are optional arguments

---

CHANGELOG.md
src/stitching/index.ts

Please let me know if any changes are needed.
TODO:

expose defaultMergedResolver from stitching

---

docs/_config.yml

Improve related docs section

---

CHANGELOG.md
docs/source/schema-directives.md

fix typo in schema-directives.md

---

src/stitching/delegateToSchema.ts

graphql -> execute

---

package.json

TODO:
Does this need to be in the changelog?

let the lint script work on windows and improve speed

---

docs/source/resolvers.md

Fix broken link in resolvers.md

---

package.json

Force apollo-link version to avoid type problems

---

docs/source/schema-stitching.md

Updated a few examples of `delegateToSchema` to use the latest API.
Not sure about ‘mergeInfo and delegateToSchema’ section of `schema-stitching.md`, especially this (old) bit:
>`delegateToSchema` allows delegating to any GraphQLSchema, while adding `fragmentReplacement` transforms. It's identical to `delegateToSchema` function otherwise.

Fix examples of delegateToSchema

---

docs/source/schema-delegation.md

Fix broken link in schema-delegation.md

---

docs/source/schema-transforms.md
src/transforms/ReplaceFieldWithFragment.ts

Fix fragments bug in ReplaceFieldWithFragment

---

src/stitching/mergeSchemas.ts

Fix right schema reference in onTypeConflict info

---

docs/source/remote-schemas.md

Update remote schema docs with async/await

---

src/stitching/delegateToSchema.ts

Default `operation` prop to `info.operation.operation`

---

src/schemaVisitor.ts
src/test/testDirectives.ts

fix(schemaVisitor): allow multiple replacing visitors

---

docs/source/schema-delegation.md

Fix missing { in Schema Delegation docs

---

src/transforms/ExpandAbstractTypes.ts

Fixes https://github.com/apollographql/graphql-tools/issues/769
TODO:

Fixed possible undefined from getPossibleTypes

---

src/makeExecutableSchema.ts

De-factor makeExecutableSchema

---

docs/source/resolvers.md

Update link to context documentation

---

src/mock.ts

TODO:
Reduce import cost of GraphQL dependencies on mocks

Reduce import cost mock component

---

docs/source/schema-directives.md

Schema directives: fix typo

---

docs/source/mocking.md

This is just a small change to the mocking documentation. It seems like some words were crossed (UI / backend) so the intention wasn't correctly expressed. Changed up the sentence flow a bit to read more easily as well.

Correct description on mocking

---

docs/source/schema-directives.md

missing comma in doc

---

docs/source/schema-transforms.md

fixed arbitrarily

---

CHANGELOG.md
docs/source/mocking.md

TODO:
Closes #947 
CC: @hwillson

Add docs for mockServer

---

CHANGELOG.md
docs/source/schema-stitching.md

TODO:
- [] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [] Make sure all of the significant new logic is covered by tests
- [] Rebase your changes on master so that they can be merged easily
- [] Make sure all tests and linter rules pass
Just an update on the docs to add a missing property to `mergeSchemas`.

docs: add missing api to mergeSchemas

---

CHANGELOG.md
src/Interfaces.ts

Add missing TArgs generic

---

docs/package-lock.json
docs/package.json

This branch upgrades the Gatsby theme to fix Google Analytics

Upgrade gatsby theme for a GA fix

---

docs/source/index.md

Deleted the link to the example in the Apollo Launchpad.
TODO:

"hello world" example deleted

---

docs/source/schema-stitching.md

Federation: Add deprecation notice for schema stitching

---

README.md

Remove launchpad link

---

docs/source/remote-schemas.md

fix(typo): typo in import example (: instead of ;)

---

docs/source/index.mdx

Fix typo of heading "The GitHunt-API example"

Fix heading format

---

docs/source/resolvers.md

Noticed a small typo in docs, fix for that 😅

Remove typo

---

docs/source/mocking.md

Just a docs update to remove a "broken" link

Remove reference to deprecated service

---

docs/package-lock.json
docs/package.json

Update dependency gatsby-theme-apollo-docs to v3.1.2

---

src/Interfaces.ts
src/test/schemaGenerator.test.ts

Allow to use a map of extensions in a field resolver

---

src/wrap/transforms/RenameRootTypes.ts
src/wrap/transforms/RenameTypes.ts

Returning undefined should not change the type name.
Closes https://github.com/apollographql/graphql-tools/pull/1170

fix(renameTypes): allow undefined renamer result

---

src/wrap/resolvers.ts
src/wrap/wrapSchema.ts

- remove unnecessary config for addResolversToSchema
- remove extra maps and functions

refactor(resolvers): code cleanup

---

src/wrap/index.ts
src/wrap/makeRemoteExecutableSchema.ts

transforms implementation may change in future versions
also includes change to internal name of defaultCreateRemoteResolver to match exported name

fix(exports): further streamline exports

---

docs/source/scalars.md

Add notes on GraphQL Scalars library on "Using a package" scalar section

docs: Add notes on GraphQL Scalars library

---

src/Interfaces.ts
src/delegate/createRequest.ts
src/test/requests.test.ts

Allow creation of a request independent of an existing execution context.

feat(createRequest): allow bare requests

---

docs/source/schema-stitching.md
jest.config.js
src/Interfaces.ts
src/stitch/mergeSchemas.ts
src/utils/SchemaDirectiveVisitor.ts

typeof SchemaDirectiveVisitor does not handle generics
hopefully closes #1376

fix(visitSchemaDirectives): broken types

---

package.json
scripts/bump.js

chore(scripts): move bump

---

CHANGELOG.md
src/test/directives.test.ts
src/utils/visitSchema.ts

Fix visitEnumValue to allow modifying the enum value

---

src/test/transforms.test.ts

This test passes using the included FilterObjectFields transform.
Although the original AST is still preserved in the transform (in order to preserve directives that are being used as metadata), schema recreation does not depend on the original AST, which would be dangerous, as it can be heavily modified by all prior transforms.

add test to replace #766

---

package.json
src/mock/index.ts
src/test/mocking.test.ts
src/utils/SchemaVisitor.ts
src/utils/visitSchema.ts

Avoid instanceof usage to support different non-breaking versions

---

website/docs/mocking.md

I fixed small mistake in sample code.
In the schema, it was usage, but in the sample code, it was person.
TODO:

Fixed small mistake in sample code

---

src/Interfaces.ts
src/delegate/createRequest.ts
src/delegate/transforms/FilterToSchema.ts
src/stitch/typeFromAST.ts
src/test/alternateStitchSchemas.test.ts
src/test/fixtures/schemas.ts
src/utils/updateArgument.ts
src/wrap/transforms/MapFields.ts

graphql-js converts these to null
See https://github.com/graphql/graphql-js/issues/2533

do not send variables with value undefined

---

packages/utils/src/heal.ts
packages/utils/tests/directives.test.ts
packages/wrap/tests/gatsbyTransforms.test.ts

Within v4, schema healing was less agressive and did not attempt to refresh the schemas private variables and correct the root types.
Reversion to the less agressive healSchema makes some sense.
Library users require healSchema because they are modifying the schema in place using visitSchema or visitSchemaDirectives. This lets them do some things that perhaps they shouldn't (e.g. create fields of different types with identical names), but it is unexpected for the more aggressive healing to actually fail where the less agressive healing works fine.
See https://github.com/ardatan/graphql-tools/issues/1462
This requires a rewrite of the existing Gatsby transforms which had been changed to rely on the more aggressive healSchema within graphql-tools-fork and graphql-tools v5, but this is …

restore v4 healSchema functionality

---

packages/utils/tests/directives.test.ts

compare original error as comparing GraphQL errors is trickier

fix latest test

---

packages/delegate/src/delegateToSchema.ts
packages/delegate/src/results/handleObject.ts
packages/stitch/src/stitchSchemas.ts
packages/stitch/src/stitchingInfo.ts
packages/stitch/src/typeCandidates.ts
packages/stitch/src/types.ts
packages/stitch/tests/alternateStitchSchemas.test.ts

rename mergeInfo to stitchingInfo
stash on extensions instead of annotating info argument
closes #1486

Stitching info

---

website/docs/resolvers-composition.md

Updated the resolvers composition page to indicate the correct package to import as the composeResolvers function is not available in the utils package.

Documentation Update for Resolver Composition

---

packages/wrap/src/transforms/TransformRootFields.ts

TransformRootFields, FilterRootFields and RenameRootFields were previously hard-coding root type names -- these may be customized and should be read from the schema at transformation time.
Closes #1596

transforms should support custom root type names

---

CHANGELOG.md
packages/graphql-tag-pluck/src/config.ts
packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts

Update graphql tag pluck to include flow plugins whenever the code includes @flow

---

packages/schema/src/makeExecutableSchema.ts

pruningOptions are optional, leaving them out should skip pruning, rather than pruning with all options disabled.

Fix pruning types x2

---

packages/utils/src/build-operation-for-field.ts

fix for missing enum in build operation node for field method

---

packages/delegate/package.json
packages/delegate/src/delegateToSchema.ts
packages/delegate/src/results/handleNull.ts
packages/utils/package.json
packages/utils/src/validate-documents.ts
packages/utils/tests/validate-documents.spec.ts
packages/wrap/src/introspect.ts
yarn.lock

Use non-node friendly aggregate error

---

packages/delegate/src/proxiedResult.ts
packages/delegate/src/results/handleObject.ts
packages/stitch/tests/typeMerging.example.test.ts
packages/stitch/tests/typeMerging.test.ts

= Fix cases where keys differ across subschemas
= Fix multiple rounds of type merging
Closes #1697.
Thanks to @flux627 for reporting.

Fixes for complex type merging

---

packages/load/src/schema.ts

fix(loadSchema): add optional chaining
TODO:

fix(loadSchema): add optional chaining

---

packages/stitch/tests/alternateStitchSchemas.test.ts

When attempting to use WrapType on a Mutation type you just get back `null` for the data and the resolver isn't hit.
I've added a test to demonstrate this behaviour, using the `bookingSchema` as it was the only one with a mutation.
I've also refactored the existing passing test for using WrapType on a Query type to use the same `bookingSchema` so the tests are more comprehensible together.

Add (failing) test for WrapType mutation

---

packages/delegate/src/getFieldsNotInSubschema.ts
packages/delegate/src/memoize.ts
packages/delegate/src/mergeFields.ts
packages/delegate/src/results/handleObject.ts

See https://github.com/ardatan/graphql-tools/issues/1710#issuecomment-652393288

use memoization when type merging with lists

---

packages/links/tests/upload.test.ts

See:
https://github.com/graphql/express-graphql/releases/tag/v0.10.0
https://github.com/graphql/express-graphql/pull/626

fix express-graphql usage

---

packages/stitch/src/typeCandidates.ts

allow merging scalars

---

website/docs/merge-typedefs.md

Correct loadFilesSync docs

---

packages/delegate/src/delegationBindings.ts
packages/delegate/src/transforms/AddSelectionSets.ts

to easily add dynamic selection sets (functions)
see #1709

change args order

---

website/docs/remote-schemas.md

fix imports

---

packages/stitch/src/stitchingInfo.ts
packages/stitch/tests/alternateStitchSchemas.test.ts

fix typos! add tests!
https://github.com/ardatan/graphql-tools/discussions/1709#discussioncomment-39154

fix and actually introduce dynamic selection sets

---

website/docs/schema-stitching.md
website/docusaurus.config.js

add more type merging config options

chore(docs): [deploy_website]

---

website/docs/remote-schemas.md

See: https://github.com/ardatan/graphql-tools/issues/1924#issuecomment-676431108
Thanks @tomasstrejcek for finding this.

[deploy website] fix ICreateProxyingResolverOptions

---

packages/utils/src/build-operation-for-field.ts

Related https://github.com/ardatan/graphql-tools/pull/1928#issuecomment-680765945

fix(build-operation-for-field): respect field depth

---

website/docs/merge-schemas.md

Just docs. Straight copy from https://github.com/ardatan/graphql-tools/discussions/1894

docs: difference between stitching and merging

---

packages/delegate/src/Subschema.ts
packages/delegate/src/delegateToSchema.ts
packages/delegate/src/index.ts
packages/delegate/src/types.ts
packages/delegate/tests/batchExecution.test.ts
packages/stitch/src/stitchSchemas.ts
packages/stitch/src/types.ts

to improve ergonomics of sharing endpoint details between subschemas

enhance(stitch): introduce SubschemaSetConfig

---

website/docs/server-setup.md

Make sure to destructure graphqlHTTP out of express-graphql

---

packages/stitch/tests/alternateStitchSchemas.test.ts
packages/wrap/src/transforms/HoistField.ts

By default, only the hoisted fields arguments are allowed. By configuration, you can also allow specification of arguments along the hoisted path.

enhance(HoistFields): allow arguments

---

packages/import/src/index.ts

Ref https://github.com/ardatan/graphql-tools/issues/2044
TODO:

feat(import): support specifiedBy builtin directive

---

.changeset/forty-chicken-drum.md
packages/graphql-tag-pluck/src/index.ts
packages/graphql-tag-pluck/src/utils.ts
packages/graphql-tag-pluck/src/visitor.ts
packages/graphql-tag-pluck/tests/__snapshots__/graphql-tag-pluck.test.ts.snap
packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts

Continue: https://github.com/ardatan/graphql-tools/pull/2079

allow to skip identation while plucking

---

.changeset/thick-pumas-compare.md
packages/loaders/url/src/index.ts
packages/loaders/url/tests/url-loader.spec.ts

feat(url-loader): handle graphql sdl

---

README.md

A very simple example of using graphql-express.
The idea here is to provide a fully functional example in readme.

Adding example of using graphql-express

---

.changeset/many-bats-yell.md
packages/wrap/src/transforms/HoistField.ts

fix(wrap): keep transformedSchema argument optional

---

.changeset/silver-zebras-itch.md
packages/graphql-tag-pluck/src/config.ts

feat(graphql-tag-pluck): Support Vue files with TypeScript

---

.changeset/breezy-snakes-hope.md
packages/stitch/src/stitchingInfo.ts
packages/stitch/tests/mergeAbstractTypes.test.ts

fix(stitch): support type merging with abstract types

---

.changeset/dull-cobras-bake.md
packages/links/src/linkToExecutor.ts
packages/links/src/linkToSubscriber.ts
packages/links/src/types.ts

also pass extensions
#2105, #2111, #2138

fix(links): use identical ExecutionParams

---

.changeset/thin-actors-attend.md
packages/links/package.json
packages/links/src/linkToExecutor.ts
packages/links/src/linkToSubscriber.ts
packages/links/src/types.ts

fix(links): refactor and fix types

---

website/docs/merge-resolvers.md

TODO:
I added the missing equal sign. Cheers.

docs(merge-resolvers): add missing equal sign

---

.changeset/lucky-garlics-approve.md
packages/loaders/url/declarations.d.ts
packages/loaders/url/package.json
packages/loaders/url/src/index.ts
yarn.lock

feat(url-loader): support loadSync

---

packages/delegate/src/resolveExternalValue.ts
packages/utils/tests/validate-documents.spec.ts

fix(delegate): import AggregateError polyfill

---

.changeset/thick-houses-divide.md

add changeset

---

website/docs/mocking.md

docs: Fix broken link in mocking.md

---

website/docs/server-setup.md

Hey hey 👋,
[`graphql-ws` has changed a bit as of v2](https://github.com/enisdenjo/graphql-ws/releases/tag/v2.0.0), this small PR reflects that. :D

docs: Update graphql-ws example

---

.changeset/violet-sloths-mate.md
packages/stitch/tests/mergeInterfaces.test.ts

see #2285
= enhance tests
= add changeset

complete abstract type merging fix

---

.changeset/quick-otters-float.md
packages/batch-delegate/tests/typeMerging.example.test.ts
packages/stitch/src/stitchingInfo.ts
packages/stitch/tests/fieldSelectionSets.test.ts
packages/stitch/tests/mergeAbstractTypes.test.ts
packages/stitch/tests/mergeComputedFields.test.ts
packages/stitch/tests/mergeConflicts.test.ts
packages/stitch/tests/mergeFailures.test.ts
packages/stitch/tests/mergeInterfaces.test.ts
packages/stitch/tests/typeMerging.test.ts

https://discord.com/channels/625400653321076807/631489932334202882/782758068168818709

fix(typeMerging): support transforms that rename types

---

.changeset/calm-schools-turn.md
packages/wrap/src/transforms/TransformCompositeFields.ts

attempt to rerelease...
also includes correction to typo in `@graphql-tools/wrap`

fix release

---

website/docs/remote-schemas.md

Rename to `graphql-ws`

---

.changeset/gold-rivers-fail.md
packages/loaders/url/declarations.d.ts
packages/loaders/url/package.json
packages/loaders/url/src/index.ts
packages/loaders/url/tests/url-loader.spec.ts
yarn.lock

feat(url-loader): handle HTTP result as an SDL with handleAsSDL option

---

.changeset/stupid-pumas-cross.md
packages/delegate/src/resolveExternalValue.ts
packages/stitch/tests/typeMerging.test.ts

fix(delegate): resolve external objects only once

---

.changeset/warm-donuts-sneeze.md
packages/utils/src/visitSchema.ts

fix(utils): fix crashs when return null while visitSchema

---

.changeset/thick-ducks-heal.md
packages/stitch/tests/typeMergingWithExtensions.test.ts
packages/stitching-directives/src/defaultStitchingDirectiveOptions.ts
packages/stitching-directives/src/stitchingDirectivesTransformer.ts
packages/stitching-directives/src/stitchingDirectivesValidator.ts
packages/stitching-directives/src/types.ts
packages/utils/src/SchemaDirectiveVisitor.ts
packages/utils/src/get-directives.ts
website/docs/legacy-schema-directives.md
website/docs/schema-directives.md

follows gatsby and graphql-compose convention but allow customization
see: https://github.com/graphql/graphql-js/issues/1343#issuecomment-479877640

enhance(utils): read directives from extensions

---

.changeset/little-spiders-reply.md
packages/utils/src/astFromValueUntyped.ts
packages/utils/src/index.ts
packages/utils/src/print-schema-with-directives.ts
packages/utils/tests/print-schema-with-directives.spec.ts

should print directive usages even if directive are not actually defined in the schema

fix(printSchemaWithDirectives): usage without defs

---

.changeset/twenty-carrots-jump.md
packages/stitch/src/isolateComputedFields.ts
packages/stitch/src/stitchingInfo.ts
packages/stitch/tests/typeMergingWithInterfaces.test.ts

https://github.com/ardatan/graphql-tools/pull/2432#issuecomment-753729191
https://github.com/gmac/schema-stitching-handbook/pull/17

reproduced!

---

.changeset/giant-cooks-melt.md
packages/stitch/src/stitchingInfo.ts
packages/stitch/tests/nestedRootTypes.test.ts

Small fix related to #2349 
TODO:

fix(stitch): add __typename for mutations

---

website/docs/legacy-schema-directives.md

Fixes link to new schema directives article

docs: fix link to schema-directives

---

.changeset/plenty-moons-hide.md
.changeset/shiny-eagles-rescue.md
packages/import/src/index.ts
packages/loaders/graphql-file/src/index.ts
scripts/build-api-docs.js

Improve loaders

---

.changeset/pretty-suns-fetch.md
.changeset/violet-trainers-deny.md
packages/graphql-tag-pluck/src/index.ts
packages/schema/src/extendResolversFromInterfaces.ts
packages/schema/tests/schemaGenerator.test.ts

fix(schema): ignore resolvers if they are not in schema

---

website/docs/stitch-combining-schemas.md

Fixed two typos

---

.github/workflows/website.yml
algolia/config.json
patches/@docsearch+react+3.0.0-alpha.32.patch
website/docusaurus.config.js

This PR is related to https://github.com/the-guild-org/the-guild-website/issues/300

Added support for Multi-search

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR is related to https://github.com/the-guild-org/Stack/pull/9
- Added CODE OF CONDUCT to README
- Added Issue and PR templates

Added PR and ISSUE templates

---

.changeset/eighty-cars-marry.md
packages/batch-delegate/src/getLoader.ts
packages/batch-delegate/src/types.ts

fix(batchDelegate): don't batch delegation to different root fields

---

website/docs/migration-from-tools.md

Related #2759
- [-] I have added tests that prove my fix is effective or that my feature works
- [-] New and existing unit tests and linter rules pass locally with my changes
- [-] Any dependent changes have been merged and published in downstream modules

Update migration-from-tools.md docs to better explain replacing fragments with selectionSets

---

.changeset/dirty-lizards-warn.md
packages/load-files/src/index.ts

noticed a few lines of code is redundant in the `loadFiles` function (compared to the `loadFilesSync`), so i just removed it in this pr, everything should works fine.

Remove duplicate logic from loadFiles

---

.gitignore

Recently, jest or something else seems to be populating the `.cache` folder on my machine
@ardatan are you ok with simply adding this to the `.gitignore`?

hide cache

---

.changeset/big-tomatoes-nail.md

add changeset for recent fix

---

website/docusaurus.config.js
website/package.json

Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components

[deploy_website] Algolia Config Removal

---

.changeset/silly-pets-reflect.md
packages/batch-execute/package.json
packages/batch-execute/src/createBatchingExecutor.ts
packages/delegate/package.json
packages/delegate/src/delegateToSchema.ts
packages/delegate/src/mergeFields.ts
packages/schema/package.json
packages/schema/src/addSchemaLevelResolver.ts
packages/stitch/package.json
packages/stitch/tests/fixtures/schemas.ts
packages/wrap/package.json
packages/wrap/src/introspect.ts
packages/wrap/tests/fixtures/schemas.ts
yarn.lock

use value-or-promise

---

website/docs/mocking.md

Added resolvers' usage with mockServer

---

.changeset/fluffy-melons-sleep.md
packages/resolvers-composition/src/resolvers-composition.ts

- [  ] Bug fix (non-breaking change which fixes an issue)
Visual testing. 
- OS:
- NodeJS:

Fixed type error for resolvers with typed arguments

---

website/docs/documents-loading.md
website/docs/loaders.md
website/docs/schema-loading.md

Added documentation on how to solve loader issues when the files loaded import other files using typescript path aliases.
Related #1544 
N/A
- OS: Linux
- `@graphql-tools/load-files`:^6.3.2
-  `@graphql-tools/schema`:^6.2.13
- NodeJS: 15.14.0
N/A

Added special note on file loading with typescript paths

---

website/docs/documents-loading.md
website/docs/schema-loading.md

Hi @ardatan, I noticed that the links I added in docs were broken in #2904 so I wanted to submit a quick fix -- I made the initial changes late at night.  Apologies for the extra work.

fix broken link in docs

---

website/docs/stitch-combining-schemas.md

Fix bad link

---

.changeset/nasty-worms-hope.md
.changeset/witty-fireants-bake.md
packages/loaders/url/tests/url-loader.spec.ts
packages/resolvers-composition/src/resolvers-composition.ts
packages/utils/src/getResolversFromSchema.ts

Related https://github.com/Urigo/graphql-mesh/issues/1889

Do not extract default resolvers and compose scalar configuration

---

.husky/pre-commit
package.json

configuration changed, ran the 4 to 6 tool
https://typicode.github.io/husky/\#/\?id\=husky-4-to-6-cli
Related #2781 
Development task
The hook ran when creating this PR's commit: 
```
$ git commit -m "chore(husky): finish migration
dquote> configuration changed, ran the 4 to 6 tool
dquote> https://typicode.github.io/husky/\#/\?id\=husky-4-to-6-cli"
yarn run v1.22.10
$ /home/pixnbits/projects/graphql-tools/node_modules/.bin/lint-staged
ℹ No staged files match any configured task.
Done in 1.25s.
[fix/husky-update 78a465db] chore(husky): finish migration configuration changed, ran the 4 to 6 tool https://typicode.github.io/husky/\#/\?id\=husky-4-to-6-cli
2 files changed, 4 insertions(+), 5 deletions(-)
create mode 100755 .husky/pre-commit
```
- OS: Linux
- …

chore(husky): finish migration

---

.changeset/eighty-books-develop.md
packages/load/tests/loaders/schema/schema-from-typedefs.spec.ts
packages/loaders/graphql-file/src/index.ts

Related # https://github.com/dotansimha/graphql-eslint/issues/507

fix(file-loader): location path must be normalized

---

packages/delegate/src/delegationBindings.ts
packages/delegate/src/types.ts
packages/stitch/src/stitchingInfo.ts

refactor: internal StitchingInfo properties

---

packages/delegate/src/getFieldsNotInSubschema.ts
packages/delegate/src/transforms/AddSelectionSets.ts

and make fewer loops
follow up to #3199

refactor: use Set to avoid repetition

---

.changeset/ten-deers-return.md
packages/mock/package.json
packages/mock/src/MockStore.ts
yarn.lock

`ts-is-defined` and one of its dependencies are [causing some headaches for people](https://github.com/apollographql/apollo-server/issues/5505) with the `apollo-server` 3 upgrade. The assertion logic seems straightforward enough to port straight into the repo.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Removes ts-is-defined dependency from @graphql-tools/mock.

---

.changeset/serious-apes-check.md
packages/delegate/src/finalizeGatewayRequest.ts
packages/delegate/tests/delegateToSchema.test.ts

fix(delegate): handle variables correctly

---

packages/wrap/src/transforms/TransformInputObjectFields.ts
packages/wrap/tests/transformFilterInputObjectFields.test.ts

Handle non-nullable input types in TransformInputObjectFields.
Related #3345 

fix(wrap): handle non nullable input variables correctly

---

.changeset/hip-weeks-buy.md
packages/loaders/url/package.json
yarn.lock

The dependency is used - see https://www.runpkg.com/?@graphql-tools/url-loader@7.0.11/index.d.ts#1
N/A
N/A
N/A

fix(url-loader): add missing dep on @types/ws

---

.changeset/happy-ants-pretend.md
.changeset/moody-months-turn.md
packages/batch-delegate/src/getLoader.ts
packages/delegate/src/finalizeGatewayRequest.ts
packages/delegate/src/types.ts
packages/load/src/load-typedefs/load-file.ts
packages/loaders/code-file/src/index.ts
packages/loaders/git/src/index.ts
packages/loaders/graphql-file/src/index.ts
packages/loaders/json-file/src/index.ts
packages/merge/src/typedefs-mergers/fields.ts
packages/stitch/src/stitchSchemas.ts
packages/stitch/src/stitchingInfo.ts
packages/stitch/src/typeCandidates.ts
packages/utils/src/heal.ts
packages/utils/src/helpers.ts
packages/utils/src/mapSchema.ts
packages/utils/src/rewire.ts

Thanks @IvanGoncharov for the note about `TypeMap`.

Remove `TypeMap` and improvements on loaders

---

.changeset/weak-queens-search.md
packages/wrap/src/transforms/MapLeafValues.ts
packages/wrap/tests/transformMapLeafValues.test.ts

Related #3540 
- [x ] Bug fix (non-breaking change which fixes an issue)
- …

Fixing variables missing on wrap/MapLeafValues transform

---

packages/load/tests/loaders/schema/schema-from-typedefs.spec.ts
packages/load/tests/loaders/schema/test-files/nested-imports/query.graphql
packages/load/tests/loaders/schema/test-files/nested-imports/types.graphql

PR with failing test for #3182
Related #3182

test: Test for parsing nested imports bug

---

website/docs/schema-directives.mdx

Fixes a slight uncertainty in the documentation, which may make it difficult for new users to understand where certain imports come from.

docs: Update Schema Directives example to include all required imports

---

.changeset/four-needles-smile.md
packages/loaders/github/tests/schema-from-github.spec.ts
packages/loaders/graphql-file/src/index.ts
packages/loaders/graphql-file/tests/loader.spec.ts
packages/loaders/json-file/src/index.ts
packages/loaders/json-file/tests/loader.spec.ts

Not sure if this is a breaking change or fix

fix(graphql/json-loader): raise error if any of the found files fails

---

.changeset/hip-cobras-explode.md
packages/mock/src/addMocksToSchema.ts
packages/mock/tests/mocking-compatibility.spec.ts

Follow on to https://github.com/ardatan/graphql-tools/pull/3613 to improve deep mocking with `preserveResolvers` option on. This PR covers extra use cases like non-null.
Unit tests

Update to deep mocking

---

.eslintrc.json
packages/delegate/tests/transforms.test.ts
packages/import/src/index.ts
packages/loaders/url/src/event-stream/handleEventStreamResponse.ts
packages/loaders/url/src/event-stream/handleReadableStream.ts
packages/loaders/url/src/handleMultipartMixedResponse.ts
packages/loaders/url/tests/url-loader.spec.ts
packages/node-require/src/index.ts
packages/schema/src/assertResolversPresent.ts
packages/schema/src/checkForResolveTypeResolver.ts
packages/schema/tests/schemaGenerator.test.ts
packages/stitch/tests/alternateStitchSchemas.test.ts
packages/stitch/tests/stitchSchemas.test.ts
packages/utils/src/declarations.d.ts
packages/utils/src/getArgumentValues.ts
packages/utils/src/inspect.ts
packages/utils/src/mergeDeep.ts

add `"reportUnusedDisableDirectives": true` to find unused ESLint directives

remove unused eslint directives

---

website/docs/remote-schemas.mdx

Closes https://github.com/ardatan/graphql-tools/issues/3959

docs: improve remote schema executor section

---

.changeset/sixty-students-leave.md
packages/loaders/code-file/src/load-from-module.ts

Include stack traces when encountering errors if possible

fix(code-file-loader): do not swallow stack traces

---

website/docs/mocking.mdx

While reading the docs, I had to ask the Guild about mocks, because it felt a bit unclear. It was suggested that I add a sentence to the docs. Hopefully, like after this change it would be a bit more descriptive than before 🙂
Screenshot from my chat with The Guild 👇🏻 
Related : [chat link](https://app.crisp.chat/website/af9adec5-ddfa-4db9-a4a3-25769daf2fc2/inbox/session_2247f5d0-4e6d-44d2-8af0-f1de034b3d74/)

Update docs per suggestion in user chat

---

.changeset/friendly-geckos-guess.md
packages/utils/src/getArgumentValues.ts

Context: https://github.com/dotansimha/envelop/pull/1183

Improve getArgumentValues check for null values

---

.changeset/strange-carpets-bake.md
packages/stitch/tests/alternateStitchSchemas.test.ts
packages/utils/src/prune.ts

make pruning recursive

---

benchmark/federation/index.js

using parse cache and graphql-executor should allow subschemas to perform cacheable work on fieldNodes because graphql-executor caches identical fieldNodes

use graphql-executor in benchmarks

---

website/docs/remote-schemas.mdx
website/docs/schema-loading.mdx
website/docs/schema-merging.mdx

* Add video embed for schema file loading 📺 
* Add video embed for schema merging 📺 
* Add video embed for remote schemas 📺 

docs: add wtf video embeds

---

packages/load/tests/custom-loader.js
packages/load/tests/loaders/documents/documents-from-glob.spec.ts
packages/load/tests/loaders/schema/integration.spec.ts
packages/load/tests/use-custom-loader.spec.ts

Instead of https://github.com/dotansimha/graphql-code-generator/issues/7213 & https://github.com/dotansimha/graphql-code-generator/pull/7304

Add tests for custom loader configuration

---

.changeset/tough-monkeys-attack.md
packages/wrap/src/transforms/RenameObjectFieldArguments.ts
packages/wrap/src/transforms/index.ts
packages/wrap/tests/transformRenameObjectFieldArguments.test.ts
website/docs/schema-wrapping.mdx

Linked to https://github.com/Urigo/graphql-mesh/issues/3654

feat(wrap): RenameObjectFieldArguments transform

---

packages/loaders/url/package.json
packages/loaders/url/tests/url-loader.spec.ts
yarn.lock

Can be merged after https://github.com/dotansimha/graphql-yoga/pull/1064

Add test for live queries

---

.changeset/ninety-stingrays-type.md
packages/loaders/url/declarations.d.ts
packages/loaders/url/package.json
packages/loaders/url/src/event-stream/handleAsyncIterable.ts
packages/loaders/url/src/event-stream/handleEventStreamResponse.ts
packages/loaders/url/src/event-stream/handleReadableStream.ts

Simplify SSE handling in UrlLoader

---

.changeset/tender-forks-yawn.md
packages/loaders/graphql-file/tests/loader.spec.ts
packages/loaders/graphql-file/tests/test-files/typedefs-&-copy.graphql
packages/utils/src/helpers.ts

This was an issue reported in codegen https://github.com/dotansimha/graphql-code-generator/issues/6174
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the …

feat: allow ampersand in file names to load

---

.github/workflows/release.yml

ci: pin release action version

---

website/docs/schema-directives.mdx

It wasn't clear on how to add multiple directives. Finding a discussion [here](https://github.com/ardatan/graphql-tools/discussions/3419) which helped and adding for documentation clarity.
Since this is a small documentation update an issue was not created first. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …

Add an example to map multiple custom directives.

---

.github/workflows/algolia-integrity.yml
.github/workflows/algolia-publish.yml
.github/workflows/benchmark.yml
.github/workflows/tests.yml
package.json

ci: use shared flows

---

packages/load/tests/loaders/documents/documents-from-glob.spec.ts
website/docs/documents-loading.mdx

closes https://github.com/ardatan/graphql-tools/issues/4620
closes https://github.com/ardatan/graphql-tools/issues/4685

docs: update documents-loading.mdx

---

.changeset/early-camels-listen.md
packages/utils/src/prune.ts
packages/utils/tests/prune.test.ts

Related #4693 
Tests are included in PR
- OS: macOS Monterey v12.4
- `@graphql-tools/utils`: 8.10.1
- NodeJS: v16.15.1
Some tests currently failing on the master branch on my machine. No new failing tests added
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

fix pruning of directive arg type

---

.eslintrc.cjs

https://tortilla-hq.slack.com/archives/C0115JCR4AK/p1667694414865899

Update .eslintrc.cjs, use `@typescript-eslint/no-restricted-imports`

---

.changeset/four-icons-hammer.md
packages/executors/http/src/index.ts
packages/executors/http/tests/buildHTTPExecutor.test.ts
packages/executors/http/tests/handleEventStreamResponse.test.ts

useGETForQueries was also activating GET for mutations

---

website/package.json
yarn.lock

Signed-off-by: Tuval Simha <tuval.simha@gmail.com> …

Website: update theguild/components

---

website/src/pages/docs/schema-loading.mdx

Simple docs update, wrong import for loading schema
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

chore: update schema-loading readme to use correct import

---

website/src/pages/docs/documents-loading.mdx

Signed-off-by: Tuval Simha <tuval.simha@gmail.com> …

Docs Loading blog: fix 404 routes links

---

.changeset/serious-dingos-care.md
packages/merge/src/typedefs-mergers/interface.ts

This is an attempt to remove the circular dependency as described in the big.
Related # 4985
#4985 
N/A
Since this is a deeply nested dependency, I modified my local setup and tested that the rollup script stopped complaining. 
Hopefully the manual test will suffice.
N/A
- [ x I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …

remove circular dependency, #4985

---

.changeset/beige-crabs-divide.md
packages/loaders/code-file/src/index.ts
packages/loaders/code-file/tests/load-from-code-file.spec.ts

#5004 
Related issue: https://github.com/dotansimha/graphql-code-generator/issues/8780
error reproduces sandbox:
solution sandbox: 
- Reproduce way: run `yarn test`
- How to verify: when an option that passes by the `load` function is an empty object, it shouldn't overwrite the config setup when constructed.
- OS: macOS 13.1
- `@graphql-tools` : in …

fix: Deep Copy Config Object When Merge Config.

---

.changeset/five-phones-pretend.md
packages/wrap/src/introspect.ts

N/A
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

fix: only warn about deprecated `introspectSchema` once

---

.changeset/@graphql-tools_batch-execute-5202-dependencies.md
.changeset/@graphql-tools_executor-5202-dependencies.md
.changeset/@graphql-tools_graphql-tag-pluck-5202-dependencies.md
.changeset/@graphql-tools_links-5202-dependencies.md
.changeset/@graphql-tools_schema-5202-dependencies.md
packages/batch-execute/package.json
packages/executor/package.json
packages/executors/envelop/package.json
packages/graphql-tag-pluck/package.json
packages/links/package.json
packages/loaders/url/package.json
packages/schema/package.json
packages/stitch/package.json
yarn.lock

Reorganize dependencies

---

packages/loaders/github/src/index.ts
packages/loaders/github/tests/schema-from-github.spec.ts

Currently the GitHub loader ignores any additional headers passed as `options` to it, for instance when calling `graphql-inspector diff 'github:foo:bar/baz' 'github:foo:bar/baz' --headers 'x-header: x-value'`.
This makes it harder as a user to pass extra info to the GitHub API like user agents as per https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#user-agent-required.
Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as …

Forward additional headers to github

---

.changeset/@graphql-tools_federation-5468-dependencies.md
.changeset/shiny-swans-wink.md
packages/federation/package.json
packages/federation/src/gateway.ts
packages/federation/src/supergraph.ts
packages/federation/src/utils.ts
packages/federation/test/gateway.test.ts
yarn.lock

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
expected)
- OS:
- …

Optimizations on Federation impl

---

website/src/pages/docs/resolvers.mdx

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
expected)
- OS:
- …

docs: improve examples by adding more context

---

packages/utils/src/helpers.ts

This PR fixes the path matching for files inside folders with `=` chars like.
For example SvelteKit supports route param matching for routes like this:
```
src/routes/[[locale]]/[[beta=beta]]/(authed)/admin/payment/+page.gql
```
https://kit.svelte.dev/docs/advanced-routing#matching
Related Issue:
https://github.com/dotansimha/graphql-code-generator/issues/3058#issuecomment-1701291642
Please describe the tests that …

fix isValid path regex for paths including `=`

---

.changeset/mean-jobs-tickle.md
packages/executors/http/src/handleAsyncIterable.ts
packages/executors/http/tests/handleEventStreamResponse.test.ts

Handle chunked and no-space messages in SSE

---

packages/schema/src/addResolversToSchema.ts
packages/schema/tests/schemaGenerator.test.ts

This PR introduces checks against `requireResolversToMatchSchema: 'warn'`. This was already suggested by the types but not reflected in the code.

Fix 'warn' for requireResolversToMatchSchema

---

.changeset/gentle-peas-hope.md
packages/batch-execute/src/mergeRequests.ts
packages/batch-execute/src/prefix.ts
packages/batch-execute/tests/batchExecute.test.ts

Fixes #5905
- OS: Mac
- `@graphql-tools/batch-execute`: 9.0.2
- NodeJS: v20.8.0

Avoid for...in loop on array

---

packages/executor/src/execution/__tests__/abort-signal.test.ts

reduces the test runtime by avoiding timers

feat: reduce abort signal test runtime to few ms

---

.changeset/eight-clocks-share.md
packages/executor/src/execution/__tests__/abort-signal.test.ts
packages/executor/src/execution/execute.ts
packages/executor/src/execution/normalizedExecutor.ts
packages/executor/src/execution/promiseForObject.ts

follow up for https://github.com/ardatan/graphql-tools/pull/6006

test: cancellation of subscription execution and stream execution

---

packages/merge/tests/merge-typedefs.spec.ts

Reproduction https://github.com/ardatan/graphql-tools/issues/5849

Add tests for merging the directives with the same name and arguments

---

.changeset/sour-pianos-smile.md
packages/federation/src/supergraph.ts
packages/federation/test/federation-compatibility.test.ts
packages/federation/test/fixtures/federation-compatibility/interface-object-with-requires/supergraph.graphql
packages/federation/test/fixtures/federation-compatibility/interface-object-with-requires/tests.json
packages/federation/test/fixtures/federation-compatibility/non-resolvable-interface-object/supergraph.graphql
packages/federation/test/fixtures/federation-compatibility/non-resolvable-interface-object/tests.json
packages/federation/test/fixtures/federation-compatibility/simple-interface-object/supergraph.graphql
packages/federation/test/fixtures/federation-compatibility/simple-interface-object/tests.json
packages/stitch/src/subschemaConfigTransforms/isolateComputedFieldsTransformer.ts

Closes https://github.com/ardatan/graphql-tools/issues/6073
Merged by mistake before. This PR's been created after revert.

feat(federation): interface objects

---

.changeset/poor-glasses-vanish.md
packages/delegate/src/extractUnavailableFields.ts
packages/federation/src/supergraph.ts
packages/federation/test/fixtures/federation-compatibility/corrupted-supergraph-node-id/supergraph.graphql
packages/federation/test/fixtures/federation-compatibility/corrupted-supergraph-node-id/tests.json
packages/stitch/src/createDelegationPlanBuilder.ts
packages/stitch/src/index.ts

See the changeset for more information

fix(federation): handle unresolvable interface fields and choose the best root field if there are many

---

packages/stitch/tests/isolateComputedFieldsTransformer.test.ts

Failing test case for issue: [Adding a computed property with a non-primitive/non-scalar return type breaks the schema when stitching ](https://github.com/ardatan/graphql-tools/issues/4956)
Related https://github.com/ardatan/graphql-tools/issues/4956
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

test(stitch): add failing test for complex computed return type

---

.changeset/dirty-colts-smell.md
package.json
packages/graphql-tag-pluck/src/index.ts
scripts/postbuild.ts

related https://github.com/dimaMachina/graphql-eslint/issues/2342
see that currently flat config fails in graphql-eslint https://github.com/dimaMachina/graphql-eslint/actions/runs/10227495892/job/28299017491?pr=2466

[graphql-tag-pluck] fix `require is not defined` for esm build

---

.changeset/silver-olives-poke.md
packages/inspect/package.json
packages/utils/package.json

I got the following error with nuxt:
```
[DEP0166] DeprecationWarning: Use of deprecated double slash resolving "./esm//index.js.js" for module request ".//index.js" matched to "./*" in the "exports" field module resolution of the package at D:\Programming\JabRefOnline\node_modules\.pnpm\node_modules\cross-inspect\package.json
[DEP0166] DeprecationWarning: Use of deprecated double slash resolving "./esm//index.cjs.js" for module request ".//index.cjs" matched to "./*" in the "exports" field module resolution of the package at D:\Programming\JabRefOnline\node_modules\@graphql-tools\utils\ …
```

fix: remove generic package export

---

.changeset/fuzzy-tips-invent.md
packages/loaders/url/package.json

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
Fixes #6624
expected)
- OS: …

chore(loaders/url): remove unused @graphql-tools/delegate dependency

---

packages/graphql-tag-pluck/package.json
yarn.lock

This reverts commit f7a2c13e1de80128d58a78a565712feca065d10c.
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
expected)
reproduce. Please also list any relevant details for your …

Revert "chore(deps): update dependency svelte2tsx to v0.7.25 (#6686)"

---

.changeset/swift-readers-fail.md
packages/import/src/index.ts

Fixes https://github.com/ardatan/graphql-tools/issues/6225

enhance(import): avoid `process` import

---

.changeset/four-bees-relate.md
packages/utils/src/registerAbortSignalListener.ts

Remove VoidFunction type

---

.changeset/@graphql-tools_utils-6822-dependencies.md
.changeset/new-squids-cheat.md
packages/utils/package.json
yarn.lock

https://security.snyk.io/vuln/SNYK-JS-DSET-7116691

Bump dset dependency handling the CVE-2024-21529

---

website/src/app/layout.tsx

fix footer

---

website/src/app/page.tsx

The link pointed to Yoga. Not it's fixed.

Fix the link to GitHub

---

packages/utils/src/comments.ts

Potential fix for [https://github.com/ardatan/graphql-tools/security/code-scanning/11](https://github.com/ardatan/graphql-tools/security/code-scanning/11)
To fix the problem, we need to ensure that backslashes are also escaped in the input string. This can be done by using a regular expression with the global flag to replace all occurrences of backslashes before handling other special characters. This approach ensures that all instances of backslashes are properly escaped, preventing any potential issues.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 11: Incomplete string escaping or encoding

---

package.json
yarn.lock

Reverts ardatan/graphql-tools#7033

Revert "chore(deps): update dependency typedoc to v0.28.1"

---

package.json
packages/graphql-tag-pluck/package.json
website/package.json
yarn.lock

Reverts ardatan/graphql-tools#7326

Revert "build(deps): bump the actions-deps group across 1 directory with 5 updates"

---

.changeset/@graphql-tools_links-7438-dependencies.md
packages/links/package.json
yarn.lock

Reverts ardatan/graphql-tools#7438

Revert "fix(deps): update dependency apollo-upload-client to v19"

---

package-lock.json
packages/loaders/github/package.json
packages/loaders/url/package.json
website/package.json

Reverts ardatan/graphql-tools#7458

Revert "Bump the actions-deps group across 1 directory with 3 updates"
